// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: import.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deactivateDishBySku = `-- name: DeactivateDishBySku :exec
UPDATE dishes SET active = FALSE, updated_at = now()
WHERE store_id = $1 AND sku = $2
`

type DeactivateDishBySkuParams struct {
	StoreID int64  `json:"store_id"`
	Sku     string `json:"sku"`
}

func (q *Queries) DeactivateDishBySku(ctx context.Context, arg DeactivateDishBySkuParams) error {
	_, err := q.db.Exec(ctx, deactivateDishBySku, arg.StoreID, arg.Sku)
	return err
}

const upsertDish = `-- name: UpsertDish :one
INSERT INTO dishes (store_id, sku, name, base_price, active, daily_limit, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (store_id, sku) DO UPDATE
SET name = EXCLUDED.name,
    base_price = EXCLUDED.base_price,
    active = EXCLUDED.active,
    daily_limit = EXCLUDED.daily_limit,
    sort_order = EXCLUDED.sort_order,
    updated_at = now()
RETURNING id, store_id, sku, name, base_price, active, daily_limit, sort_order, created_at, updated_at
`

type UpsertDishParams struct {
	StoreID    int64       `json:"store_id"`
	Sku        string      `json:"sku"`
	Name       string      `json:"name"`
	BasePrice  int64       `json:"base_price"`
	Active     bool        `json:"active"`
	DailyLimit pgtype.Int8 `json:"daily_limit"`
	SortOrder  int32       `json:"sort_order"`
}

// Batch import upsert keyed on (store_id, sku). Used inside one transaction by
// the import handler, which validates the whole batch first; any failure rolls
// the entire import back (all-or-nothing, max 500 items).
func (q *Queries) UpsertDish(ctx context.Context, arg UpsertDishParams) (Dish, error) {
	row := q.db.QueryRow(ctx, upsertDish,
		arg.StoreID,
		arg.Sku,
		arg.Name,
		arg.BasePrice,
		arg.Active,
		arg.DailyLimit,
		arg.SortOrder,
	)
	var i Dish
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Sku,
		&i.Name,
		&i.BasePrice,
		&i.Active,
		&i.DailyLimit,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
