// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: menu.sql

package db

import (
	"context"
)

const bumpStoreVersion = `-- name: BumpStoreVersion :exec
UPDATE stores SET menu_version = $2 WHERE id = $1
`

type BumpStoreVersionParams struct {
	ID          int64 `json:"id"`
	MenuVersion int64 `json:"menu_version"`
}

func (q *Queries) BumpStoreVersion(ctx context.Context, arg BumpStoreVersionParams) error {
	_, err := q.db.Exec(ctx, bumpStoreVersion, arg.ID, arg.MenuVersion)
	return err
}

type CopyVersionItemsParams struct {
	VersionID    int64  `json:"version_id"`
	Sku          string `json:"sku"`
	Name         string `json:"name"`
	BasePrice    int64  `json:"base_price"`
	DisplayOrder int32  `json:"display_order"`
}

const countVersionItems = `-- name: CountVersionItems :one
SELECT count(*) FROM menu_version_items WHERE version_id = $1
`

func (q *Queries) CountVersionItems(ctx context.Context, versionID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countVersionItems, versionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMenuVersion = `-- name: CreateMenuVersion :one
INSERT INTO menu_versions (store_id, version, note)
VALUES ($1, $2, $3)
RETURNING id, store_id, version, published_at, note
`

type CreateMenuVersionParams struct {
	StoreID int64  `json:"store_id"`
	Version int64  `json:"version"`
	Note    string `json:"note"`
}

func (q *Queries) CreateMenuVersion(ctx context.Context, arg CreateMenuVersionParams) (MenuVersion, error) {
	row := q.db.QueryRow(ctx, createMenuVersion, arg.StoreID, arg.Version, arg.Note)
	var i MenuVersion
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Version,
		&i.PublishedAt,
		&i.Note,
	)
	return i, err
}

const getLatestVersion = `-- name: GetLatestVersion :one
SELECT id, store_id, version, published_at, note FROM menu_versions
WHERE store_id = $1
ORDER BY version DESC
LIMIT 1
`

func (q *Queries) GetLatestVersion(ctx context.Context, storeID int64) (MenuVersion, error) {
	row := q.db.QueryRow(ctx, getLatestVersion, storeID)
	var i MenuVersion
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Version,
		&i.PublishedAt,
		&i.Note,
	)
	return i, err
}

const getVersionByNumber = `-- name: GetVersionByNumber :one
SELECT id, store_id, version, published_at, note FROM menu_versions
WHERE store_id = $1 AND version = $2
`

type GetVersionByNumberParams struct {
	StoreID int64 `json:"store_id"`
	Version int64 `json:"version"`
}

func (q *Queries) GetVersionByNumber(ctx context.Context, arg GetVersionByNumberParams) (MenuVersion, error) {
	row := q.db.QueryRow(ctx, getVersionByNumber, arg.StoreID, arg.Version)
	var i MenuVersion
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Version,
		&i.PublishedAt,
		&i.Note,
	)
	return i, err
}

const listVersionItems = `-- name: ListVersionItems :many
SELECT id, version_id, sku, name, base_price, display_order FROM menu_version_items
WHERE version_id = $1
ORDER BY display_order, id
`

func (q *Queries) ListVersionItems(ctx context.Context, versionID int64) ([]MenuVersionItem, error) {
	rows, err := q.db.Query(ctx, listVersionItems, versionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MenuVersionItem{}
	for rows.Next() {
		var i MenuVersionItem
		if err := rows.Scan(
			&i.ID,
			&i.VersionID,
			&i.Sku,
			&i.Name,
			&i.BasePrice,
			&i.DisplayOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVersions = `-- name: ListVersions :many
SELECT id, store_id, version, published_at, note FROM menu_versions
WHERE store_id = $1
ORDER BY version DESC
`

func (q *Queries) ListVersions(ctx context.Context, storeID int64) ([]MenuVersion, error) {
	rows, err := q.db.Query(ctx, listVersions, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MenuVersion{}
	for rows.Next() {
		var i MenuVersion
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.Version,
			&i.PublishedAt,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockStoreForPublish = `-- name: LockStoreForPublish :one
SELECT id, name, timezone, menu_version
FROM stores
WHERE id = $1
FOR UPDATE
`

type LockStoreForPublishRow struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	Timezone    string `json:"timezone"`
	MenuVersion int64  `json:"menu_version"`
}

func (q *Queries) LockStoreForPublish(ctx context.Context, id int64) (LockStoreForPublishRow, error) {
	row := q.db.QueryRow(ctx, lockStoreForPublish, id)
	var i LockStoreForPublishRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Timezone,
		&i.MenuVersion,
	)
	return i, err
}
