// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DailySale struct {
	ID       int64       `json:"id"`
	StoreID  int64       `json:"store_id"`
	SalesDay pgtype.Date `json:"sales_day"`
	Sku      string      `json:"sku"`
	Qty      int64       `json:"qty"`
}

type Dish struct {
	ID         int64              `json:"id"`
	StoreID    int64              `json:"store_id"`
	Sku        string             `json:"sku"`
	Name       string             `json:"name"`
	BasePrice  int64              `json:"base_price"`
	Active     bool               `json:"active"`
	DailyLimit pgtype.Int8        `json:"daily_limit"`
	SortOrder  int32              `json:"sort_order"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type MenuVersion struct {
	ID          int64              `json:"id"`
	StoreID     int64              `json:"store_id"`
	Version     int64              `json:"version"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	Note        string             `json:"note"`
}

type MenuVersionItem struct {
	ID           int64  `json:"id"`
	VersionID    int64  `json:"version_id"`
	Sku          string `json:"sku"`
	Name         string `json:"name"`
	BasePrice    int64  `json:"base_price"`
	DisplayOrder int32  `json:"display_order"`
}

type SalesEvent struct {
	ID         int64              `json:"id"`
	StoreID    int64              `json:"store_id"`
	EventID    string             `json:"event_id"`
	Sku        string             `json:"sku"`
	Qty        int32              `json:"qty"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	ReceivedAt pgtype.Timestamptz `json:"received_at"`
}

type Screen struct {
	ID            int64              `json:"id"`
	StoreID       int64              `json:"store_id"`
	Name          string             `json:"name"`
	TokenHash     string             `json:"token_hash"`
	LastHeartbeat pgtype.Timestamptz `json:"last_heartbeat"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type SoldOut struct {
	StoreID     int64              `json:"store_id"`
	Sku         string             `json:"sku"`
	SalesDay    pgtype.Date        `json:"sales_day"`
	TriggeredAt pgtype.Timestamptz `json:"triggered_at"`
}

type Store struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Timezone    string             `json:"timezone"`
	MenuVersion int64              `json:"menu_version"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type TemporaryPrice struct {
	ID        int64              `json:"id"`
	StoreID   int64              `json:"store_id"`
	VersionID int64              `json:"version_id"`
	Sku       string             `json:"sku"`
	Price     int64              `json:"price"`
	StartAt   pgtype.Timestamptz `json:"start_at"`
	EndAt     pgtype.Timestamptz `json:"end_at"`
}
