// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	BumpStoreVersion(ctx context.Context, arg BumpStoreVersionParams) error
	CopyVersionItems(ctx context.Context, arg []CopyVersionItemsParams) (int64, error)
	CountVersionItems(ctx context.Context, versionID int64) (int64, error)
	CreateDish(ctx context.Context, arg CreateDishParams) (Dish, error)
	CreateMenuVersion(ctx context.Context, arg CreateMenuVersionParams) (MenuVersion, error)
	CreateScreen(ctx context.Context, arg CreateScreenParams) (Screen, error)
	CreateStore(ctx context.Context, arg CreateStoreParams) (Store, error)
	DeactivateDishBySku(ctx context.Context, arg DeactivateDishBySkuParams) error
	DeleteDish(ctx context.Context, arg DeleteDishParams) error
	GetDailySales(ctx context.Context, arg GetDailySalesParams) ([]GetDailySalesRow, error)
	GetDish(ctx context.Context, arg GetDishParams) (Dish, error)
	GetDishLimit(ctx context.Context, arg GetDishLimitParams) (pgtype.Int8, error)
	GetLatestVersion(ctx context.Context, storeID int64) (MenuVersion, error)
	GetSalesEvent(ctx context.Context, arg GetSalesEventParams) (SalesEvent, error)
	GetScreen(ctx context.Context, arg GetScreenParams) (Screen, error)
	GetScreenByTokenHash(ctx context.Context, tokenHash string) (Screen, error)
	GetStore(ctx context.Context, id int64) (Store, error)
	GetStoreVersion(ctx context.Context, id int64) (int64, error)
	GetVersionByNumber(ctx context.Context, arg GetVersionByNumberParams) (MenuVersion, error)
	// The heartbeat instant is supplied by the application clock (nowFn) rather
	// than SQL now(), so liveness evaluation and the stored timestamp share one
	// clock (important under a pinned test clock).
	HeartbeatScreen(ctx context.Context, arg HeartbeatScreenParams) error
	// Atomic counter. ON CONFLICT takes a row lock on the target daily_sales row,
	// so concurrent events for the same (store, day, sku) serialize and no
	// increment is ever lost.
	IncrementDailySales(ctx context.Context, arg IncrementDailySalesParams) (DailySale, error)
	// Idempotent insert. A second submission of the same (store_id, event_id)
	// inserts nothing; the handler then compares the stored row to the payload to
	// tell a harmless duplicate from a conflicting re-use of the same ID.
	InsertSalesEvent(ctx context.Context, arg InsertSalesEventParams) (SalesEvent, error)
	InsertTemporaryPrice(ctx context.Context, arg InsertTemporaryPriceParams) error
	// Only active dishes are snapshotted into a publish.
	ListActiveDishesForPublish(ctx context.Context, storeID int64) ([]ListActiveDishesForPublishRow, error)
	// Temporary price in effect at a fixed instant. Windows are half-open and
	// non-overlapping, so at most one row matches per (version, sku).
	ListActiveTempPrices(ctx context.Context, arg ListActiveTempPricesParams) ([]ListActiveTempPricesRow, error)
	// Thresholds are catalog configuration; sold-out checks read the current
	// per-SKU limit independently of which menu version is live.
	ListDishLimits(ctx context.Context, storeID int64) ([]ListDishLimitsRow, error)
	ListDishes(ctx context.Context, storeID int64) ([]Dish, error)
	ListScreens(ctx context.Context, storeID int64) ([]Screen, error)
	ListSoldOutsForDay(ctx context.Context, arg ListSoldOutsForDayParams) ([]ListSoldOutsForDayRow, error)
	ListStores(ctx context.Context) ([]Store, error)
	ListTempPricesForVersion(ctx context.Context, versionID int64) ([]TemporaryPrice, error)
	ListVersionItems(ctx context.Context, versionID int64) ([]MenuVersionItem, error)
	ListVersions(ctx context.Context, storeID int64) ([]MenuVersion, error)
	LockStoreForPublish(ctx context.Context, id int64) (LockStoreForPublishRow, error)
	MarkSoldOut(ctx context.Context, arg MarkSoldOutParams) error
	UpdateDish(ctx context.Context, arg UpdateDishParams) (Dish, error)
	// Batch import upsert keyed on (store_id, sku). Used inside one transaction by
	// the import handler, which validates the whole batch first; any failure rolls
	// the entire import back (all-or-nothing, max 500 items).
	UpsertDish(ctx context.Context, arg UpsertDishParams) (Dish, error)
}

var _ Querier = (*Queries)(nil)
