// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: temp_prices.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertTemporaryPrice = `-- name: InsertTemporaryPrice :exec
INSERT INTO temporary_prices (store_id, version_id, sku, price, start_at, end_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertTemporaryPriceParams struct {
	StoreID   int64              `json:"store_id"`
	VersionID int64              `json:"version_id"`
	Sku       string             `json:"sku"`
	Price     int64              `json:"price"`
	StartAt   pgtype.Timestamptz `json:"start_at"`
	EndAt     pgtype.Timestamptz `json:"end_at"`
}

func (q *Queries) InsertTemporaryPrice(ctx context.Context, arg InsertTemporaryPriceParams) error {
	_, err := q.db.Exec(ctx, insertTemporaryPrice,
		arg.StoreID,
		arg.VersionID,
		arg.Sku,
		arg.Price,
		arg.StartAt,
		arg.EndAt,
	)
	return err
}

const listActiveTempPrices = `-- name: ListActiveTempPrices :many
SELECT id, version_id, sku, price, start_at, end_at
FROM temporary_prices
WHERE version_id = $1
  AND start_at <= $2
  AND end_at > $2
`

type ListActiveTempPricesParams struct {
	VersionID int64              `json:"version_id"`
	StartAt   pgtype.Timestamptz `json:"start_at"`
}

type ListActiveTempPricesRow struct {
	ID        int64              `json:"id"`
	VersionID int64              `json:"version_id"`
	Sku       string             `json:"sku"`
	Price     int64              `json:"price"`
	StartAt   pgtype.Timestamptz `json:"start_at"`
	EndAt     pgtype.Timestamptz `json:"end_at"`
}

// Temporary price in effect at a fixed instant. Windows are half-open and
// non-overlapping, so at most one row matches per (version, sku).
func (q *Queries) ListActiveTempPrices(ctx context.Context, arg ListActiveTempPricesParams) ([]ListActiveTempPricesRow, error) {
	rows, err := q.db.Query(ctx, listActiveTempPrices, arg.VersionID, arg.StartAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveTempPricesRow{}
	for rows.Next() {
		var i ListActiveTempPricesRow
		if err := rows.Scan(
			&i.ID,
			&i.VersionID,
			&i.Sku,
			&i.Price,
			&i.StartAt,
			&i.EndAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTempPricesForVersion = `-- name: ListTempPricesForVersion :many
SELECT id, store_id, version_id, sku, price, start_at, end_at FROM temporary_prices
WHERE version_id = $1
ORDER BY sku, start_at
`

func (q *Queries) ListTempPricesForVersion(ctx context.Context, versionID int64) ([]TemporaryPrice, error) {
	rows, err := q.db.Query(ctx, listTempPricesForVersion, versionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TemporaryPrice{}
	for rows.Next() {
		var i TemporaryPrice
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.VersionID,
			&i.Sku,
			&i.Price,
			&i.StartAt,
			&i.EndAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
