// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

import {Test} from "forge-std/Test.sol";
import {Vm} from "forge-std/Vm.sol";
import {ConstantProductPool} from "../src/ConstantProductPool.sol";
import {TestERC20} from "../src/test/TestERC20.sol";

/// @title ReferenceVectorsTest
/// @notice Replays every operation sequence generated by the independent
///         Python high-precision reference model (test/vectors/vectors.json)
///         against the deployed pool and asserts byte-for-byte identical
///         post-state after EVERY step:
///           - reserves equal the model's reserves AND the real balances
///           - total supply / every named account's balances + shares match
///           - expected return values on success, expected revert on failure
///         Because failed calls roll back, the post-state of a reverted
///         step must equal the pre-step state (the model leaves it untouched).
contract ReferenceVectorsTest is Test {
    // ---- JSON record shapes (field names match vectors.json) ----------
    // IMPORTANT: vm.parseJson abi-encodes objects with keys in ALPHABETICAL
    // order, so every struct below lists its fields in that exact order.
    // Fund: actor, amount0, amount1
    struct Fund {
        string actor;
        uint256 amount0;
        uint256 amount1;
    }

    // StepInput: actor, amount0Desired, amount1Desired, amountIn, deadline,
    //            minAmount0, minAmount1, minAmountOut, minShares, op, shares,
    //            to, tokenIn
    struct StepInput {
        string actor;
        uint256 amount0Desired;
        uint256 amount1Desired;
        uint256 amountIn;
        uint256 deadline;
        uint256 minAmount0;
        uint256 minAmount1;
        uint256 minAmountOut;
        uint256 minShares;
        string op;
        uint256 shares;
        string to;
        uint256 tokenIn;
    }

    // StepResult: amount0, amount1, amountIn, amountOut, shares
    struct StepResult {
        uint256 amount0;
        uint256 amount1;
        uint256 amountIn;
        uint256 amountOut;
        uint256 shares;
    }

    // AccountState: bal0, bal1, key, shares
    struct AccountState {
        uint256 bal0;
        uint256 bal1;
        string key;
        uint256 shares;
    }

    // State: accountList, lockedShares, reserve0, reserve1, totalShares
    struct State {
        AccountState[] accountList;
        uint256 lockedShares;
        uint256 reserve0;
        uint256 reserve1;
        uint256 totalShares;
    }

    // Record: ok, ret, revert, state, step, time
    struct Record {
        bool ok;
        StepResult ret;
        string revert;
        State state;
        StepInput step;
        uint256 time;
    }

    // Case: actors, finalState, funds, name, steps
    struct Case {
        string[] actors;
        State finalState;
        Fund[] funds;
        string name;
        Record[] steps;
    }

    ConstantProductPool internal pool;
    TestERC20 internal t0;
    TestERC20 internal t1;

    function _loadCases() internal view returns (Case[] memory cases) {
        string memory raw = vm.readFile("./test/vectors/vectors.json");
        bytes memory abiEncoded = vm.parseJson(raw, ".cases");
        cases = abi.decode(abiEncoded, (Case[]));
    }

    /// @notice Replay all generated state sequences; a failure names the
    ///         offending case and step via the revert message.
    function test_ReplayAllReferenceSequences() public {
        Case[] memory cases = _loadCases();
        for (uint256 i = 0; i < cases.length; i++) {
            _runCase(cases[i]);
        }
    }

    function test_VectorHashMatchesManifest() public view {
        // Guards stale/edited vectors: manifest records the generator's
        // sha256 of vectors.json, recomputed here via the SHA-256 precompile.
        string memory manifestJson = vm.readFile("./test/vectors/manifest.json");
        bytes32 expected = vm.parseJsonBytes32(manifestJson, ".vectorSha256");
        string memory raw = vm.readFile("./test/vectors/vectors.json");
        assertEq(_sha256(bytes(raw)), expected, "vectors.json sha256 mismatch");
        assertTrue(expected != bytes32(0));
    }

    // ==================================================================
    function _runCase(Case memory c) internal {
        t0 = new TestERC20("Token0", "T0");
        t1 = new TestERC20("Token1", "T1");
        pool = new ConstantProductPool(address(t0), address(t1));

        for (uint256 i = 0; i < c.funds.length; i++) {
            Fund memory f = c.funds[i];
            address who = _addr(f.actor);
            if (f.amount0 != 0) t0.mint(who, f.amount0);
            if (f.amount1 != 0) t1.mint(who, f.amount1);
            vm.prank(who);
            t0.approve(address(pool), type(uint256).max);
            vm.prank(who);
            t1.approve(address(pool), type(uint256).max);
        }

        for (uint256 i = 0; i < c.steps.length; i++) {
            _runRecord(c, c.steps[i]);
        }
        _assertState(c.finalState);
    }

    function _runRecord(Case memory c, Record memory rec) internal {
        StepInput memory s = rec.step;
        address actor = _addr(s.actor);
        address to = _addr(s.to);
        vm.warp(rec.time);

        bytes memory payload = _encodeCall(s, to);
        vm.prank(actor);
        (bool success, bytes memory returndata) = address(pool).call(payload);

        if (rec.ok) {
            assertTrue(success, _fail(c.name, rec, "expected success"));
            if (_eq(s.op, "addLiquidity")) {
                (uint256 a0, uint256 a1, uint256 sh) = abi.decode(returndata, (uint256, uint256, uint256));
                assertEq(a0, rec.ret.amount0, _fail(c.name, rec, "amount0"));
                assertEq(a1, rec.ret.amount1, _fail(c.name, rec, "amount1"));
                assertEq(sh, rec.ret.shares, _fail(c.name, rec, "shares"));
            } else if (_eq(s.op, "removeLiquidity")) {
                (uint256 a0, uint256 a1) = abi.decode(returndata, (uint256, uint256));
                assertEq(a0, rec.ret.amount0, _fail(c.name, rec, "rm amount0"));
                assertEq(a1, rec.ret.amount1, _fail(c.name, rec, "rm amount1"));
            } else if (_eq(s.op, "swap")) {
                uint256 out = abi.decode(returndata, (uint256));
                assertEq(out, rec.ret.amountOut, _fail(c.name, rec, "amountOut"));
            } else {
                revert(_fail(c.name, rec, "unknown op"));
            }
        } else {
            assertFalse(success, _fail(c.name, rec, "expected revert"));
            bytes4 sel = _revertSelector(rec.revert);
            assertEq(_selectorOf(returndata), sel, _fail(c.name, rec, string.concat("revert selector: ", rec.revert)));
        }

        // After EVERY step (success or revert) state matches the model
        // exactly; reverted calls left no trace on either side.
        _assertState(rec.state);
    }

    function _encodeCall(StepInput memory s, address to) private view returns (bytes memory) {
        if (_eq(s.op, "addLiquidity")) {
            return abi.encodeCall(
                ConstantProductPool.addLiquidity, (s.amount0Desired, s.amount1Desired, s.minShares, to, s.deadline)
            );
        }
        if (_eq(s.op, "removeLiquidity")) {
            return
                abi.encodeCall(
                    ConstantProductPool.removeLiquidity, (s.shares, s.minAmount0, s.minAmount1, to, s.deadline)
                );
        }
        // swap: model tokenIn 0/1 -> real token; anything else -> a bogus
        // address that must produce InvalidTokenIn.
        address tin = s.tokenIn == 0 ? address(t0) : (s.tokenIn == 1 ? address(t1) : address(0xBADBAD));
        return abi.encodeCall(ConstantProductPool.swapExactInput, (tin, s.amountIn, s.minAmountOut, to, s.deadline));
    }

    // ==================================================================
    function _assertState(State memory want) internal view {
        (uint112 r0, uint112 r1, uint256 ts) = pool.getReserves();
        assertEq(uint256(r0), want.reserve0, "reserve0");
        assertEq(uint256(r1), want.reserve1, "reserve1");
        assertEq(ts, want.totalShares, "totalShares");

        // Core on-chain-only invariant: reserves equal real token balances.
        assertEq(t0.balanceOf(address(pool)), want.reserve0, "balance0==reserve0");
        assertEq(t1.balanceOf(address(pool)), want.reserve1, "balance1==reserve1");
        // Locked shares are held by address(0): never mintable/burnable.
        assertEq(pool.balanceOf(address(0)), want.lockedShares, "locked shares");

        for (uint256 i = 0; i < want.accountList.length; i++) {
            AccountState memory a = want.accountList[i];
            if (_eq(a.key, "LOCK")) continue; // checked above
            address who = _addr(a.key);
            assertEq(t0.balanceOf(who), a.bal0, string.concat(a.key, " bal0"));
            assertEq(t1.balanceOf(who), a.bal1, string.concat(a.key, " bal1"));
            assertEq(pool.balanceOf(who), a.shares, string.concat(a.key, " shares"));
        }
    }

    // ==================================================================
    // revert-name -> selector. Names come from RefError in the Python model.
    // ==================================================================
    function _revertSelector(string memory name) private pure returns (bytes4) {
        if (_eq(name, "Expired")) return ConstantProductPool.Expired.selector;
        if (_eq(name, "ZeroAmount")) return ConstantProductPool.ZeroAmount.selector;
        if (_eq(name, "ZeroOutput")) return ConstantProductPool.ZeroOutput.selector;
        if (_eq(name, "ZeroRecipient")) return ConstantProductPool.ZeroRecipient.selector;
        if (_eq(name, "NoLiquidityMinted")) return ConstantProductPool.NoLiquidityMinted.selector;
        if (_eq(name, "InsufficientShares")) return ConstantProductPool.InsufficientShares.selector;
        if (_eq(name, "SlippageShares")) return ConstantProductPool.SlippageShares.selector;
        if (_eq(name, "SlippageToken")) return ConstantProductPool.SlippageToken.selector;
        if (_eq(name, "InvalidTokenIn")) return ConstantProductPool.InvalidTokenIn.selector;
        if (_eq(name, "MinOutputNotMet")) return ConstantProductPool.MinOutputNotMet.selector;
        if (_eq(name, "TransferFailed")) return ConstantProductPool.TransferFailed.selector;
        revert(string.concat("unknown expected revert: ", name));
    }

    function _selectorOf(bytes memory data) private pure returns (bytes4 sel) {
        if (data.length >= 4) {
            assembly {
                sel := mload(add(data, 32))
            }
        }
    }

    function _sha256(bytes memory data) private view returns (bytes32 result) {
        (bool ok, bytes memory out) = address(0x02).staticcall(data);
        require(ok && out.length == 32, "sha256 precompile failed");
        return abi.decode(out, (bytes32));
    }

    function _addr(string memory actor) private pure returns (address) {
        // Deterministic addresses matching the model's ACTOR_ADDR table.
        if (_eq(actor, "alice")) return 0xa11ce00000000000000000000000000000000001;
        if (_eq(actor, "bob")) return 0xb0b0000000000000000000000000000000000002;
        if (_eq(actor, "carol")) return 0xC0A0000000000000000000000000000000000003;
        if (_eq(actor, "dave")) return 0xDa7e000000000000000000000000000000000004;
        if (_eq(actor, "LP")) return 0x1000000000000000000000000000000000000001;
        if (_eq(actor, "SWAP")) return 0x2000000000000000000000000000000000000002;
        revert("unknown actor");
    }

    function _eq(string memory a, string memory b) private pure returns (bool) {
        return keccak256(bytes(a)) == keccak256(bytes(b));
    }

    function _fail(string memory caseName, Record memory rec, string memory what) private pure returns (string memory) {
        return
            string.concat("[", caseName, "] t=", _u(rec.time), " ", rec.step.op, " expected=[", rec.revert, "]: ", what);
    }

    function _u(uint256 x) private pure returns (string memory) {
        if (x == 0) return "0";
        uint256 j = x;
        uint256 len;
        while (j != 0) {
            len++;
            j /= 10;
        }
        bytes memory b = new bytes(len);
        while (len != 0) {
            len--;
            b[len] = bytes1(uint8(48 + (x % 10)));
            x /= 10;
        }
        return string(b);
    }
}
