// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

import {Test} from "forge-std/Test.sol";
import {stdJson} from "forge-std/StdJson.sol";
import {CPMMFactory} from "../src/CPMMFactory.sol";
import {CPMMPair} from "../src/CPMMPair.sol";
import {TestERC20} from "../src/mocks/TestERC20.sol";

/// @notice Replays every scenario generated by reference/scenarios.py against
///         the live contracts and asserts state after each step matches the
///         independent Python model exactly (reserves == real balances,
///         supplies, per-user holdings). Steps marked expectRevert must fail
///         atomically and leave no state change after a cleanup skim.
contract SequenceTest is Test {
    using stdJson for string;

    CPMMFactory internal factory;
    CPMMPair internal pair;
    TestERC20 internal t0;
    TestERC20 internal t1;

    address internal alice = address(0xA11CE);
    address internal bob = address(0xB0B);

    string internal root;
    string internal raw;

    function setUp() public {
        root = vm.projectRoot();
        raw = vm.readFile(string.concat(root, "/reference/fixtures/scenarios.json"));
    }

    function test_AllScenarios() public {
        uint256 n = raw.readUint(".scenarioCount");
        for (uint256 s; s < n; ++s) {
            _runScenario(s);
        }
    }

    function _runScenario(uint256 idx) internal {
        // Fresh contracts per scenario. Deploy both, then orient t0/t1 by
        // the pair's own ordering — CREATE addresses are keccak-derived, so
        // deployment order does NOT imply numeric address order.
        factory = new CPMMFactory();
        TestERC20 x = new TestERC20("Token0", "TK0");
        TestERC20 y = new TestERC20("Token1", "TK1");
        pair = CPMMPair(factory.createPair(address(x), address(y)));
        if (address(x) < address(y)) {
            t0 = x;
            t1 = y;
        } else {
            t0 = y;
            t1 = x;
        }
        assertEq(address(pair.token0()), address(t0), "t0 must equal pair.token0()");

        string memory base = string.concat(".scenarios[", vm.toString(idx), "]");
        uint256 steps = raw.readUint(string.concat(base, ".stepCount"));
        for (uint256 i; i < steps; ++i) {
            _runStep(string.concat(base, ".steps[", vm.toString(i), "]"));
        }
    }

    function _runStep(string memory p) internal {
        string memory op = _str(p, ".op");

        if (_eq(op, "fund")) {
            t0.mint(alice, _u(p, ".amount0"));
            t1.mint(alice, _u(p, ".amount1"));
            t0.mint(bob, _u(p, ".bob0"));
            t1.mint(bob, _u(p, ".bob1"));
            _assertState(p);
        } else if (_eq(op, "deposit")) {
            address who = _who(_str(p, ".user"));
            uint256 a0 = _u(p, ".amount0");
            uint256 a1 = _u(p, ".amount1");
            if (_hasStr(p, ".expectRevert")) {
                _doDepositExpectRevert(who, a0, a1);
                return;
            }
            _deposit(who, a0, a1);
            assertEq(pair.balanceOf(who), _u(p, ".liquidity"), "lp shares");
            _assertState(p);
        } else if (_eq(op, "swap")) {
            address who = _who(_str(p, ".user"));
            string memory tin = _str(p, ".tokenIn");
            uint256 ain = _u(p, ".amountIn");
            (uint112 r0, uint112 r1,) = pair.getReserves();
            uint256 predicted = _eq(tin, "token0") ? _getOut(ain, r0, r1) : _getOut(ain, r1, r0);
            if (_hasStr(p, ".expectRevert")) {
                assertEq(predicted, 0, "fixture expects zero-output revert");
                _doSwapExpectRevert(who, tin, ain);
                return;
            }
            uint256 out = _swap(who, tin, ain);
            assertEq(out, _u(p, ".amountOut"), "evm amountOut");
            _assertState(p);
        } else if (_eq(op, "burn")) {
            address who = _who(_str(p, ".user"));
            uint256 liq = _u(p, ".liquidity");
            (uint256 got0, uint256 got1) = _burn(who, liq);
            assertEq(got0, _u(p, ".amount0"), "burn amount0");
            assertEq(got1, _u(p, ".amount1"), "burn amount1");
            _assertState(p);
        } else if (_eq(op, "feeBound")) {
            (uint112 r0, uint112 r1,) = pair.getReserves();
            uint256 ain = _u(p, ".amountIn");
            uint256 withFee = _getOut(ain, r0, r1);
            uint256 zeroFee = (ain * uint256(r1)) / (uint256(r0) + ain);
            assertEq(withFee, _u(p, ".withFeeOut"), "withFee");
            assertEq(zeroFee, _u(p, ".zeroFeeOut"), "zeroFee");
            assertLe(withFee, zeroFee, "fee must reduce output");
        } else {
            revert("unknown op");
        }
    }

    // ------------------------------------------------------------------
    // On-chain actions
    // ------------------------------------------------------------------

    function _deposit(address who, uint256 a0, uint256 a1) internal {
        vm.startPrank(who);
        t0.transfer(address(pair), a0);
        t1.transfer(address(pair), a1);
        pair.mint(who, a0, a1);
        vm.stopPrank();
    }

    function _doDepositExpectRevert(address who, uint256 a0, uint256 a1) internal {
        bytes memory snap = _liveState();
        vm.startPrank(who);
        t0.transfer(address(pair), a0);
        t1.transfer(address(pair), a1);
        (bool ok,) = address(pair).call(abi.encodeCall(CPMMPair.mint, (who, a0, a1)));
        vm.stopPrank();
        assertFalse(ok, "deposit must revert");
        // mint reverted atomically; tokens remain as a donation. Skim them
        // back to the depositor so the next step starts from model state.
        vm.prank(address(0xDEAD));
        pair.skim(who);
        assertEq(_liveState(), snap, "revert step changed state");
    }

    function _swap(address who, string memory tin, uint256 ain) internal returns (uint256 out) {
        (uint112 r0, uint112 r1,) = pair.getReserves();
        if (_eq(tin, "token0")) {
            out = _getOut(ain, r0, r1);
            vm.startPrank(who);
            t0.transfer(address(pair), ain);
            pair.swap(0, out, who, ain, 0, "");
            vm.stopPrank();
        } else {
            out = _getOut(ain, r1, r0);
            vm.startPrank(who);
            t1.transfer(address(pair), ain);
            pair.swap(out, 0, who, 0, ain, "");
            vm.stopPrank();
        }
    }

    function _doSwapExpectRevert(address who, string memory tin, uint256 ain) internal {
        bytes memory snap = _liveState();
        vm.startPrank(who);
        if (_eq(tin, "token0")) {
            t0.transfer(address(pair), ain);
            (bool ok,) = address(pair).call(abi.encodeCall(CPMMPair.swap, (uint256(0), uint256(0), who, ain, 0, "")));
            assertFalse(ok, "zero-out swap must revert");
        } else {
            t1.transfer(address(pair), ain);
            (bool ok,) = address(pair).call(abi.encodeCall(CPMMPair.swap, (uint256(0), uint256(0), who, 0, ain, "")));
            assertFalse(ok, "zero-out swap must revert");
        }
        vm.stopPrank();
        vm.prank(address(0xDEAD));
        pair.skim(who);
        assertEq(_liveState(), snap, "revert swap changed state");
    }

    function _burn(address who, uint256 liq) internal returns (uint256 got0, uint256 got1) {
        uint256 before0 = t0.balanceOf(who);
        uint256 before1 = t1.balanceOf(who);
        vm.startPrank(who);
        pair.transfer(address(pair), liq);
        pair.burn(who);
        vm.stopPrank();
        got0 = t0.balanceOf(who) - before0;
        got1 = t1.balanceOf(who) - before1;
    }

    // ------------------------------------------------------------------
    // State assertions
    // ------------------------------------------------------------------

    function _assertState(string memory p) internal view {
        string memory sp = string.concat(p, ".state");
        (uint112 r0, uint112 r1,) = pair.getReserves();
        assertEq(uint256(r0), _u(sp, ".reserve0"), "reserve0");
        assertEq(uint256(r1), _u(sp, ".reserve1"), "reserve1");
        assertEq(t0.balanceOf(address(pair)), uint256(r0), "bal0==reserve0");
        assertEq(t1.balanceOf(address(pair)), uint256(r1), "bal1==reserve1");
        assertEq(pair.totalSupply(), _u(sp, ".totalSupply"), "totalSupply");
        assertEq(pair.balanceOf(address(0)), _u(sp, ".lockLp"), "locked lp");

        string[2] memory names = ["alice", "bob"];
        address[2] memory who = [alice, bob];
        for (uint256 i; i < 2; ++i) {
            string memory up = string.concat(sp, ".users.", names[i]);
            assertEq(t0.balanceOf(who[i]), _u(up, ".token0"), string.concat(names[i], ".token0"));
            assertEq(t1.balanceOf(who[i]), _u(up, ".token1"), string.concat(names[i], ".token1"));
            assertEq(pair.balanceOf(who[i]), _u(up, ".lp"), string.concat(names[i], ".lp"));
        }
    }

    function _liveState() internal view returns (bytes memory) {
        (uint112 r0, uint112 r1,) = pair.getReserves();
        return abi.encode(
            r0,
            r1,
            pair.totalSupply(),
            t0.balanceOf(address(pair)),
            t1.balanceOf(address(pair)),
            t0.balanceOf(alice),
            t1.balanceOf(alice),
            pair.balanceOf(alice),
            t0.balanceOf(bob),
            t1.balanceOf(bob),
            pair.balanceOf(bob)
        );
    }

    // ------------------------------------------------------------------
    // JSON + misc helpers
    // ------------------------------------------------------------------

    function _u(string memory p, string memory key) internal view returns (uint256) {
        return raw.readUint(string.concat(p, key));
    }

    function _str(string memory p, string memory key) internal view returns (string memory) {
        return raw.readString(string.concat(p, key));
    }

    function _hasStr(string memory p, string memory key) internal view returns (bool) {
        try this.__readString(string.concat(p, key)) returns (string memory) {
            return true;
        } catch {
            return false;
        }
    }

    function __readString(string memory full) external view returns (string memory) {
        return raw.readString(full);
    }

    function _eq(string memory a, string memory b) internal pure returns (bool) {
        return keccak256(bytes(a)) == keccak256(bytes(b));
    }

    function _who(string memory s) internal pure returns (address) {
        if (keccak256(bytes(s)) == keccak256("alice")) return address(0xA11CE);
        if (keccak256(bytes(s)) == keccak256("bob")) return address(0xB0B);
        revert("unknown user");
    }

    function _getOut(uint256 ain, uint256 rin, uint256 rout) internal pure returns (uint256) {
        if (ain == 0 || rin == 0 || rout == 0) return 0;
        uint256 withFee = ain * 997;
        return (withFee * rout) / (rin * 1000 + withFee);
    }
}
