# Generated by Django 4.2.16 on 2026-09-21 18:49

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterfallVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=16)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_waterfall_versions', to=settings.AUTH_USER_MODEL)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='applications.placement')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_waterfall_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['placement_id', '-version_number'],
            },
        ),
        migrations.CreateModel(
            name='WaterfallEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField()),
                ('fallback_order', models.PositiveSmallIntegerField()),
                ('floor_cpm', models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='Minimum acceptable CPM for this network in this slot.', max_digits=14)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applications.adnetwork')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='waterfall.waterfallversion')),
            ],
            options={
                'ordering': ['version_id', 'fallback_order'],
            },
        ),
        migrations.CreateModel(
            name='CurrentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('placement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_pointer', to='applications.placement')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_pointers', to='waterfall.waterfallversion')),
            ],
        ),
        migrations.AddIndex(
            model_name='waterfallversion',
            index=models.Index(fields=['placement', 'status'], name='waterfall_w_placeme_f8c59d_idx'),
        ),
        migrations.AddConstraint(
            model_name='waterfallversion',
            constraint=models.UniqueConstraint(fields=('placement', 'version_number'), name='uniq_version_number_per_placement'),
        ),
        migrations.AddConstraint(
            model_name='waterfallentry',
            constraint=models.UniqueConstraint(fields=('version', 'network'), name='uniq_network_per_version'),
        ),
        migrations.AddConstraint(
            model_name='waterfallentry',
            constraint=models.UniqueConstraint(fields=('version', 'priority'), name='uniq_priority_per_version'),
        ),
        migrations.AddConstraint(
            model_name='waterfallentry',
            constraint=models.UniqueConstraint(fields=('version', 'fallback_order'), name='uniq_fallback_per_version'),
        ),
    ]
