# Generated by Django 4.2.16 on 2026-09-21 18:49

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('experiments', '0001_initial'),
        ('waterfall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=64)),
                ('event_type', models.CharField(choices=[('impression', 'Impression'), ('fill', 'Fill'), ('revenue', 'Revenue'), ('failure', 'Failure')], max_length=16)),
                ('variant', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B')], max_length=1, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=6, default=Decimal('0'), help_text='Revenue amount (USD, 6-dp).', max_digits=14, null=True)),
                ('failure_reason', models.CharField(blank=True, choices=[('no_fill', 'No fill'), ('timeout', 'Timeout'), ('error', 'Error'), ('other', 'Other')], max_length=16, null=True)),
                ('user_key_hash', models.CharField(blank=True, help_text='SHA-256 of the SDK user key; raw keys are never stored.', max_length=64, null=True)),
                ('occurred_at', models.DateTimeField(help_text='Client timestamp of when the event happened.')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='applications.app')),
                ('experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='experiments.experiment')),
                ('network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='applications.adnetwork')),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='applications.placement')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='waterfall.waterfallversion')),
            ],
            options={
                'indexes': [models.Index(fields=['placement', 'network', 'occurred_at'], name='events_even_placeme_5b241b_idx'), models.Index(fields=['experiment', 'variant'], name='events_even_experim_587753_idx'), models.Index(fields=['occurred_at'], name='events_even_occurre_1eb0a1_idx'), models.Index(fields=['app', 'occurred_at'], name='events_even_app_id_65697c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('app', 'event_id'), name='uniq_event_id_per_app'),
        ),
    ]
