# Generated by Django 4.2.16 on 2026-09-21 18:49

import applications.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('bundle_id', models.CharField(help_text='Platform bundle / package identifier, e.g. com.acme.game', max_length=255)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], max_length=16)),
                ('api_key', models.CharField(default=applications.models._new_api_key, editable=False, help_text="SDK authentication key (sent as 'Authorization: ApiKey <key>').", max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('placement_key', models.SlugField(help_text='Stable key used by the SDK to fetch config.', max_length=128)),
                ('ad_type', models.CharField(choices=[('banner', 'Banner'), ('interstitial', 'Interstitial'), ('rewarded', 'Rewarded video'), ('native', 'Native')], default='rewarded', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='applications.app')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('code', models.SlugField(help_text="Stable machine code, e.g. 'adcolony'.", max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_networks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='placement',
            constraint=models.UniqueConstraint(fields=('app', 'placement_key'), name='uniq_placement_key_per_app'),
        ),
        migrations.AddConstraint(
            model_name='app',
            constraint=models.UniqueConstraint(fields=('developer', 'bundle_id'), name='uniq_app_bundle_per_developer'),
        ),
        migrations.AddConstraint(
            model_name='adnetwork',
            constraint=models.UniqueConstraint(fields=('developer', 'code'), name='uniq_network_code_per_developer'),
        ),
    ]
