# Generated by Django 5.0.14 on 2026-09-21 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], default='running', max_length=16)),
                ('is_active', models.BooleanField(default=False)),
                ('checksum', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='NetworkScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('fills', models.PositiveIntegerField(default=0)),
                ('failures', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('fill_rate', models.DecimalField(decimal_places=6, max_digits=8, null=True)),
                ('ecpm', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('reliability', models.DecimalField(decimal_places=6, max_digits=8, null=True)),
                ('fill_rate_norm', models.DecimalField(decimal_places=6, max_digits=8, null=True)),
                ('ecpm_norm', models.DecimalField(decimal_places=6, max_digits=8, null=True)),
                ('reliability_norm', models.DecimalField(decimal_places=6, max_digits=8, null=True)),
                ('score', models.DecimalField(decimal_places=6, default=0, max_digits=8)),
                ('rank', models.PositiveSmallIntegerField(default=0)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='network_scores', to='catalog.adnetwork')),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_scores', to='catalog.placement')),
            ],
            options={
                'ordering': ['run_id', 'placement_id', 'rank'],
            },
        ),
        migrations.AddConstraint(
            model_name='scorerun',
            constraint=models.UniqueConstraint(fields=('period_start',), name='uniq_scoring_period'),
        ),
        migrations.AddField(
            model_name='networkscore',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_scores', to='scoring.scorerun'),
        ),
        migrations.AddIndex(
            model_name='networkscore',
            index=models.Index(fields=['placement', 'run'], name='ix_score_placement_run'),
        ),
        migrations.AddConstraint(
            model_name='networkscore',
            constraint=models.UniqueConstraint(fields=('run', 'placement', 'network'), name='uniq_score_run_placement_network'),
        ),
    ]
