// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: membership.sql

package database

import (
	"context"
)

const cancelSubscription = `-- name: CancelSubscription :exec
UPDATE subscriptions SET status = 'cancelled'
WHERE community_id = $1 AND user_id = $2 AND status = 'active'
`

type CancelSubscriptionParams struct {
	CommunityID int64 `json:"community_id"`
	UserID      int64 `json:"user_id"`
}

// Immediate loss of access: status flips to cancelled; access checks require
// status='active', so the change takes effect at once.
func (q *Queries) CancelSubscription(ctx context.Context, arg CancelSubscriptionParams) error {
	_, err := q.db.Exec(ctx, cancelSubscription, arg.CommunityID, arg.UserID)
	return err
}

const countTiers = `-- name: CountTiers :one
SELECT count(*) FROM tiers WHERE community_id = $1
`

func (q *Queries) CountTiers(ctx context.Context, communityID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countTiers, communityID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (community_id, request_id, user_id, tier_id, amount_cents, days)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, community_id, request_id, user_id, tier_id, amount_cents, days, created_at
`

type CreatePaymentParams struct {
	CommunityID int64  `json:"community_id"`
	RequestID   string `json:"request_id"`
	UserID      int64  `json:"user_id"`
	TierID      int64  `json:"tier_id"`
	AmountCents int64  `json:"amount_cents"`
	Days        int32  `json:"days"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.CommunityID,
		arg.RequestID,
		arg.UserID,
		arg.TierID,
		arg.AmountCents,
		arg.Days,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.CommunityID,
		&i.RequestID,
		&i.UserID,
		&i.TierID,
		&i.AmountCents,
		&i.Days,
		&i.CreatedAt,
	)
	return i, err
}

const createTier = `-- name: CreateTier :one
INSERT INTO tiers (community_id, level, name, price_cents, duration_days)
VALUES ($1, $2, $3, $4, $5) RETURNING id, community_id, level, name, price_cents, duration_days, is_active, created_at
`

type CreateTierParams struct {
	CommunityID  int64  `json:"community_id"`
	Level        int32  `json:"level"`
	Name         string `json:"name"`
	PriceCents   int64  `json:"price_cents"`
	DurationDays int32  `json:"duration_days"`
}

func (q *Queries) CreateTier(ctx context.Context, arg CreateTierParams) (Tier, error) {
	row := q.db.QueryRow(ctx, createTier,
		arg.CommunityID,
		arg.Level,
		arg.Name,
		arg.PriceCents,
		arg.DurationDays,
	)
	var i Tier
	err := row.Scan(
		&i.ID,
		&i.CommunityID,
		&i.Level,
		&i.Name,
		&i.PriceCents,
		&i.DurationDays,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getEffectiveLevel = `-- name: GetEffectiveLevel :one
SELECT t.level
FROM subscriptions s
JOIN tiers t ON t.id = s.tier_id
WHERE s.community_id = $1 AND s.user_id = $2
  AND s.status = 'active' AND s.period_end > now()
  AND t.is_active = TRUE
FOR SHARE OF s
`

type GetEffectiveLevelParams struct {
	CommunityID int64 `json:"community_id"`
	UserID      int64 `json:"user_id"`
}

// Returns the member's effective tier level, or sqlc.ErrNoRows when there is no
// active, unexpired subscription. Single locking read so renewal and access
// checks serialize on the subscription row.
func (q *Queries) GetEffectiveLevel(ctx context.Context, arg GetEffectiveLevelParams) (int32, error) {
	row := q.db.QueryRow(ctx, getEffectiveLevel, arg.CommunityID, arg.UserID)
	var level int32
	err := row.Scan(&level)
	return level, err
}

const getPaymentByRequest = `-- name: GetPaymentByRequest :one
SELECT id, community_id, request_id, user_id, tier_id, amount_cents, days, created_at FROM payments WHERE community_id = $1 AND request_id = $2
`

type GetPaymentByRequestParams struct {
	CommunityID int64  `json:"community_id"`
	RequestID   string `json:"request_id"`
}

// Idempotency lookup for payment registration.
func (q *Queries) GetPaymentByRequest(ctx context.Context, arg GetPaymentByRequestParams) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByRequest, arg.CommunityID, arg.RequestID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.CommunityID,
		&i.RequestID,
		&i.UserID,
		&i.TierID,
		&i.AmountCents,
		&i.Days,
		&i.CreatedAt,
	)
	return i, err
}

const getSubscription = `-- name: GetSubscription :one
SELECT id, community_id, user_id, tier_id, status, period_end, created_at, updated_at FROM subscriptions
WHERE community_id = $1 AND user_id = $2
`

type GetSubscriptionParams struct {
	CommunityID int64 `json:"community_id"`
	UserID      int64 `json:"user_id"`
}

func (q *Queries) GetSubscription(ctx context.Context, arg GetSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscription, arg.CommunityID, arg.UserID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.CommunityID,
		&i.UserID,
		&i.TierID,
		&i.Status,
		&i.PeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTier = `-- name: GetTier :one
SELECT id, community_id, level, name, price_cents, duration_days, is_active, created_at FROM tiers WHERE id = $1 AND community_id = $2
`

type GetTierParams struct {
	ID          int64 `json:"id"`
	CommunityID int64 `json:"community_id"`
}

func (q *Queries) GetTier(ctx context.Context, arg GetTierParams) (Tier, error) {
	row := q.db.QueryRow(ctx, getTier, arg.ID, arg.CommunityID)
	var i Tier
	err := row.Scan(
		&i.ID,
		&i.CommunityID,
		&i.Level,
		&i.Name,
		&i.PriceCents,
		&i.DurationDays,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listTiers = `-- name: ListTiers :many
SELECT id, community_id, level, name, price_cents, duration_days, is_active, created_at FROM tiers WHERE community_id = $1 ORDER BY level
`

func (q *Queries) ListTiers(ctx context.Context, communityID int64) ([]Tier, error) {
	rows, err := q.db.Query(ctx, listTiers, communityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tier{}
	for rows.Next() {
		var i Tier
		if err := rows.Scan(
			&i.ID,
			&i.CommunityID,
			&i.Level,
			&i.Name,
			&i.PriceCents,
			&i.DurationDays,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTierActive = `-- name: SetTierActive :exec
UPDATE tiers SET is_active = $3 WHERE id = $1 AND community_id = $2
`

type SetTierActiveParams struct {
	ID          int64 `json:"id"`
	CommunityID int64 `json:"community_id"`
	IsActive    bool  `json:"is_active"`
}

func (q *Queries) SetTierActive(ctx context.Context, arg SetTierActiveParams) error {
	_, err := q.db.Exec(ctx, setTierActive, arg.ID, arg.CommunityID, arg.IsActive)
	return err
}

const upsertSubscription = `-- name: UpsertSubscription :one
INSERT INTO subscriptions (community_id, user_id, tier_id, status, period_end)
VALUES ($1, $2, $3, 'active', now() + make_interval(days => $4))
ON CONFLICT (community_id, user_id) DO UPDATE
SET tier_id    = EXCLUDED.tier_id,
    status     = 'active',
    period_end = GREATEST(subscriptions.period_end, now())
                 + make_interval(days => $4)
RETURNING id, community_id, user_id, tier_id, status, period_end, created_at, updated_at
`

type UpsertSubscriptionParams struct {
	CommunityID int64 `json:"community_id"`
	UserID      int64 `json:"user_id"`
	TierID      int64 `json:"tier_id"`
	Days        int32 `json:"days"`
}

// Single-statement insert-or-renew. On the unique (community_id,user_id)
// conflict PostgreSQL takes a row lock and re-evaluates the DO UPDATE against
// the winner's committed row, so two first-time payments that race serialize
// into one insert plus one renewal instead of a duplicate key error.
func (q *Queries) UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, upsertSubscription,
		arg.CommunityID,
		arg.UserID,
		arg.TierID,
		arg.Days,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.CommunityID,
		&i.UserID,
		&i.TierID,
		&i.Status,
		&i.PeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
