// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Attachment struct {
	ID          int64     `json:"id"`
	CommunityID int64     `json:"community_id"`
	VersionID   int64     `json:"version_id"`
	Filename    string    `json:"filename"`
	ContentType string    `json:"content_type"`
	Data        []byte    `json:"data"`
	CreatedAt   time.Time `json:"created_at"`
}

type Community struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type Content struct {
	ID                 int64       `json:"id"`
	CommunityID        int64       `json:"community_id"`
	AuthorID           int64       `json:"author_id"`
	Title              string      `json:"title"`
	Status             string      `json:"status"`
	CurrentVersionID   pgtype.Int8 `json:"current_version_id"`
	PublishedVersionID pgtype.Int8 `json:"published_version_id"`
	RequiredLevel      int32       `json:"required_level"`
	CreatedAt          time.Time   `json:"created_at"`
	UpdatedAt          time.Time   `json:"updated_at"`
}

type ContentEvent struct {
	ID          int64       `json:"id"`
	CommunityID int64       `json:"community_id"`
	ContentID   int64       `json:"content_id"`
	VersionID   pgtype.Int8 `json:"version_id"`
	ActorID     int64       `json:"actor_id"`
	Action      string      `json:"action"`
	Reason      string      `json:"reason"`
	CreatedAt   time.Time   `json:"created_at"`
}

type ContentVersion struct {
	ID           int64     `json:"id"`
	ContentID    int64     `json:"content_id"`
	CommunityID  int64     `json:"community_id"`
	VersionNo    int32     `json:"version_no"`
	Body         string    `json:"body"`
	ReviewStatus string    `json:"review_status"`
	CreatedBy    int64     `json:"created_by"`
	CreatedAt    time.Time `json:"created_at"`
}

type Course struct {
	ID            int64              `json:"id"`
	CommunityID   int64              `json:"community_id"`
	AuthorID      int64              `json:"author_id"`
	Title         string             `json:"title"`
	RequiredLevel int32              `json:"required_level"`
	Published     bool               `json:"published"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
}

type CourseLesson struct {
	ID               int64       `json:"id"`
	ModuleID         int64       `json:"module_id"`
	Position         int32       `json:"position"`
	Title            string      `json:"title"`
	ContentVersionID pgtype.Int8 `json:"content_version_id"`
}

type CourseModule struct {
	ID       int64  `json:"id"`
	CourseID int64  `json:"course_id"`
	Position int32  `json:"position"`
	Title    string `json:"title"`
}

type CoursePublish struct {
	ID          int64     `json:"id"`
	CourseID    int64     `json:"course_id"`
	CommunityID int64     `json:"community_id"`
	PublishedBy int64     `json:"published_by"`
	PublishedAt time.Time `json:"published_at"`
}

type CoursePublishLesson struct {
	ID               int64  `json:"id"`
	PublishModuleID  int64  `json:"publish_module_id"`
	Position         int32  `json:"position"`
	Title            string `json:"title"`
	ContentVersionID int64  `json:"content_version_id"`
	ContentID        int64  `json:"content_id"`
	RequiredLevel    int32  `json:"required_level"`
}

type CoursePublishModule struct {
	ID        int64  `json:"id"`
	PublishID int64  `json:"publish_id"`
	Position  int32  `json:"position"`
	Title     string `json:"title"`
}

type Payment struct {
	ID          int64     `json:"id"`
	CommunityID int64     `json:"community_id"`
	RequestID   string    `json:"request_id"`
	UserID      int64     `json:"user_id"`
	TierID      int64     `json:"tier_id"`
	AmountCents int64     `json:"amount_cents"`
	Days        int32     `json:"days"`
	CreatedAt   time.Time `json:"created_at"`
}

type Report struct {
	ID          int64     `json:"id"`
	CommunityID int64     `json:"community_id"`
	ContentID   int64     `json:"content_id"`
	VersionID   int64     `json:"version_id"`
	ReporterID  int64     `json:"reporter_id"`
	Category    string    `json:"category"`
	Reason      string    `json:"reason"`
	Status      string    `json:"status"`
	Appealed    bool      `json:"appealed"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type ReportEvent struct {
	ID          int64     `json:"id"`
	ReportID    int64     `json:"report_id"`
	CommunityID int64     `json:"community_id"`
	ActorID     int64     `json:"actor_id"`
	Action      string    `json:"action"`
	Basis       string    `json:"basis"`
	CreatedAt   time.Time `json:"created_at"`
}

type Subscription struct {
	ID          int64     `json:"id"`
	CommunityID int64     `json:"community_id"`
	UserID      int64     `json:"user_id"`
	TierID      int64     `json:"tier_id"`
	Status      string    `json:"status"`
	PeriodEnd   time.Time `json:"period_end"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Tier struct {
	ID           int64     `json:"id"`
	CommunityID  int64     `json:"community_id"`
	Level        int32     `json:"level"`
	Name         string    `json:"name"`
	PriceCents   int64     `json:"price_cents"`
	DurationDays int32     `json:"duration_days"`
	IsActive     bool      `json:"is_active"`
	CreatedAt    time.Time `json:"created_at"`
}

type User struct {
	ID          int64     `json:"id"`
	CommunityID int64     `json:"community_id"`
	Username    string    `json:"username"`
	Role        string    `json:"role"`
	Token       string    `json:"token"`
	CreatedAt   time.Time `json:"created_at"`
}
