// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"context"
)

type Querier interface {
	// 受理: valid only while the report is still in the initial accepted state.
	AcceptReport(ctx context.Context, arg AcceptReportParams) (Report, error)
	AddAttachment(ctx context.Context, arg AddAttachmentParams) (AddAttachmentRow, error)
	// One appeal only; flips the report back to the accepted/pending state so the
	// ruling endpoints can decide it a second time.
	AppealReport(ctx context.Context, arg AppealReportParams) (Report, error)
	// Moderator approve. Bound to BOTH the submitted version and the expected
	// content status. If an author edited after submission, current_version_id has
	// moved on and this matches zero rows -> 409; the unreviewed new version can
	// never be published.
	ApproveContent(ctx context.Context, arg ApproveContentParams) (Content, error)
	ApproveVersion(ctx context.Context, arg ApproveVersionParams) error
	// Initial binding right after content creation, when current_version_id is
	// still NULL (NULL = NULL never matches, so it needs its own predicate).
	BindInitialVersion(ctx context.Context, arg BindInitialVersionParams) error
	// Immediate loss of access: status flips to cancelled; access checks require
	// status='active', so the change takes effect at once.
	CancelSubscription(ctx context.Context, arg CancelSubscriptionParams) error
	CountTiers(ctx context.Context, communityID int64) (int64, error)
	CreateCommunity(ctx context.Context, name string) (Community, error)
	CreateContent(ctx context.Context, arg CreateContentParams) (Content, error)
	CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error)
	CreateLesson(ctx context.Context, arg CreateLessonParams) (CourseLesson, error)
	CreateModule(ctx context.Context, arg CreateModuleParams) (CourseModule, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreatePublish(ctx context.Context, arg CreatePublishParams) (CoursePublish, error)
	CreatePublishLesson(ctx context.Context, arg CreatePublishLessonParams) (CoursePublishLesson, error)
	CreatePublishModule(ctx context.Context, arg CreatePublishModuleParams) (CoursePublishModule, error)
	CreateReport(ctx context.Context, arg CreateReportParams) (Report, error)
	CreateTier(ctx context.Context, arg CreateTierParams) (Tier, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVersion(ctx context.Context, arg CreateVersionParams) (ContentVersion, error)
	// Successful appeal; content may then be explicitly restored.
	DecideAppealDismissed(ctx context.Context, arg DecideAppealDismissedParams) (Report, error)
	// Appeal ruling against the appellant.
	DecideAppealUpheld(ctx context.Context, arg DecideAppealUpheldParams) (Report, error)
	DeleteModulesForCourse(ctx context.Context, courseID int64) error
	DelistContent(ctx context.Context, arg DelistContentParams) (Content, error)
	// First-instance ruling for the content (accepted -> dismissed).
	DismissReport(ctx context.Context, arg DismissReportParams) (Report, error)
	// Author edit: creates a new current version; any pending content drops back to
	// draft so a pending approve cannot publish the new, unreviewed version.
	EditContentSwapVersion(ctx context.Context, arg EditContentSwapVersionParams) (Content, error)
	GetAttachment(ctx context.Context, arg GetAttachmentParams) (Attachment, error)
	GetCommunity(ctx context.Context, id int64) (Community, error)
	GetContent(ctx context.Context, arg GetContentParams) (Content, error)
	GetContentForUpdate(ctx context.Context, arg GetContentForUpdateParams) (Content, error)
	GetCourse(ctx context.Context, arg GetCourseParams) (Course, error)
	GetCourseForUpdate(ctx context.Context, arg GetCourseForUpdateParams) (Course, error)
	// Returns the member's effective tier level, or sqlc.ErrNoRows when there is no
	// active, unexpired subscription. Single locking read so renewal and access
	// checks serialize on the subscription row.
	GetEffectiveLevel(ctx context.Context, arg GetEffectiveLevelParams) (int32, error)
	GetLatestPublish(ctx context.Context, arg GetLatestPublishParams) (CoursePublish, error)
	// Idempotency lookup for payment registration.
	GetPaymentByRequest(ctx context.Context, arg GetPaymentByRequestParams) (Payment, error)
	GetReport(ctx context.Context, arg GetReportParams) (Report, error)
	GetReportForUpdate(ctx context.Context, arg GetReportForUpdateParams) (Report, error)
	GetSubscription(ctx context.Context, arg GetSubscriptionParams) (Subscription, error)
	GetTier(ctx context.Context, arg GetTierParams) (Tier, error)
	GetUser(ctx context.Context, arg GetUserParams) (User, error)
	GetUserByToken(ctx context.Context, token string) (User, error)
	GetVersion(ctx context.Context, arg GetVersionParams) (ContentVersion, error)
	InsertContentEvent(ctx context.Context, arg InsertContentEventParams) error
	InsertReportEvent(ctx context.Context, arg InsertReportEventParams) error
	ListAttachmentBlobs(ctx context.Context, versionID int64) ([]ListAttachmentBlobsRow, error)
	ListAttachmentsMeta(ctx context.Context, versionID int64) ([]ListAttachmentsMetaRow, error)
	ListContentEvents(ctx context.Context, arg ListContentEventsParams) ([]ContentEvent, error)
	ListContents(ctx context.Context, arg ListContentsParams) ([]Content, error)
	ListCourses(ctx context.Context, arg ListCoursesParams) ([]Course, error)
	ListDraftLessons(ctx context.Context, courseID int64) ([]CourseLesson, error)
	ListDraftModules(ctx context.Context, courseID int64) ([]CourseModule, error)
	ListPublishLessons(ctx context.Context, publishModuleID int64) ([]CoursePublishLesson, error)
	ListPublishModules(ctx context.Context, publishID int64) ([]CoursePublishModule, error)
	ListReportEvents(ctx context.Context, arg ListReportEventsParams) ([]ReportEvent, error)
	ListReports(ctx context.Context, arg ListReportsParams) ([]Report, error)
	ListTiers(ctx context.Context, communityID int64) ([]Tier, error)
	ListUsers(ctx context.Context, communityID int64) ([]User, error)
	ListVersions(ctx context.Context, arg ListVersionsParams) ([]ContentVersion, error)
	MarkCoursePublished(ctx context.Context, arg MarkCoursePublishedParams) error
	MarkVersionPending(ctx context.Context, arg MarkVersionPendingParams) error
	NextVersionNo(ctx context.Context, contentID int64) (int32, error)
	// Reject: content returns to draft; only the bound pending version is rejected.
	RejectContent(ctx context.Context, arg RejectContentParams) (Content, error)
	RejectVersion(ctx context.Context, arg RejectVersionParams) error
	// Restore safety: only succeeds if the version being restored is still the
	// newest version of the content. A newer edit after the takedown makes this
	// match zero rows -> 409, so restoring an old version never clobbers new work.
	RestoreContent(ctx context.Context, arg RestoreContentParams) (Content, error)
	SetTierActive(ctx context.Context, arg SetTierActiveParams) error
	// Author submits current working version for review. Allowed from draft,
	// a previously-pending content (re-submit no-op-ish), or delisted (appeal
	// rework path). Must bind the exact current_version_id.
	SubmitContent(ctx context.Context, arg SubmitContentParams) (Content, error)
	// First-instance ruling against content (accepted -> upheld).
	UpholdReport(ctx context.Context, arg UpholdReportParams) (Report, error)
	// Single-statement insert-or-renew. On the unique (community_id,user_id)
	// conflict PostgreSQL takes a row lock and re-evaluates the DO UPDATE against
	// the winner's committed row, so two first-time payments that race serialize
	// into one insert plus one renewal instead of a duplicate key error.
	UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) (Subscription, error)
	// Full validation of every lesson's referenced version at publish time:
	// version must exist, be the content's currently published frozen version,
	// content published (not delisted), and the content's required tier must not
	// exceed the course's tier.
	ValidateCourseDraft(ctx context.Context, courseID int64) ([]ValidateCourseDraftRow, error)
}

var _ Querier = (*Queries)(nil)
