# Generated by Django 5.0.14 on 2026-09-21 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'assets',
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('frozen', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('is_equity', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='accounts.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'balances',
            },
        ),
        migrations.AddConstraint(
            model_name='balance',
            constraint=models.CheckConstraint(check=models.Q(('available__gte', 0), ('is_equity', True), _connector='OR'), name='balance_available_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='balance',
            constraint=models.CheckConstraint(check=models.Q(('frozen__gte', 0)), name='balance_frozen_nonneg'),
        ),
        migrations.AlterUniqueTogether(
            name='balance',
            unique_together={('user', 'asset')},
        ),
    ]
