# Generated by Django 5.0.14 on 2026-09-21 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32, unique=True)),
                ('maker_fee_bps', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('taker_fee_bps', models.DecimalField(decimal_places=4, default=10, max_digits=10)),
                ('min_quantity', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('min_notional', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('is_active', models.BooleanField(default=True)),
                ('in_maintenance', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='base_markets', to='accounts.asset')),
                ('quote_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_markets', to='accounts.asset')),
            ],
            options={
                'db_table': 'markets',
            },
        ),
    ]
