# SPDX-License-Identifier: MIT
# SPSC shared-memory ring queue — build file.
# Zero third-party libraries: libc + libpthread + librt only.

CXX      ?= g++
CXXFLAGS ?= -std=c++17 -O2 -g -Wall -Wextra -Wpedantic -pthread
LDLIBS   ?= -lrt -pthread

BINARIES := shmring-producer shmring-consumer shmring-ctl
LIB_SRCS := shmring.cpp
LIB_OBJS := $(LIB_SRCS:.cpp=.o)

.PHONY: all clean test demo versions check

all: $(BINARIES)

shmring.o: shmring.cpp shmring.h
	$(CXX) $(CXXFLAGS) -c shmring.cpp -o $@

shmring-producer: producer.cpp cli_common.h shmring.h $(LIB_OBJS)
	$(CXX) $(CXXFLAGS) producer.cpp $(LIB_OBJS) -o $@ $(LDLIBS)

shmring-consumer: consumer.cpp cli_common.h shmring.h $(LIB_OBJS)
	$(CXX) $(CXXFLAGS) consumer.cpp $(LIB_OBJS) -o $@ $(LDLIBS)

shmring-ctl: ctl.cpp cli_common.h shmring.h $(LIB_OBJS)
	$(CXX) $(CXXFLAGS) ctl.cpp $(LIB_OBJS) -o $@ $(LDLIBS)

check: $(BINARIES)
	./shmring-ctl check

test: $(BINARIES)
	python3 tests/run_tests.py

demo: $(BINARIES)
	./scripts/demo.sh

# Record the exact toolchain this tree was built/tested with.
versions:
	@echo "# dependency lock — generated by 'make versions'" > deps.lock
	@echo "date=$$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> deps.lock
	@echo "kernel=$$(uname -srm)" >> deps.lock
	@echo "cxx=$$($(CXX) --version | head -1)" >> deps.lock
	@echo "cxx_std=c++17" >> deps.lock
	@echo "python=$$(python3 --version 2>&1)" >> deps.lock
	@echo "make=$$(make --version | head -1)" >> deps.lock
	@echo "linked_libs=-lrt,-lpthread(glibc)" >> deps.lock
	@echo "third_party=none" >> deps.lock
	@cat deps.lock

clean:
	rm -f $(BINARIES) $(LIB_OBJS)
