# Generated by Django 5.0.14 on 2026-09-21 00:50

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='项目编码')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用中')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, verbose_name='模板编码')),
                ('version', models.PositiveIntegerField(verbose_name='版本号')),
                ('name', models.CharField(max_length=200, verbose_name='模板名称')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('deprecated', '已弃用')], default='draft', max_length=20)),
                ('schema', models.JSONField(default=core.models._default_schema, verbose_name='表单定义')),
                ('legacy_fields', models.JSONField(blank=True, default=list, verbose_name='遗留字段白名单')),
                ('version_notes', models.TextField(blank=True, default='', verbose_name='版本说明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('deprecated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='core.project')),
            ],
            options={
                'verbose_name': '表单模板',
                'verbose_name_plural': '表单模板',
                'ordering': ('project_id', 'code', '-version'),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('worker', '工作人员'), ('supervisor', '主管'), ('admin', '管理员')], default='worker', max_length=20, verbose_name='角色')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('assigned_projects', models.ManyToManyField(blank=True, related_name='assigned_users', to='core.project', verbose_name='分配项目')),
            ],
            options={
                'verbose_name': '用户档案',
                'verbose_name_plural': '用户档案',
            },
        ),
        migrations.CreateModel(
            name='FormRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, verbose_name='记录 UUID')),
                ('status', models.CharField(choices=[('active', '正常'), ('in_conflict', '冲突待解决'), ('resolved', '冲突已解决'), ('deleted', '已删除')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='core.formtemplate')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='core.project')),
            ],
            options={
                'verbose_name': '现场记录',
                'verbose_name_plural': '现场记录',
            },
        ),
        migrations.CreateModel(
            name='RecordVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField(verbose_name='提交内容')),
                ('content_hash', models.CharField(db_index=True, max_length=64, verbose_name='内容哈希')),
                ('client_record_version', models.PositiveIntegerField(verbose_name='客户端记录版本')),
                ('collected_at', models.DateTimeField(verbose_name='采集时间')),
                ('device_id', models.CharField(blank=True, default='', max_length=128, verbose_name='设备标识')),
                ('status', models.CharField(choices=[('accepted', '已接受（当前）'), ('candidate', '冲突候选'), ('superseded', '已被取代')], default='accepted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='record_versions', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='core.formrecord')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='record_versions', to='core.formtemplate')),
            ],
            options={
                'verbose_name': '记录版本',
                'verbose_name_plural': '记录版本',
                'ordering': ('id',),
                'get_latest_by': 'id',
            },
        ),
        migrations.AddField(
            model_name='formrecord',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.recordversion'),
        ),
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', '待解决'), ('resolved', '已解决')], default='open', max_length=20)),
                ('resolution_note', models.TextField(blank=True, default='', verbose_name='解决依据')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_conflicts', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conflicts', to='core.formrecord')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conflicts', to='core.project')),
                ('versions', models.ManyToManyField(related_name='conflicts', to='core.recordversion')),
                ('winning_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='won_conflicts', to='core.recordversion')),
            ],
            options={
                'verbose_name': '冲突',
                'verbose_name_plural': '冲突',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('record_upserted', '记录写入/更新'), ('conflict_detected', '发现冲突'), ('conflict_resolved', '冲突已解决'), ('record_deleted', '记录删除（墓碑）')], max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conflict', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.conflict')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_logs', to='core.formrecord')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_logs', to='core.project')),
                ('record_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.recordversion')),
            ],
            options={
                'verbose_name': '变更日志',
                'verbose_name_plural': '变更日志',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SyncBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_batch_id', models.CharField(max_length=128, verbose_name='客户端批次 ID')),
                ('status', models.CharField(choices=[('completed', '已完成'), ('processing', '处理中（异常中断）')], default='completed', max_length=20)),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_batches', to='core.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '同步批次',
                'verbose_name_plural': '同步批次',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SyncItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(verbose_name='批次内序号')),
                ('uuid', models.UUIDField()),
                ('status', models.CharField(choices=[('created', '新建成功'), ('updated', '接受新版本'), ('idempotent', '幂等重放（同 UUID 同内容）'), ('conflict', '内容冲突，已保留双方版本'), ('error', '校验/权限错误')], max_length=20)),
                ('code', models.CharField(max_length=64, verbose_name='机器可读码')),
                ('message', models.TextField(blank=True, default='')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.syncbatch')),
                ('conflict', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.conflict')),
                ('record_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.recordversion')),
            ],
            options={
                'verbose_name': '同步条目结果',
                'verbose_name_plural': '同步条目结果',
                'ordering': ('batch_id', 'index'),
            },
        ),
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursor', models.BigIntegerField(default=0, verbose_name='已确认游标')),
                ('hwm', models.BigIntegerField(blank=True, null=True, verbose_name='本轮快照高水位')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_states', to='core.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '同步游标',
                'verbose_name_plural': '同步游标',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='班组编码')),
                ('name', models.CharField(max_length=200, verbose_name='班组名称')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(blank=True, related_name='teams', to=settings.AUTH_USER_MODEL, verbose_name='班组成员')),
                ('projects', models.ManyToManyField(blank=True, related_name='teams', to='core.project', verbose_name='关联项目')),
                ('supervisors', models.ManyToManyField(blank=True, related_name='supervised_teams', to=settings.AUTH_USER_MODEL, verbose_name='主管')),
            ],
            options={
                'verbose_name': '班组',
                'verbose_name_plural': '班组',
                'ordering': ('code',),
            },
        ),
        migrations.AddIndex(
            model_name='formtemplate',
            index=models.Index(fields=['code', 'status'], name='core_formte_code_199be4_idx'),
        ),
        migrations.AddConstraint(
            model_name='formtemplate',
            constraint=models.UniqueConstraint(fields=('project', 'code', 'version'), name='uniq_template_project_code_version'),
        ),
        migrations.AddIndex(
            model_name='recordversion',
            index=models.Index(fields=['record', 'content_hash', 'client_record_version'], name='idx_rv_idempotent'),
        ),
        migrations.AddIndex(
            model_name='formrecord',
            index=models.Index(fields=['project', 'status'], name='core_formre_project_9c501f_idx'),
        ),
        migrations.AddConstraint(
            model_name='formrecord',
            constraint=models.UniqueConstraint(fields=('project', 'uuid'), name='uniq_record_project_uuid'),
        ),
        migrations.AddConstraint(
            model_name='conflict',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('record',), name='uniq_one_open_conflict_per_record'),
        ),
        migrations.AddIndex(
            model_name='changelog',
            index=models.Index(fields=['project', 'id'], name='core_change_project_488b4e_idx'),
        ),
        migrations.AddConstraint(
            model_name='syncbatch',
            constraint=models.UniqueConstraint(fields=('user', 'client_batch_id'), name='uniq_syncbatch_user_clientbatch'),
        ),
        migrations.AddConstraint(
            model_name='syncstate',
            constraint=models.UniqueConstraint(fields=('user', 'project'), name='uniq_syncstate_user_project'),
        ),
    ]
