# Generated by Django 5.0.14 on 2026-09-21 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncitem',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
