# Generated by Django 5.0.14 on 2026-09-21 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_syncitem_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncitem',
            name='raw_uuid',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='原始 UUID 字符串'),
        ),
    ]
