# Generated by Django 5.0.14 on 2026-09-21 02:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_syncitem_raw_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syncbatch',
            options={'verbose_name': '同步批次', 'verbose_name_plural': '同步批次'},
        ),
        migrations.AddIndex(
            model_name='syncbatch',
            index=models.Index(fields=['-created_at'], name='core_syncba_created_cb7294_idx'),
        ),
    ]
