# Generated by Django 5.0.14 on 2026-09-21 20:28

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LIMIT', 'Limit'), ('MARKET', 'Market')], max_length=8)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('price', models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True)),
                ('quote_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True)),
                ('filled_quantity', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=30)),
                ('frozen_remaining', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=30)),
                ('quote_filled', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=30)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('PARTIAL', 'Partially filled'), ('FILLED', 'Filled'), ('CANCELED', 'Canceled'), ('REJECTED', 'Rejected')], db_index=True, default='NEW', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.BigIntegerField(db_index=True, default=0)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='markets.market')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('request_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_keys', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='idempotency_keys', to='trading.order')),
            ],
            options={
                'db_table': 'idempotency_keys',
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=8, max_digits=30)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=30)),
                ('taker_fee', models.DecimalField(decimal_places=8, max_digits=30)),
                ('maker_fee', models.DecimalField(decimal_places=8, max_digits=30)),
                ('executed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('maker_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maker_trades', to='trading.order')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trades', to='markets.market')),
                ('taker_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taker_trades', to='trading.order')),
            ],
            options={
                'db_table': 'trades',
            },
        ),
        migrations.CreateModel(
            name='Fill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('TAKER', 'Taker'), ('MAKER', 'Maker')], max_length=5)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('price', models.DecimalField(decimal_places=8, max_digits=30)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=30)),
                ('fee', models.DecimalField(decimal_places=8, max_digits=30)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fills', to='trading.order')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fills', to='trading.trade')),
            ],
            options={
                'db_table': 'fills',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['market', 'side', 'status', 'price', 'sequence'], name='ix_order_book'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='ix_order_user'),
        ),
        migrations.AddConstraint(
            model_name='idempotencykey',
            constraint=models.UniqueConstraint(fields=('user', 'key'), name='uq_idem_user_key'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['market', '-executed_at'], name='ix_trade_mkt'),
        ),
        migrations.AddConstraint(
            model_name='fill',
            constraint=models.UniqueConstraint(fields=('trade', 'order'), name='uq_fill_trade_order'),
        ),
    ]
