// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: action_items.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createActionItem = `-- name: CreateActionItem :one
INSERT INTO action_items (id, incident_id, title, owner_id, due_at, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, incident_id, title, owner_id, due_at, version, status, created_by, created_at, updated_at
`

type CreateActionItemParams struct {
	ID         string             `json:"id"`
	IncidentID string             `json:"incident_id"`
	Title      string             `json:"title"`
	OwnerID    string             `json:"owner_id"`
	DueAt      pgtype.Timestamptz `json:"due_at"`
	CreatedBy  string             `json:"created_by"`
}

func (q *Queries) CreateActionItem(ctx context.Context, arg CreateActionItemParams) (ActionItem, error) {
	row := q.db.QueryRow(ctx, createActionItem,
		arg.ID,
		arg.IncidentID,
		arg.Title,
		arg.OwnerID,
		arg.DueAt,
		arg.CreatedBy,
	)
	var i ActionItem
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.Title,
		&i.OwnerID,
		&i.DueAt,
		&i.Version,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (id, action_item_id, owner_id, message, due_at, version)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, action_item_id, owner_id, message, due_at, version, created_at
`

type CreateNotificationParams struct {
	ID           string             `json:"id"`
	ActionItemID string             `json:"action_item_id"`
	OwnerID      string             `json:"owner_id"`
	Message      string             `json:"message"`
	DueAt        pgtype.Timestamptz `json:"due_at"`
	Version      int32              `json:"version"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.ID,
		arg.ActionItemID,
		arg.OwnerID,
		arg.Message,
		arg.DueAt,
		arg.Version,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.ActionItemID,
		&i.OwnerID,
		&i.Message,
		&i.DueAt,
		&i.Version,
		&i.CreatedAt,
	)
	return i, err
}

const dueActionItems = `-- name: DueActionItems :many
SELECT ai.id, ai.incident_id, ai.title, ai.owner_id, ai.due_at, ai.version, ai.status, ai.created_by, ai.created_at, ai.updated_at
FROM action_items ai
WHERE ai.status = 'open'
  AND ai.due_at <= $1
  AND NOT EXISTS (
      SELECT 1 FROM reminder_dispatches rd
      WHERE rd.action_item_id = ai.id AND rd.version = ai.version
  )
ORDER BY ai.due_at
LIMIT $2
`

type DueActionItemsParams struct {
	DueAt pgtype.Timestamptz `json:"due_at"`
	Limit int32              `json:"limit"`
}

// Open, due items that have never had a dispatch for their CURRENT version.
// The LEFT JOIN + NULL check is what stops an old schedule version from ever
// reminding after a reschedule.
func (q *Queries) DueActionItems(ctx context.Context, arg DueActionItemsParams) ([]ActionItem, error) {
	rows, err := q.db.Query(ctx, dueActionItems, arg.DueAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActionItem{}
	for rows.Next() {
		var i ActionItem
		if err := rows.Scan(
			&i.ID,
			&i.IncidentID,
			&i.Title,
			&i.OwnerID,
			&i.DueAt,
			&i.Version,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActionItem = `-- name: GetActionItem :one
SELECT id, incident_id, title, owner_id, due_at, version, status, created_by, created_at, updated_at FROM action_items WHERE id = $1
`

func (q *Queries) GetActionItem(ctx context.Context, id string) (ActionItem, error) {
	row := q.db.QueryRow(ctx, getActionItem, id)
	var i ActionItem
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.Title,
		&i.OwnerID,
		&i.DueAt,
		&i.Version,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActionItemForUpdate = `-- name: GetActionItemForUpdate :one
SELECT id, incident_id, title, owner_id, due_at, version, status, created_by, created_at, updated_at FROM action_items WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetActionItemForUpdate(ctx context.Context, id string) (ActionItem, error) {
	row := q.db.QueryRow(ctx, getActionItemForUpdate, id)
	var i ActionItem
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.Title,
		&i.OwnerID,
		&i.DueAt,
		&i.Version,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRescheduleAudit = `-- name: InsertRescheduleAudit :exec
INSERT INTO action_item_reschedules
    (id, action_item_id, from_version, to_version, old_due_at, new_due_at, actor_id, request_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertRescheduleAuditParams struct {
	ID           string             `json:"id"`
	ActionItemID string             `json:"action_item_id"`
	FromVersion  int32              `json:"from_version"`
	ToVersion    int32              `json:"to_version"`
	OldDueAt     pgtype.Timestamptz `json:"old_due_at"`
	NewDueAt     pgtype.Timestamptz `json:"new_due_at"`
	ActorID      string             `json:"actor_id"`
	RequestID    string             `json:"request_id"`
}

func (q *Queries) InsertRescheduleAudit(ctx context.Context, arg InsertRescheduleAuditParams) error {
	_, err := q.db.Exec(ctx, insertRescheduleAudit,
		arg.ID,
		arg.ActionItemID,
		arg.FromVersion,
		arg.ToVersion,
		arg.OldDueAt,
		arg.NewDueAt,
		arg.ActorID,
		arg.RequestID,
	)
	return err
}

const listActionItems = `-- name: ListActionItems :many
SELECT id, incident_id, title, owner_id, due_at, version, status, created_by, created_at, updated_at FROM action_items WHERE incident_id = $1 ORDER BY due_at, id
`

func (q *Queries) ListActionItems(ctx context.Context, incidentID string) ([]ActionItem, error) {
	rows, err := q.db.Query(ctx, listActionItems, incidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActionItem{}
	for rows.Next() {
		var i ActionItem
		if err := rows.Scan(
			&i.ID,
			&i.IncidentID,
			&i.Title,
			&i.OwnerID,
			&i.DueAt,
			&i.Version,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, action_item_id, owner_id, message, due_at, version, created_at FROM notifications
WHERE ($4::boolean = true OR owner_id = $1)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListNotificationsParams struct {
	OwnerID    string `json:"owner_id"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
	IncludeAll bool   `json:"include_all"`
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications,
		arg.OwnerID,
		arg.Limit,
		arg.Offset,
		arg.IncludeAll,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.ActionItemID,
			&i.OwnerID,
			&i.Message,
			&i.DueAt,
			&i.Version,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReminderDispatched = `-- name: MarkReminderDispatched :execrows
INSERT INTO reminder_dispatches (action_item_id, version)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type MarkReminderDispatchedParams struct {
	ActionItemID string `json:"action_item_id"`
	Version      int32  `json:"version"`
}

func (q *Queries) MarkReminderDispatched(ctx context.Context, arg MarkReminderDispatchedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markReminderDispatched, arg.ActionItemID, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rescheduleActionItem = `-- name: RescheduleActionItem :one
UPDATE action_items
SET due_at = $2,
    version = version + 1,
    updated_at = now()
WHERE id = $1 AND version = $3
RETURNING id, incident_id, title, owner_id, due_at, version, status, created_by, created_at, updated_at
`

type RescheduleActionItemParams struct {
	ID      string             `json:"id"`
	DueAt   pgtype.Timestamptz `json:"due_at"`
	Version int32              `json:"version"`
}

// Optimistic-locked reschedule. WHERE version = $3 makes a stale concurrent
// reschedule lose, so no two schedules for the same version survive.
func (q *Queries) RescheduleActionItem(ctx context.Context, arg RescheduleActionItemParams) (ActionItem, error) {
	row := q.db.QueryRow(ctx, rescheduleActionItem, arg.ID, arg.DueAt, arg.Version)
	var i ActionItem
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.Title,
		&i.OwnerID,
		&i.DueAt,
		&i.Version,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateActionItemStatus = `-- name: UpdateActionItemStatus :one
UPDATE action_items
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, incident_id, title, owner_id, due_at, version, status, created_by, created_at, updated_at
`

type UpdateActionItemStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateActionItemStatus(ctx context.Context, arg UpdateActionItemStatusParams) (ActionItem, error) {
	row := q.db.QueryRow(ctx, updateActionItemStatus, arg.ID, arg.Status)
	var i ActionItem
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.Title,
		&i.OwnerID,
		&i.DueAt,
		&i.Version,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
