// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: evidence.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addEvidence = `-- name: AddEvidence :one
INSERT INTO evidence (id, incident_id, content, submitted_by, request_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, incident_id, content, submitted_by, created_at, request_id
`

type AddEvidenceParams struct {
	ID          string `json:"id"`
	IncidentID  string `json:"incident_id"`
	Content     string `json:"content"`
	SubmittedBy string `json:"submitted_by"`
	RequestID   string `json:"request_id"`
}

func (q *Queries) AddEvidence(ctx context.Context, arg AddEvidenceParams) (Evidence, error) {
	row := q.db.QueryRow(ctx, addEvidence,
		arg.ID,
		arg.IncidentID,
		arg.Content,
		arg.SubmittedBy,
		arg.RequestID,
	)
	var i Evidence
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.Content,
		&i.SubmittedBy,
		&i.CreatedAt,
		&i.RequestID,
	)
	return i, err
}

const addEvidenceNote = `-- name: AddEvidenceNote :one
INSERT INTO evidence_notes (id, evidence_id, content, added_by, request_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, evidence_id, content, added_by, created_at, request_id
`

type AddEvidenceNoteParams struct {
	ID         string `json:"id"`
	EvidenceID string `json:"evidence_id"`
	Content    string `json:"content"`
	AddedBy    string `json:"added_by"`
	RequestID  string `json:"request_id"`
}

func (q *Queries) AddEvidenceNote(ctx context.Context, arg AddEvidenceNoteParams) (EvidenceNote, error) {
	row := q.db.QueryRow(ctx, addEvidenceNote,
		arg.ID,
		arg.EvidenceID,
		arg.Content,
		arg.AddedBy,
		arg.RequestID,
	)
	var i EvidenceNote
	err := row.Scan(
		&i.ID,
		&i.EvidenceID,
		&i.Content,
		&i.AddedBy,
		&i.CreatedAt,
		&i.RequestID,
	)
	return i, err
}

const countEvidence = `-- name: CountEvidence :one
SELECT count(*)::int AS cnt FROM evidence WHERE incident_id = $1
`

func (q *Queries) CountEvidence(ctx context.Context, incidentID string) (int32, error) {
	row := q.db.QueryRow(ctx, countEvidence, incidentID)
	var cnt int32
	err := row.Scan(&cnt)
	return cnt, err
}

const getEvidence = `-- name: GetEvidence :one
SELECT id, incident_id, content, submitted_by, created_at, request_id FROM evidence WHERE id = $1
`

func (q *Queries) GetEvidence(ctx context.Context, id string) (Evidence, error) {
	row := q.db.QueryRow(ctx, getEvidence, id)
	var i Evidence
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.Content,
		&i.SubmittedBy,
		&i.CreatedAt,
		&i.RequestID,
	)
	return i, err
}

const listEvidence = `-- name: ListEvidence :many
SELECT id, incident_id, content, submitted_by, created_at, request_id FROM evidence WHERE incident_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListEvidence(ctx context.Context, incidentID string) ([]Evidence, error) {
	rows, err := q.db.Query(ctx, listEvidence, incidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Evidence{}
	for rows.Next() {
		var i Evidence
		if err := rows.Scan(
			&i.ID,
			&i.IncidentID,
			&i.Content,
			&i.SubmittedBy,
			&i.CreatedAt,
			&i.RequestID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvidenceWithNotes = `-- name: ListEvidenceWithNotes :many
SELECT
    e.id AS evidence_id,
    e.content AS evidence_content,
    e.submitted_by AS evidence_submitted_by,
    e.created_at AS evidence_created_at,
    n.id AS note_id,
    n.content AS note_content,
    n.added_by AS note_added_by,
    n.created_at AS note_created_at
FROM evidence e
LEFT JOIN evidence_notes n ON n.evidence_id = e.id
WHERE e.incident_id = $1
ORDER BY e.created_at, e.id, n.created_at
`

type ListEvidenceWithNotesRow struct {
	EvidenceID          string             `json:"evidence_id"`
	EvidenceContent     string             `json:"evidence_content"`
	EvidenceSubmittedBy string             `json:"evidence_submitted_by"`
	EvidenceCreatedAt   pgtype.Timestamptz `json:"evidence_created_at"`
	NoteID              pgtype.Text        `json:"note_id"`
	NoteContent         pgtype.Text        `json:"note_content"`
	NoteAddedBy         pgtype.Text        `json:"note_added_by"`
	NoteCreatedAt       pgtype.Timestamptz `json:"note_created_at"`
}

func (q *Queries) ListEvidenceWithNotes(ctx context.Context, incidentID string) ([]ListEvidenceWithNotesRow, error) {
	rows, err := q.db.Query(ctx, listEvidenceWithNotes, incidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEvidenceWithNotesRow{}
	for rows.Next() {
		var i ListEvidenceWithNotesRow
		if err := rows.Scan(
			&i.EvidenceID,
			&i.EvidenceContent,
			&i.EvidenceSubmittedBy,
			&i.EvidenceCreatedAt,
			&i.NoteID,
			&i.NoteContent,
			&i.NoteAddedBy,
			&i.NoteCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
