// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: incidents.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addIncidentMember = `-- name: AddIncidentMember :exec
INSERT INTO incident_members (incident_id, user_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddIncidentMemberParams struct {
	IncidentID string `json:"incident_id"`
	UserID     string `json:"user_id"`
}

func (q *Queries) AddIncidentMember(ctx context.Context, arg AddIncidentMemberParams) error {
	_, err := q.db.Exec(ctx, addIncidentMember, arg.IncidentID, arg.UserID)
	return err
}

const assignIncidentPerson = `-- name: AssignIncidentPerson :exec
UPDATE incidents
SET assigned_analyst_id   = CASE WHEN $2::text = 'analyst'   THEN $3 ELSE assigned_analyst_id END,
    assigned_responder_id = CASE WHEN $2::text = 'responder' THEN $3 ELSE assigned_responder_id END,
    updated_at = now()
WHERE id = $1
`

type AssignIncidentPersonParams struct {
	ID     string      `json:"id"`
	Role   string      `json:"role"`
	UserID pgtype.Text `json:"user_id"`
}

func (q *Queries) AssignIncidentPerson(ctx context.Context, arg AssignIncidentPersonParams) error {
	_, err := q.db.Exec(ctx, assignIncidentPerson, arg.ID, arg.Role, arg.UserID)
	return err
}

const countActionItemsAny = `-- name: CountActionItemsAny :one
SELECT EXISTS (SELECT 1 FROM action_items WHERE incident_id = $1) AS any_items
`

func (q *Queries) CountActionItemsAny(ctx context.Context, incidentID string) (bool, error) {
	row := q.db.QueryRow(ctx, countActionItemsAny, incidentID)
	var any_items bool
	err := row.Scan(&any_items)
	return any_items, err
}

const countOpenActionItems = `-- name: CountOpenActionItems :one
SELECT count(*)::int AS open_count FROM action_items
WHERE incident_id = $1 AND status = 'open'
`

func (q *Queries) CountOpenActionItems(ctx context.Context, incidentID string) (int32, error) {
	row := q.db.QueryRow(ctx, countOpenActionItems, incidentID)
	var open_count int32
	err := row.Scan(&open_count)
	return open_count, err
}

const createIncident = `-- name: CreateIncident :one
INSERT INTO incidents (id, title, severity, created_by, assigned_analyst_id, assigned_responder_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, title, severity, stage, version, created_by, assigned_analyst_id, assigned_responder_id, root_cause, lessons_learned, detected_at, triaged_at, contained_at, eradicated_at, recovered_at, postmortem_at, closed_at, created_at, updated_at
`

type CreateIncidentParams struct {
	ID                  string      `json:"id"`
	Title               string      `json:"title"`
	Severity            string      `json:"severity"`
	CreatedBy           string      `json:"created_by"`
	AssignedAnalystID   pgtype.Text `json:"assigned_analyst_id"`
	AssignedResponderID pgtype.Text `json:"assigned_responder_id"`
}

func (q *Queries) CreateIncident(ctx context.Context, arg CreateIncidentParams) (Incident, error) {
	row := q.db.QueryRow(ctx, createIncident,
		arg.ID,
		arg.Title,
		arg.Severity,
		arg.CreatedBy,
		arg.AssignedAnalystID,
		arg.AssignedResponderID,
	)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Severity,
		&i.Stage,
		&i.Version,
		&i.CreatedBy,
		&i.AssignedAnalystID,
		&i.AssignedResponderID,
		&i.RootCause,
		&i.LessonsLearned,
		&i.DetectedAt,
		&i.TriagedAt,
		&i.ContainedAt,
		&i.EradicatedAt,
		&i.RecoveredAt,
		&i.PostmortemAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIncident = `-- name: GetIncident :one
SELECT id, title, severity, stage, version, created_by, assigned_analyst_id, assigned_responder_id, root_cause, lessons_learned, detected_at, triaged_at, contained_at, eradicated_at, recovered_at, postmortem_at, closed_at, created_at, updated_at FROM incidents WHERE id = $1
`

func (q *Queries) GetIncident(ctx context.Context, id string) (Incident, error) {
	row := q.db.QueryRow(ctx, getIncident, id)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Severity,
		&i.Stage,
		&i.Version,
		&i.CreatedBy,
		&i.AssignedAnalystID,
		&i.AssignedResponderID,
		&i.RootCause,
		&i.LessonsLearned,
		&i.DetectedAt,
		&i.TriagedAt,
		&i.ContainedAt,
		&i.EradicatedAt,
		&i.RecoveredAt,
		&i.PostmortemAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIncidentForUpdate = `-- name: GetIncidentForUpdate :one
SELECT id, title, severity, stage, version, created_by, assigned_analyst_id, assigned_responder_id, root_cause, lessons_learned, detected_at, triaged_at, contained_at, eradicated_at, recovered_at, postmortem_at, closed_at, created_at, updated_at FROM incidents WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetIncidentForUpdate(ctx context.Context, id string) (Incident, error) {
	row := q.db.QueryRow(ctx, getIncidentForUpdate, id)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Severity,
		&i.Stage,
		&i.Version,
		&i.CreatedBy,
		&i.AssignedAnalystID,
		&i.AssignedResponderID,
		&i.RootCause,
		&i.LessonsLearned,
		&i.DetectedAt,
		&i.TriagedAt,
		&i.ContainedAt,
		&i.EradicatedAt,
		&i.RecoveredAt,
		&i.PostmortemAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertStageEvent = `-- name: InsertStageEvent :one
INSERT INTO stage_events (id, incident_id, version, from_stage, to_stage, actor_id, note, request_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, incident_id, version, from_stage, to_stage, actor_id, note, occurred_at, request_id
`

type InsertStageEventParams struct {
	ID         string `json:"id"`
	IncidentID string `json:"incident_id"`
	Version    int64  `json:"version"`
	FromStage  string `json:"from_stage"`
	ToStage    string `json:"to_stage"`
	ActorID    string `json:"actor_id"`
	Note       string `json:"note"`
	RequestID  string `json:"request_id"`
}

func (q *Queries) InsertStageEvent(ctx context.Context, arg InsertStageEventParams) (StageEvent, error) {
	row := q.db.QueryRow(ctx, insertStageEvent,
		arg.ID,
		arg.IncidentID,
		arg.Version,
		arg.FromStage,
		arg.ToStage,
		arg.ActorID,
		arg.Note,
		arg.RequestID,
	)
	var i StageEvent
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.Version,
		&i.FromStage,
		&i.ToStage,
		&i.ActorID,
		&i.Note,
		&i.OccurredAt,
		&i.RequestID,
	)
	return i, err
}

const isIncidentMember = `-- name: IsIncidentMember :one
SELECT EXISTS(
    SELECT 1 FROM incident_members WHERE incident_id = $1 AND user_id = $2
) AS member
`

type IsIncidentMemberParams struct {
	IncidentID string `json:"incident_id"`
	UserID     string `json:"user_id"`
}

func (q *Queries) IsIncidentMember(ctx context.Context, arg IsIncidentMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isIncidentMember, arg.IncidentID, arg.UserID)
	var member bool
	err := row.Scan(&member)
	return member, err
}

const listIncidentMembers = `-- name: ListIncidentMembers :many
SELECT u.id, u.name, u.role, u.created_at FROM users u
JOIN incident_members im ON im.user_id = u.id
WHERE im.incident_id = $1
ORDER BY u.id
`

func (q *Queries) ListIncidentMembers(ctx context.Context, incidentID string) ([]User, error) {
	rows, err := q.db.Query(ctx, listIncidentMembers, incidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncidents = `-- name: ListIncidents :many
SELECT id, title, severity, stage, version, created_by, assigned_analyst_id, assigned_responder_id, root_cause, lessons_learned, detected_at, triaged_at, contained_at, eradicated_at, recovered_at, postmortem_at, closed_at, created_at, updated_at FROM incidents
WHERE ($3::boolean = false
       OR assigned_analyst_id = $4
       OR assigned_responder_id = $4)
  AND ($5::text = '' OR severity = $5)
ORDER BY created_at DESC, id
LIMIT $1 OFFSET $2
`

type ListIncidentsParams struct {
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
	AssigneeFilter bool        `json:"assignee_filter"`
	UserID         pgtype.Text `json:"user_id"`
	Severity       string      `json:"severity"`
}

func (q *Queries) ListIncidents(ctx context.Context, arg ListIncidentsParams) ([]Incident, error) {
	rows, err := q.db.Query(ctx, listIncidents,
		arg.Limit,
		arg.Offset,
		arg.AssigneeFilter,
		arg.UserID,
		arg.Severity,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Incident{}
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Severity,
			&i.Stage,
			&i.Version,
			&i.CreatedBy,
			&i.AssignedAnalystID,
			&i.AssignedResponderID,
			&i.RootCause,
			&i.LessonsLearned,
			&i.DetectedAt,
			&i.TriagedAt,
			&i.ContainedAt,
			&i.EradicatedAt,
			&i.RecoveredAt,
			&i.PostmortemAt,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncidentsForExport = `-- name: ListIncidentsForExport :many
SELECT id, title, severity, stage, version, created_by, assigned_analyst_id, assigned_responder_id, root_cause, lessons_learned, detected_at, triaged_at, contained_at, eradicated_at, recovered_at, postmortem_at, closed_at, created_at, updated_at FROM incidents ORDER BY created_at
`

func (q *Queries) ListIncidentsForExport(ctx context.Context) ([]Incident, error) {
	rows, err := q.db.Query(ctx, listIncidentsForExport)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Incident{}
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Severity,
			&i.Stage,
			&i.Version,
			&i.CreatedBy,
			&i.AssignedAnalystID,
			&i.AssignedResponderID,
			&i.RootCause,
			&i.LessonsLearned,
			&i.DetectedAt,
			&i.TriagedAt,
			&i.ContainedAt,
			&i.EradicatedAt,
			&i.RecoveredAt,
			&i.PostmortemAt,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStageEvents = `-- name: ListStageEvents :many
SELECT id, incident_id, version, from_stage, to_stage, actor_id, note, occurred_at, request_id FROM stage_events WHERE incident_id = $1 ORDER BY version, occurred_at
`

func (q *Queries) ListStageEvents(ctx context.Context, incidentID string) ([]StageEvent, error) {
	rows, err := q.db.Query(ctx, listStageEvents, incidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StageEvent{}
	for rows.Next() {
		var i StageEvent
		if err := rows.Scan(
			&i.ID,
			&i.IncidentID,
			&i.Version,
			&i.FromStage,
			&i.ToStage,
			&i.ActorID,
			&i.Note,
			&i.OccurredAt,
			&i.RequestID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transitionIncident = `-- name: TransitionIncident :one
UPDATE incidents AS inc
    SET stage     = $1,
        version   = version + 1,
        triaged_at    = CASE WHEN $1 = 'triaged'    THEN now() ELSE triaged_at END,
        contained_at  = CASE WHEN $1 = 'contained'  THEN now() ELSE contained_at END,
        eradicated_at = CASE WHEN $1 = 'eradicated' THEN now() ELSE eradicated_at END,
        recovered_at  = CASE WHEN $1 = 'recovered'  THEN now() ELSE recovered_at END,
        postmortem_at = CASE WHEN $1 = 'postmortem' THEN now() ELSE postmortem_at END,
        closed_at     = CASE WHEN $1 = 'closed'     THEN now() ELSE closed_at END,
        root_cause      = COALESCE($2, root_cause),
        lessons_learned = COALESCE($3, lessons_learned),
        updated_at = now()
    WHERE inc.id = $4
      AND inc.version = $5
      AND inc.stage = $6
      AND NOT ($6 = 'detected'
               AND inc.severity = 'P1'
               AND inc.assigned_responder_id IS NULL)
      AND NOT ($1 = 'closed'
               AND (inc.root_cause IS NULL OR inc.root_cause = ''
                    OR inc.lessons_learned IS NULL OR inc.lessons_learned = ''
                    OR NOT EXISTS (SELECT 1 FROM action_items ai
                                   WHERE ai.incident_id = inc.id)))
RETURNING inc.id, inc.title, inc.severity, inc.stage, inc.version, inc.created_by, inc.assigned_analyst_id, inc.assigned_responder_id, inc.root_cause, inc.lessons_learned, inc.detected_at, inc.triaged_at, inc.contained_at, inc.eradicated_at, inc.recovered_at, inc.postmortem_at, inc.closed_at, inc.created_at, inc.updated_at
`

type TransitionIncidentParams struct {
	ToStage         string      `json:"to_stage"`
	RootCause       pgtype.Text `json:"root_cause"`
	LessonsLearned  pgtype.Text `json:"lessons_learned"`
	IncidentID      string      `json:"incident_id"`
	ExpectedVersion int64       `json:"expected_version"`
	FromStage       string      `json:"from_stage"`
}

// Atomic forward transition. The WHERE clause enforces: expected version
// (optimistic lock), exact current stage (no skipped transitions), and the
// P1 triage gate. Returns the updated row; no row means the caller must
// distinguish version mismatch from stage mismatch.
func (q *Queries) TransitionIncident(ctx context.Context, arg TransitionIncidentParams) (Incident, error) {
	row := q.db.QueryRow(ctx, transitionIncident,
		arg.ToStage,
		arg.RootCause,
		arg.LessonsLearned,
		arg.IncidentID,
		arg.ExpectedVersion,
		arg.FromStage,
	)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Severity,
		&i.Stage,
		&i.Version,
		&i.CreatedBy,
		&i.AssignedAnalystID,
		&i.AssignedResponderID,
		&i.RootCause,
		&i.LessonsLearned,
		&i.DetectedAt,
		&i.TriagedAt,
		&i.ContainedAt,
		&i.EradicatedAt,
		&i.RecoveredAt,
		&i.PostmortemAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
