// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	AddEvidence(ctx context.Context, arg AddEvidenceParams) (Evidence, error)
	AddEvidenceNote(ctx context.Context, arg AddEvidenceNoteParams) (EvidenceNote, error)
	AddIncidentMember(ctx context.Context, arg AddIncidentMemberParams) error
	AssignIncidentPerson(ctx context.Context, arg AssignIncidentPersonParams) error
	CompleteIdempotentRequest(ctx context.Context, arg CompleteIdempotentRequestParams) error
	CountActionItemsAny(ctx context.Context, incidentID string) (bool, error)
	CountEvidence(ctx context.Context, incidentID string) (int32, error)
	CountOpenActionItems(ctx context.Context, incidentID string) (int32, error)
	CreateActionItem(ctx context.Context, arg CreateActionItemParams) (ActionItem, error)
	CreateIncident(ctx context.Context, arg CreateIncidentParams) (Incident, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	// Open, due items that have never had a dispatch for their CURRENT version.
	// The LEFT JOIN + NULL check is what stops an old schedule version from ever
	// reminding after a reschedule.
	DueActionItems(ctx context.Context, arg DueActionItemsParams) ([]ActionItem, error)
	GetActionItem(ctx context.Context, id string) (ActionItem, error)
	GetActionItemForUpdate(ctx context.Context, id string) (ActionItem, error)
	GetEvidence(ctx context.Context, id string) (Evidence, error)
	GetIdempotentRequest(ctx context.Context, requestID string) (IdempotentRequest, error)
	GetIncident(ctx context.Context, id string) (Incident, error)
	GetIncidentForUpdate(ctx context.Context, id string) (Incident, error)
	GetUser(ctx context.Context, id string) (User, error)
	InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error
	// Reserve a request id. If it already exists the caller replays the stored
	// response instead of executing the operation again.
	InsertIdempotentRequest(ctx context.Context, arg InsertIdempotentRequestParams) (int64, error)
	InsertRescheduleAudit(ctx context.Context, arg InsertRescheduleAuditParams) error
	InsertStageEvent(ctx context.Context, arg InsertStageEventParams) (StageEvent, error)
	IsIncidentMember(ctx context.Context, arg IsIncidentMemberParams) (bool, error)
	ListActionItems(ctx context.Context, incidentID string) ([]ActionItem, error)
	ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error)
	ListEvidence(ctx context.Context, incidentID string) ([]Evidence, error)
	ListEvidenceWithNotes(ctx context.Context, incidentID string) ([]ListEvidenceWithNotesRow, error)
	ListIncidentMembers(ctx context.Context, incidentID string) ([]User, error)
	ListIncidents(ctx context.Context, arg ListIncidentsParams) ([]Incident, error)
	ListIncidentsForExport(ctx context.Context) ([]Incident, error)
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error)
	ListStageEvents(ctx context.Context, incidentID string) ([]StageEvent, error)
	ListUsers(ctx context.Context) ([]User, error)
	MarkReminderDispatched(ctx context.Context, arg MarkReminderDispatchedParams) (int64, error)
	// Optimistic-locked reschedule. WHERE version = $3 makes a stale concurrent
	// reschedule lose, so no two schedules for the same version survive.
	RescheduleActionItem(ctx context.Context, arg RescheduleActionItemParams) (ActionItem, error)
	// Atomic forward transition. The WHERE clause enforces: expected version
	// (optimistic lock), exact current stage (no skipped transitions), and the
	// P1 triage gate. Returns the updated row; no row means the caller must
	// distinguish version mismatch from stage mismatch.
	TransitionIncident(ctx context.Context, arg TransitionIncidentParams) (Incident, error)
	UpdateActionItemStatus(ctx context.Context, arg UpdateActionItemStatusParams) (ActionItem, error)
}

var _ Querier = (*Queries)(nil)
