// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: audit.sql

package sqlcgen

import (
	"context"
)

const allAuditEntries = `-- name: AllAuditEntries :many
SELECT org_id, seq, actor_id, action, content, content_hash,
       prev_hash, entry_hash, created_at
FROM audit_entries WHERE org_id = $1
ORDER BY seq
`

// Full chain in order, for verification.
func (q *Queries) AllAuditEntries(ctx context.Context, orgID int64) ([]AuditEntry, error) {
	rows, err := q.db.Query(ctx, allAuditEntries, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEntry
	for rows.Next() {
		var i AuditEntry
		if err := rows.Scan(
			&i.OrgID,
			&i.Seq,
			&i.ActorID,
			&i.Action,
			&i.Content,
			&i.ContentHash,
			&i.PrevHash,
			&i.EntryHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAuditEntries = `-- name: CountAuditEntries :one
SELECT count(*) AS cnt, COALESCE(MAX(seq), 0)::bigint AS max_seq
FROM audit_entries WHERE org_id = $1
`

type CountAuditEntriesRow struct {
	Cnt    int64 `json:"cnt"`
	MaxSeq int64 `json:"max_seq"`
}

func (q *Queries) CountAuditEntries(ctx context.Context, orgID int64) (CountAuditEntriesRow, error) {
	row := q.db.QueryRow(ctx, countAuditEntries, orgID)
	var i CountAuditEntriesRow
	err := row.Scan(&i.Cnt, &i.MaxSeq)
	return i, err
}

const getAuditEntry = `-- name: GetAuditEntry :one
SELECT org_id, seq, actor_id, action, content, content_hash,
       prev_hash, entry_hash, created_at
FROM audit_entries WHERE org_id = $1 AND seq = $2
`

type GetAuditEntryParams struct {
	OrgID int64 `json:"org_id"`
	Seq   int64 `json:"seq"`
}

func (q *Queries) GetAuditEntry(ctx context.Context, arg GetAuditEntryParams) (AuditEntry, error) {
	row := q.db.QueryRow(ctx, getAuditEntry, arg.OrgID, arg.Seq)
	var i AuditEntry
	err := row.Scan(
		&i.OrgID,
		&i.Seq,
		&i.ActorID,
		&i.Action,
		&i.Content,
		&i.ContentHash,
		&i.PrevHash,
		&i.EntryHash,
		&i.CreatedAt,
	)
	return i, err
}

const insertAuditEntry = `-- name: InsertAuditEntry :exec
INSERT INTO audit_entries (
    org_id, seq, actor_id, action, content, content_hash, prev_hash, entry_hash
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertAuditEntryParams struct {
	OrgID       int64  `json:"org_id"`
	Seq         int64  `json:"seq"`
	ActorID     *int64 `json:"actor_id"`
	Action      string `json:"action"`
	Content     []byte `json:"content"`
	ContentHash string `json:"content_hash"`
	PrevHash    string `json:"prev_hash"`
	EntryHash   string `json:"entry_hash"`
}

func (q *Queries) InsertAuditEntry(ctx context.Context, arg InsertAuditEntryParams) error {
	_, err := q.db.Exec(ctx, insertAuditEntry,
		arg.OrgID,
		arg.Seq,
		arg.ActorID,
		arg.Action,
		arg.Content,
		arg.ContentHash,
		arg.PrevHash,
		arg.EntryHash,
	)
	return err
}

const listAuditEntries = `-- name: ListAuditEntries :many
SELECT org_id, seq, actor_id, action, content, content_hash,
       prev_hash, entry_hash, created_at
FROM audit_entries
WHERE org_id = $1 AND seq > $2
ORDER BY seq
LIMIT $3
`

type ListAuditEntriesParams struct {
	OrgID int64 `json:"org_id"`
	Seq   int64 `json:"seq"`
	Limit int32 `json:"limit"`
}

func (q *Queries) ListAuditEntries(ctx context.Context, arg ListAuditEntriesParams) ([]AuditEntry, error) {
	rows, err := q.db.Query(ctx, listAuditEntries, arg.OrgID, arg.Seq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEntry
	for rows.Next() {
		var i AuditEntry
		if err := rows.Scan(
			&i.OrgID,
			&i.Seq,
			&i.ActorID,
			&i.Action,
			&i.Content,
			&i.ContentHash,
			&i.PrevHash,
			&i.EntryHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxAuditSeq = `-- name: MaxAuditSeq :one
SELECT COALESCE(MAX(seq), 0)::bigint AS max_seq FROM audit_entries WHERE org_id = $1
`

func (q *Queries) MaxAuditSeq(ctx context.Context, orgID int64) (int64, error) {
	row := q.db.QueryRow(ctx, maxAuditSeq, orgID)
	var max_seq int64
	err := row.Scan(&max_seq)
	return max_seq, err
}

const takeAuditLock = `-- name: TakeAuditLock :exec
SELECT pg_advisory_xact_lock($1::int, $2::int)
`

type TakeAuditLockParams struct {
	Column1 int32 `json:"column_1"`
	Column2 int32 `json:"column_2"`
}

func (q *Queries) TakeAuditLock(ctx context.Context, arg TakeAuditLockParams) error {
	_, err := q.db.Exec(ctx, takeAuditLock, arg.Column1, arg.Column2)
	return err
}
