// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: catalog.sql

package sqlcgen

import (
	"context"
)

const createOrg = `-- name: CreateOrg :one
INSERT INTO organizations (slug, name, timezone)
VALUES ($1, $2, $3)
RETURNING id, slug, name, timezone, created_at
`

type CreateOrgParams struct {
	Slug     string `json:"slug"`
	Name     string `json:"name"`
	Timezone string `json:"timezone"`
}

func (q *Queries) CreateOrg(ctx context.Context, arg CreateOrgParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrg, arg.Slug, arg.Name, arg.Timezone)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Timezone,
		&i.CreatedAt,
	)
	return i, err
}

const createSource = `-- name: CreateSource :one
INSERT INTO sources (org_id, source_key, name)
VALUES ($1, $2, $3)
ON CONFLICT (org_id, source_key)
DO UPDATE SET name = EXCLUDED.name
RETURNING id, org_id, source_key, name, created_at
`

type CreateSourceParams struct {
	OrgID     int64  `json:"org_id"`
	SourceKey string `json:"source_key"`
	Name      string `json:"name"`
}

func (q *Queries) CreateSource(ctx context.Context, arg CreateSourceParams) (Source, error) {
	row := q.db.QueryRow(ctx, createSource, arg.OrgID, arg.SourceKey, arg.Name)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SourceKey,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, display_name)
VALUES ($1, $2)
ON CONFLICT (email) DO UPDATE SET display_name = EXCLUDED.display_name
RETURNING id, email, display_name, created_at
`

type CreateUserParams struct {
	Email       string `json:"email"`
	DisplayName string `json:"display_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const getExportPolicy = `-- name: GetExportPolicy :one
SELECT org_id, masked_fields, updated_at FROM export_policies WHERE org_id = $1
`

func (q *Queries) GetExportPolicy(ctx context.Context, orgID int64) (ExportPolicy, error) {
	row := q.db.QueryRow(ctx, getExportPolicy, orgID)
	var i ExportPolicy
	err := row.Scan(&i.OrgID, &i.MaskedFields, &i.UpdatedAt)
	return i, err
}

const getMembership = `-- name: GetMembership :one
SELECT org_id, user_id, role FROM memberships
WHERE org_id = $1 AND user_id = $2
`

type GetMembershipParams struct {
	OrgID  int64 `json:"org_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.OrgID, arg.UserID)
	var i Membership
	err := row.Scan(&i.OrgID, &i.UserID, &i.Role)
	return i, err
}

const getOrg = `-- name: GetOrg :one
SELECT id, slug, name, timezone FROM organizations WHERE slug = $1
`

type GetOrgRow struct {
	ID       int64  `json:"id"`
	Slug     string `json:"slug"`
	Name     string `json:"name"`
	Timezone string `json:"timezone"`
}

func (q *Queries) GetOrg(ctx context.Context, slug string) (GetOrgRow, error) {
	row := q.db.QueryRow(ctx, getOrg, slug)
	var i GetOrgRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Timezone,
	)
	return i, err
}

const getOrgByID = `-- name: GetOrgByID :one
SELECT id, slug, name, timezone FROM organizations WHERE id = $1
`

type GetOrgByIDRow struct {
	ID       int64  `json:"id"`
	Slug     string `json:"slug"`
	Name     string `json:"name"`
	Timezone string `json:"timezone"`
}

func (q *Queries) GetOrgByID(ctx context.Context, id int64) (GetOrgByIDRow, error) {
	row := q.db.QueryRow(ctx, getOrgByID, id)
	var i GetOrgByIDRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Timezone,
	)
	return i, err
}

const getSource = `-- name: GetSource :one
SELECT id, org_id, source_key, name, created_at
FROM sources WHERE org_id = $1 AND source_key = $2
`

type GetSourceParams struct {
	OrgID     int64  `json:"org_id"`
	SourceKey string `json:"source_key"`
}

func (q *Queries) GetSource(ctx context.Context, arg GetSourceParams) (Source, error) {
	row := q.db.QueryRow(ctx, getSource, arg.OrgID, arg.SourceKey)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SourceKey,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByTokenHash = `-- name: GetUserByTokenHash :one
SELECT u.id, u.email, u.display_name
FROM api_tokens t
JOIN users u ON u.id = t.user_id
WHERE t.token_hash = $1
`

type GetUserByTokenHashRow struct {
	ID          int64  `json:"id"`
	Email       string `json:"email"`
	DisplayName string `json:"display_name"`
}

func (q *Queries) GetUserByTokenHash(ctx context.Context, tokenHash string) (GetUserByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getUserByTokenHash, tokenHash)
	var i GetUserByTokenHashRow
	err := row.Scan(&i.ID, &i.Email, &i.DisplayName)
	return i, err
}

const insertToken = `-- name: InsertToken :exec
INSERT INTO api_tokens (user_id, token_hash, label)
VALUES ($1, $2, $3)
ON CONFLICT (token_hash) DO NOTHING
`

type InsertTokenParams struct {
	UserID    int64  `json:"user_id"`
	TokenHash string `json:"token_hash"`
	Label     string `json:"label"`
}

func (q *Queries) InsertToken(ctx context.Context, arg InsertTokenParams) error {
	_, err := q.db.Exec(ctx, insertToken, arg.UserID, arg.TokenHash, arg.Label)
	return err
}

const listOrgs = `-- name: ListOrgs :many
SELECT id, slug, name, timezone FROM organizations ORDER BY id
`

type ListOrgsRow struct {
	ID       int64  `json:"id"`
	Slug     string `json:"slug"`
	Name     string `json:"name"`
	Timezone string `json:"timezone"`
}

func (q *Queries) ListOrgs(ctx context.Context) ([]ListOrgsRow, error) {
	rows, err := q.db.Query(ctx, listOrgs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrgsRow
	for rows.Next() {
		var i ListOrgsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Timezone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSources = `-- name: ListSources :many
SELECT id, org_id, source_key, name, created_at
FROM sources WHERE org_id = $1 ORDER BY id
`

func (q *Queries) ListSources(ctx context.Context, orgID int64) ([]Source, error) {
	rows, err := q.db.Query(ctx, listSources, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Source
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.SourceKey,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertExportPolicy = `-- name: UpsertExportPolicy :one
INSERT INTO export_policies (org_id, masked_fields)
VALUES ($1, $2)
ON CONFLICT (org_id) DO UPDATE
  SET masked_fields = EXCLUDED.masked_fields, updated_at = now()
RETURNING org_id, masked_fields, updated_at
`

type UpsertExportPolicyParams struct {
	OrgID        int64    `json:"org_id"`
	MaskedFields []string `json:"masked_fields"`
}

func (q *Queries) UpsertExportPolicy(ctx context.Context, arg UpsertExportPolicyParams) (ExportPolicy, error) {
	row := q.db.QueryRow(ctx, upsertExportPolicy, arg.OrgID, arg.MaskedFields)
	var i ExportPolicy
	err := row.Scan(&i.OrgID, &i.MaskedFields, &i.UpdatedAt)
	return i, err
}

const upsertMembership = `-- name: UpsertMembership :exec
INSERT INTO memberships (org_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (org_id, user_id) DO UPDATE SET role = EXCLUDED.role
`

type UpsertMembershipParams struct {
	OrgID  int64  `json:"org_id"`
	UserID int64  `json:"user_id"`
	Role   string `json:"role"`
}

func (q *Queries) UpsertMembership(ctx context.Context, arg UpsertMembershipParams) error {
	_, err := q.db.Exec(ctx, upsertMembership, arg.OrgID, arg.UserID, arg.Role)
	return err
}
