// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: events.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const allocateRuleID = `-- name: AllocateRuleID :one
SELECT nextval('rules_id_seq')::bigint AS id
`

func (q *Queries) AllocateRuleID(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, allocateRuleID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const eventsInWindow = `-- name: EventsInWindow :many
SELECT id, org_id, source_id, source_key, event_id, db_user, occurred_at,
       action, schema_name, table_name, row_count, content_hash, received_at
FROM events
WHERE org_id = $1
  AND db_user = $2
  AND occurred_at >= $3
  AND occurred_at <  $4
ORDER BY occurred_at, id
`

type EventsInWindowParams struct {
	OrgID        int64              `json:"org_id"`
	DbUser       string             `json:"db_user"`
	OccurredAt   pgtype.Timestamptz `json:"occurred_at"`
	OccurredAt_2 pgtype.Timestamptz `json:"occurred_at_2"`
}

// Events of one source occurring inside a half-open time window [after, before).
func (q *Queries) EventsInWindow(ctx context.Context, arg EventsInWindowParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, eventsInWindow,
		arg.OrgID,
		arg.DbUser,
		arg.OccurredAt,
		arg.OccurredAt_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.SourceID,
			&i.SourceKey,
			&i.EventID,
			&i.DbUser,
			&i.OccurredAt,
			&i.Action,
			&i.SchemaName,
			&i.TableName,
			&i.RowCount,
			&i.ContentHash,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportEventsPage = `-- name: ExportEventsPage :many
SELECT id, org_id, source_id, source_key, event_id, db_user, occurred_at,
       action, schema_name, table_name, row_count, content_hash, received_at
FROM events
WHERE org_id = $1
  AND ($2::timestamptz IS NULL OR occurred_at >= $2)
  AND ($3::timestamptz IS NULL OR occurred_at <  $3)
  AND ($4::bigint = 0
       OR (occurred_at, id) < ($5::timestamptz, $6::bigint))
ORDER BY occurred_at DESC, id DESC
LIMIT $7
`

type ExportEventsPageParams struct {
	OrgID   int64              `json:"org_id"`
	Column2 pgtype.Timestamptz `json:"column_2"`
	Column3 pgtype.Timestamptz `json:"column_3"`
	Column4 int64              `json:"column_4"`
	Column5 pgtype.Timestamptz `json:"column_5"`
	Column6 int64              `json:"column_6"`
	Limit   int32              `json:"limit"`
}

// Keyset page for export: rows strictly before the (cursor_time, cursor_id)
// tuple, descending. First page passes cursor_id = 0.
func (q *Queries) ExportEventsPage(ctx context.Context, arg ExportEventsPageParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, exportEventsPage,
		arg.OrgID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.SourceID,
			&i.SourceKey,
			&i.EventID,
			&i.DbUser,
			&i.OccurredAt,
			&i.Action,
			&i.SchemaName,
			&i.TableName,
			&i.RowCount,
			&i.ContentHash,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCurrentRules = `-- name: GetCurrentRules :many
SELECT DISTINCT ON (id) id, org_id, version, kind, name, enabled, window_seconds, max_events, tables, hour_start, hour_end, config_json, created_by, created_at
FROM rules
WHERE org_id = $1 AND enabled = TRUE
ORDER BY id, version DESC
`

func (q *Queries) GetCurrentRules(ctx context.Context, orgID int64) ([]Rule, error) {
	rows, err := q.db.Query(ctx, getCurrentRules, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rule
	for rows.Next() {
		var i Rule
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Version,
			&i.Kind,
			&i.Name,
			&i.Enabled,
			&i.WindowSeconds,
			&i.MaxEvents,
			&i.Tables,
			&i.HourStart,
			&i.HourEnd,
			&i.ConfigJson,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, org_id, source_id, source_key, event_id, db_user, occurred_at,
       action, schema_name, table_name, row_count, content_hash, received_at
FROM events WHERE org_id = $1 AND id = $2
`

type GetEventByIDParams struct {
	OrgID int64 `json:"org_id"`
	ID    int64 `json:"id"`
}

func (q *Queries) GetEventByID(ctx context.Context, arg GetEventByIDParams) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByID, arg.OrgID, arg.ID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SourceID,
		&i.SourceKey,
		&i.EventID,
		&i.DbUser,
		&i.OccurredAt,
		&i.Action,
		&i.SchemaName,
		&i.TableName,
		&i.RowCount,
		&i.ContentHash,
		&i.ReceivedAt,
	)
	return i, err
}

const getEventBySourceEvent = `-- name: GetEventBySourceEvent :one
SELECT id, org_id, source_id, source_key, event_id, db_user, occurred_at,
       action, schema_name, table_name, row_count, content_hash, received_at
FROM events
WHERE source_id = $1 AND event_id = $2
`

type GetEventBySourceEventParams struct {
	SourceID int64  `json:"source_id"`
	EventID  string `json:"event_id"`
}

func (q *Queries) GetEventBySourceEvent(ctx context.Context, arg GetEventBySourceEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, getEventBySourceEvent, arg.SourceID, arg.EventID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SourceID,
		&i.SourceKey,
		&i.EventID,
		&i.DbUser,
		&i.OccurredAt,
		&i.Action,
		&i.SchemaName,
		&i.TableName,
		&i.RowCount,
		&i.ContentHash,
		&i.ReceivedAt,
	)
	return i, err
}

const getRuleVersion = `-- name: GetRuleVersion :one
SELECT id, org_id, version, kind, name, enabled, window_seconds, max_events, tables, hour_start, hour_end, config_json, created_by, created_at FROM rules WHERE org_id = $1 AND id = $2 AND version = $3
`

type GetRuleVersionParams struct {
	OrgID   int64 `json:"org_id"`
	ID      int64 `json:"id"`
	Version int32 `json:"version"`
}

func (q *Queries) GetRuleVersion(ctx context.Context, arg GetRuleVersionParams) (Rule, error) {
	row := q.db.QueryRow(ctx, getRuleVersion, arg.OrgID, arg.ID, arg.Version)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Version,
		&i.Kind,
		&i.Name,
		&i.Enabled,
		&i.WindowSeconds,
		&i.MaxEvents,
		&i.Tables,
		&i.HourStart,
		&i.HourEnd,
		&i.ConfigJson,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO events (
    org_id, source_id, source_key, event_id, db_user, occurred_at,
    action, schema_name, table_name, row_count, content_hash
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11
)
RETURNING id, org_id, source_id, source_key, event_id, db_user, occurred_at,
          action, schema_name, table_name, row_count, content_hash, received_at
`

type InsertEventParams struct {
	OrgID       int64              `json:"org_id"`
	SourceID    int64              `json:"source_id"`
	SourceKey   string             `json:"source_key"`
	EventID     string             `json:"event_id"`
	DbUser      string             `json:"db_user"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
	Action      string             `json:"action"`
	SchemaName  string             `json:"schema_name"`
	TableName   string             `json:"table_name"`
	RowCount    int64              `json:"row_count"`
	ContentHash string             `json:"content_hash"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, insertEvent,
		arg.OrgID,
		arg.SourceID,
		arg.SourceKey,
		arg.EventID,
		arg.DbUser,
		arg.OccurredAt,
		arg.Action,
		arg.SchemaName,
		arg.TableName,
		arg.RowCount,
		arg.ContentHash,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SourceID,
		&i.SourceKey,
		&i.EventID,
		&i.DbUser,
		&i.OccurredAt,
		&i.Action,
		&i.SchemaName,
		&i.TableName,
		&i.RowCount,
		&i.ContentHash,
		&i.ReceivedAt,
	)
	return i, err
}

const insertRule = `-- name: InsertRule :one
INSERT INTO rules (
    id, org_id, version, kind, name, enabled,
    window_seconds, max_events, tables, hour_start, hour_end, config_json, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, org_id, version, kind, name, enabled, window_seconds, max_events, tables, hour_start, hour_end, config_json, created_by, created_at
`

type InsertRuleParams struct {
	ID            int64    `json:"id"`
	OrgID         int64    `json:"org_id"`
	Version       int32    `json:"version"`
	Kind          string   `json:"kind"`
	Name          string   `json:"name"`
	Enabled       bool     `json:"enabled"`
	WindowSeconds int32    `json:"window_seconds"`
	MaxEvents     int32    `json:"max_events"`
	Tables        []string `json:"tables"`
	HourStart     int32    `json:"hour_start"`
	HourEnd       int32    `json:"hour_end"`
	ConfigJson    []byte   `json:"config_json"`
	CreatedBy     *int64   `json:"created_by"`
}

func (q *Queries) InsertRule(ctx context.Context, arg InsertRuleParams) (Rule, error) {
	row := q.db.QueryRow(ctx, insertRule,
		arg.ID,
		arg.OrgID,
		arg.Version,
		arg.Kind,
		arg.Name,
		arg.Enabled,
		arg.WindowSeconds,
		arg.MaxEvents,
		arg.Tables,
		arg.HourStart,
		arg.HourEnd,
		arg.ConfigJson,
		arg.CreatedBy,
	)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Version,
		&i.Kind,
		&i.Name,
		&i.Enabled,
		&i.WindowSeconds,
		&i.MaxEvents,
		&i.Tables,
		&i.HourStart,
		&i.HourEnd,
		&i.ConfigJson,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many
SELECT id, org_id, source_id, source_key, event_id, db_user, occurred_at,
       action, schema_name, table_name, row_count, content_hash, received_at
FROM events
WHERE org_id = $1
  AND ($3::timestamptz IS NULL OR occurred_at >= $3)
  AND ($4::timestamptz IS NULL OR occurred_at <  $4)
ORDER BY occurred_at DESC, id DESC
LIMIT $2
`

type ListEventsParams struct {
	OrgID    int64              `json:"org_id"`
	Limit    int32              `json:"limit"`
	FromTime pgtype.Timestamptz `json:"from_time"`
	ToTime   pgtype.Timestamptz `json:"to_time"`
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEvents,
		arg.OrgID,
		arg.Limit,
		arg.FromTime,
		arg.ToTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.SourceID,
			&i.SourceKey,
			&i.EventID,
			&i.DbUser,
			&i.OccurredAt,
			&i.Action,
			&i.SchemaName,
			&i.TableName,
			&i.RowCount,
			&i.ContentHash,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuleVersions = `-- name: ListRuleVersions :many
SELECT id, org_id, version, kind, name, enabled, window_seconds, max_events, tables, hour_start, hour_end, config_json, created_by, created_at FROM rules WHERE org_id = $1 AND id = $2 ORDER BY version DESC
`

type ListRuleVersionsParams struct {
	OrgID int64 `json:"org_id"`
	ID    int64 `json:"id"`
}

func (q *Queries) ListRuleVersions(ctx context.Context, arg ListRuleVersionsParams) ([]Rule, error) {
	rows, err := q.db.Query(ctx, listRuleVersions, arg.OrgID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rule
	for rows.Next() {
		var i Rule
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Version,
			&i.Kind,
			&i.Name,
			&i.Enabled,
			&i.WindowSeconds,
			&i.MaxEvents,
			&i.Tables,
			&i.HourStart,
			&i.HourEnd,
			&i.ConfigJson,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRules = `-- name: ListRules :many
SELECT DISTINCT ON (id) id, org_id, version, kind, name, enabled, window_seconds, max_events, tables, hour_start, hour_end, config_json, created_by, created_at
FROM rules
WHERE org_id = $1
ORDER BY id, version DESC
`

func (q *Queries) ListRules(ctx context.Context, orgID int64) ([]Rule, error) {
	rows, err := q.db.Query(ctx, listRules, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rule
	for rows.Next() {
		var i Rule
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Version,
			&i.Kind,
			&i.Name,
			&i.Enabled,
			&i.WindowSeconds,
			&i.MaxEvents,
			&i.Tables,
			&i.HourStart,
			&i.HourEnd,
			&i.ConfigJson,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextRuleVersion = `-- name: NextRuleVersion :one
SELECT COALESCE(MAX(version), 0) + 1 AS next_version
FROM rules WHERE org_id = $1 AND id = $2
`

type NextRuleVersionParams struct {
	OrgID int64 `json:"org_id"`
	ID    int64 `json:"id"`
}

func (q *Queries) NextRuleVersion(ctx context.Context, arg NextRuleVersionParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextRuleVersion, arg.OrgID, arg.ID)
	var next_version int32
	err := row.Scan(&next_version)
	return next_version, err
}
