// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Alert struct {
	ID          int64              `json:"id"`
	OrgID       int64              `json:"org_id"`
	RuleID      int64              `json:"rule_id"`
	RuleVersion int32              `json:"rule_version"`
	Kind        string             `json:"kind"`
	Status      string             `json:"status"`
	Fingerprint string             `json:"fingerprint"`
	WindowStart pgtype.Timestamptz `json:"window_start"`
	WindowEnd   pgtype.Timestamptz `json:"window_end"`
	DbUser      *string            `json:"db_user"`
	EventID     *string            `json:"event_id"`
	EventPk     *int64             `json:"event_pk"`
	EventCount  int32              `json:"event_count"`
	AssignedTo  *int64             `json:"assigned_to"`
	Version     int32              `json:"version"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type AlertEvent struct {
	AlertID int64 `json:"alert_id"`
	EventPk int64 `json:"event_pk"`
}

type AlertRevision struct {
	ID         int64              `json:"id"`
	AlertID    int64              `json:"alert_id"`
	Revision   string             `json:"revision"`
	FromStatus *string            `json:"from_status"`
	ToStatus   *string            `json:"to_status"`
	Note       string             `json:"note"`
	EventCount *int32             `json:"event_count"`
	ActorID    *int64             `json:"actor_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ApiToken struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	Label     string             `json:"label"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type AuditEntry struct {
	OrgID       int64              `json:"org_id"`
	Seq         int64              `json:"seq"`
	ActorID     *int64             `json:"actor_id"`
	Action      string             `json:"action"`
	Content     []byte             `json:"content"`
	ContentHash string             `json:"content_hash"`
	PrevHash    string             `json:"prev_hash"`
	EntryHash   string             `json:"entry_hash"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Event struct {
	ID          int64              `json:"id"`
	OrgID       int64              `json:"org_id"`
	SourceID    int64              `json:"source_id"`
	SourceKey   string             `json:"source_key"`
	EventID     string             `json:"event_id"`
	DbUser      string             `json:"db_user"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
	Action      string             `json:"action"`
	SchemaName  string             `json:"schema_name"`
	TableName   string             `json:"table_name"`
	RowCount    int64              `json:"row_count"`
	ContentHash string             `json:"content_hash"`
	ReceivedAt  pgtype.Timestamptz `json:"received_at"`
}

type ExportPolicy struct {
	OrgID        int64              `json:"org_id"`
	MaskedFields []string           `json:"masked_fields"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Membership struct {
	OrgID  int64  `json:"org_id"`
	UserID int64  `json:"user_id"`
	Role   string `json:"role"`
}

type Organization struct {
	ID        int64              `json:"id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	Timezone  string             `json:"timezone"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Rule struct {
	ID            int64              `json:"id"`
	OrgID         int64              `json:"org_id"`
	Version       int32              `json:"version"`
	Kind          string             `json:"kind"`
	Name          string             `json:"name"`
	Enabled       bool               `json:"enabled"`
	WindowSeconds int32              `json:"window_seconds"`
	MaxEvents     int32              `json:"max_events"`
	Tables        []string           `json:"tables"`
	HourStart     int32              `json:"hour_start"`
	HourEnd       int32              `json:"hour_end"`
	ConfigJson    []byte             `json:"config_json"`
	CreatedBy     *int64             `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Source struct {
	ID        int64              `json:"id"`
	OrgID     int64              `json:"org_id"`
	SourceKey string             `json:"source_key"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID          int64              `json:"id"`
	Email       string             `json:"email"`
	DisplayName string             `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
