# Generated by Django 5.0.14 on 2026-09-20 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('singleton_id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('taker_fee_rate', models.DecimalField(decimal_places=8, default='0.001', max_digits=10, verbose_name='taker费率')),
                ('maker_fee_rate', models.DecimalField(decimal_places=8, default='0.001', max_digits=10, verbose_name='maker费率')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='维护模式')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('BUY', '买入'), ('SELL', '卖出')], max_length=8, verbose_name='方向')),
                ('type', models.CharField(choices=[('LIMIT', '限价单'), ('MARKET', '市价单')], max_length=8, verbose_name='类型')),
                ('limit_price', models.DecimalField(blank=True, decimal_places=8, max_digits=36, null=True, verbose_name='限价')),
                ('orig_qty', models.DecimalField(decimal_places=8, max_digits=36, verbose_name='委托数量/预算')),
                ('filled_qty', models.DecimalField(decimal_places=8, default=0, max_digits=36, verbose_name='已成交(base)数量')),
                ('filled_quote', models.DecimalField(decimal_places=8, default=0, max_digits=36, verbose_name='已成交额(quote)')),
                ('remaining_frozen', models.DecimalField(decimal_places=8, default=0, max_digits=36, verbose_name='剩余冻结')),
                ('status', models.CharField(choices=[('NEW', '待成交'), ('PARTIALLY_FILLED', '部分成交'), ('FILLED', '已成交'), ('CANCELED', '已撤销/剩余取消')], default='NEW', max_length=16, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='frozen_orders', to='accounts.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, verbose_name='幂等键')),
                ('fingerprint', models.CharField(max_length=128, verbose_name='参数指纹')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='idem_keys', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='idem_keys', to='trading.order')),
            ],
            options={
                'verbose_name': '幂等键',
                'verbose_name_plural': '幂等键',
            },
        ),
        migrations.CreateModel(
            name='TradingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32, unique=True, verbose_name='交易对符号')),
                ('tick_size', models.DecimalField(decimal_places=8, default='0.01', max_digits=18, verbose_name='最小报价单位')),
                ('lot_size', models.DecimalField(decimal_places=8, default='0.000001', max_digits=18, verbose_name='最小下单数量')),
                ('min_notional', models.DecimalField(decimal_places=8, default='0', max_digits=18, verbose_name='最小下单金额')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pairs_as_base', to='accounts.asset')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pairs_as_quote', to='accounts.asset')),
            ],
            options={
                'verbose_name': '交易对',
                'verbose_name_plural': '交易对',
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=8, max_digits=36, verbose_name='成交价')),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=36, verbose_name='成交数量')),
                ('quote_amount', models.DecimalField(decimal_places=8, max_digits=36, verbose_name='成交额')),
                ('taker_fee', models.DecimalField(decimal_places=8, max_digits=36, verbose_name='taker手续费')),
                ('maker_fee', models.DecimalField(decimal_places=8, max_digits=36, verbose_name='maker手续费')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('maker_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maker_trades', to='trading.order')),
                ('taker_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taker_trades', to='trading.order')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trades', to='trading.tradingpair')),
            ],
            options={
                'verbose_name': '成交',
                'verbose_name_plural': '成交',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='trading.tradingpair'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=48, verbose_name='动作')),
                ('target', models.CharField(blank=True, default='', max_length=128, verbose_name='对象')),
                ('detail', models.TextField(blank=True, default='', verbose_name='详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'indexes': [models.Index(fields=['action', '-created_at'], name='trading_aud_action_5570d1_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='idempotencykey',
            constraint=models.UniqueConstraint(fields=('user', 'key'), name='uniq_user_idem_key'),
        ),
        migrations.AddConstraint(
            model_name='tradingpair',
            constraint=models.UniqueConstraint(fields=('base', 'quote'), name='uniq_base_quote'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['pair', '-id'], name='trading_tra_pair_id_e9dea2_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['pair', 'status', '-id'], name='trading_ord_pair_id_28d034_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='trading_ord_user_id_ca9b05_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('orig_qty__gt', 0)), name='chk_order_orig_qty'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('filled_qty__gte', 0)), name='chk_order_filled_qty'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('remaining_frozen__gte', 0)), name='chk_order_rem_frozen'),
        ),
    ]
