# Generated by Django 5.1.4 on 2026-09-20 16:31

import django.db.models.deletion
import sync.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_uuid', models.UUIDField(db_index=True, default=sync.models.new_record_uuid, unique=True)),
                ('status', models.CharField(choices=[('ok', 'Current'), ('conflict', 'Needs supervisor resolution'), ('deleted', 'Deleted')], default='ok', max_length=16)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_records', to=settings.AUTH_USER_MODEL)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='forms.crew')),
                ('current_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='forms.formtemplateversion')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='forms.project')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='forms.formtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='RecordRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField()),
                ('base_version', models.PositiveIntegerField(default=0)),
                ('data', models.JSONField()),
                ('content_hash', models.CharField(max_length=64)),
                ('collected_at', models.DateTimeField()),
                ('kind', models.CharField(choices=[('created', 'First accepted revision'), ('updated', 'Fast-forward update'), ('divergent', 'Concurrent edit (same base version, other content)'), ('stale', 'Older version than the current revision'), ('resolved', 'Supervisor resolution')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='sync.formrecord')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_revisions', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_revisions', to=settings.AUTH_USER_MODEL)),
                ('template_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='forms.formtemplateversion')),
            ],
            options={
                'ordering': ('record', 'seq'),
                'unique_together': {('record', 'content_hash'), ('record', 'seq')},
            },
        ),
        migrations.AddField(
            model_name='formrecord',
            name='conflict_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conflicting_revisions', to='sync.recordrevision'),
        ),
        migrations.AddField(
            model_name='formrecord',
            name='current_revision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sync.recordrevision'),
        ),
        migrations.CreateModel(
            name='SyncBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_batch_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry_count', models.PositiveIntegerField(default=0)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_batches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SyncResultEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_uuid', models.UUIDField()),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('conflict', 'Conflict'), ('rejected', 'Validation rejected'), ('error', 'Error')], max_length=16)),
                ('status_code', models.PositiveIntegerField()),
                ('record_version', models.PositiveIntegerField(blank=True, null=True)),
                ('revision_seq', models.PositiveIntegerField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('errors', models.JSONField(blank=True, null=True)),
                ('conflict_with_seq', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='sync.syncbatch')),
            ],
        ),
        migrations.CreateModel(
            name='RecordChange',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('change_type', models.CharField(choices=[('created', 'Record created'), ('updated', 'Record updated'), ('conflict', 'Conflicting revision stored'), ('resolved', 'Conflict resolved'), ('deleted', 'Tombstone')], max_length=16)),
                ('record_status', models.CharField(choices=[('ok', 'Current'), ('conflict', 'Needs supervisor resolution'), ('deleted', 'Deleted')], max_length=16)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='forms.crew')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='forms.project')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='sync.formrecord')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='forms.formtemplate')),
                ('revision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='sync.recordrevision')),
            ],
            options={
                'ordering': ('id',),
                'indexes': [models.Index(fields=['project', 'id'], name='sync_record_project_ccfc45_idx'), models.Index(fields=['crew', 'id'], name='sync_record_crew_id_4e1e9d_idx'), models.Index(fields=['record', 'id'], name='sync_record_record__12293f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='formrecord',
            index=models.Index(fields=['project', 'status'], name='sync_formre_project_22ea26_idx'),
        ),
        migrations.AddIndex(
            model_name='formrecord',
            index=models.Index(fields=['crew', 'status'], name='sync_formre_crew_id_a6c46e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='syncbatch',
            unique_together={('submitted_by', 'client_batch_id')},
        ),
        migrations.AddIndex(
            model_name='syncresultentry',
            index=models.Index(fields=['batch', 'client_uuid'], name='sync_syncre_batch_i_d9b26a_idx'),
        ),
    ]
