# Generated by Django 4.2.16 on 2026-09-21 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('publish', 'Publish'), ('delete', 'Delete'), ('experiment_start', 'Experiment start'), ('experiment_stop', 'Experiment stop')], max_length=32)),
                ('resource_type', models.CharField(help_text="e.g. 'app', 'placement', 'waterfall_version'.", max_length=64)),
                ('resource_id', models.CharField(max_length=64)),
                ('resource_repr', models.CharField(blank=True, default='', max_length=255)),
                ('diff', models.JSONField(blank=True, default=dict, help_text='Snapshot of changed fields / full payload for creates.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('developer', models.ForeignKey(blank=True, help_text='Who performed the action (null if the account was removed).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['resource_type', 'resource_id'], name='common_audi_resourc_5a13c4_idx'), models.Index(fields=['developer', '-created_at'], name='common_audi_develop_94afe6_idx')],
            },
        ),
    ]
