# Generated by Django 6.1.1 on 2026-09-20 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_key', models.CharField(max_length=200)),
                ('needs_analysis', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='conformance.project')),
            ],
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('done', 'Done'), ('failed', 'Failed')], max_length=20)),
                ('total', models.PositiveIntegerField(default=0)),
                ('inserted', models.PositiveIntegerField(default=0)),
                ('skipped', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='conformance.project')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=200)),
                ('activity', models.CharField(max_length=200)),
                ('occurred_at', models.DateTimeField()),
                ('seq', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='conformance.case')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='conformance.importbatch')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='conformance.project')),
            ],
            options={
                'ordering': ['case', 'seq'],
            },
        ),
        migrations.AddField(
            model_name='case',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='conformance.project'),
        ),
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('incremental', 'Incremental'), ('full', 'Full rebuild')], max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('cases_processed', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='conformance.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('analyst', 'Analyst'), ('admin', 'Admin')], default='analyst', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='conformance.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('definition', models.JSONField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='conformance.processtemplate')),
            ],
            options={
                'ordering': ['template', 'version'],
            },
        ),
        migrations.AddField(
            model_name='case',
            name='template_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='conformance.templateversion'),
        ),
        migrations.CreateModel(
            name='CaseAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('waiting', 'Waiting for missing events'), ('in_progress', 'In progress, conformant so far'), ('conformant', 'Conformant'), ('nonconformant', 'Nonconformant')], max_length=20)),
                ('missing_seqs', models.JSONField(default=list)),
                ('deviations', models.JSONField(default=list)),
                ('event_count', models.PositiveIntegerField(default=0)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='conformance.case')),
                ('run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='conformance.analysisrun')),
            ],
            options={
                'ordering': ['case', 'revision'],
                'constraints': [models.UniqueConstraint(fields=('case', 'revision'), name='uniq_analysis_case_revision')],
            },
        ),
        migrations.AddConstraint(
            model_name='processtemplate',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='uniq_template_project_name'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('project', 'event_id'), name='uniq_event_project_eid'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('case', 'seq'), name='uniq_event_case_seq'),
        ),
        migrations.AddConstraint(
            model_name='projectmembership',
            constraint=models.UniqueConstraint(fields=('user', 'project'), name='uniq_membership_user_project'),
        ),
        migrations.AddConstraint(
            model_name='templateversion',
            constraint=models.UniqueConstraint(fields=('template', 'version'), name='uniq_template_version'),
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.UniqueConstraint(fields=('project', 'case_key'), name='uniq_case_project_key'),
        ),
    ]
