//! Host-side input/output types and timing helpers.

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use sha2::{Digest as _, Sha256};
use shared::{encode_batch, JournalData};

/// On-disk example input format: `{"values": [..signed integers..]}`.
#[derive(Debug, Clone, Deserialize)]
pub struct InputFile {
    pub values: Vec<i32>,
}

/// Read an input JSON file from disk.
pub fn read_input(path: &str) -> Result<InputFile> {
    let raw = std::fs::read_to_string(path)
        .with_context(|| format!("failed to read input file `{path}`"))?;
    let input: InputFile =
        serde_json::from_str(&raw).with_context(|| format!("invalid input JSON in `{path}`"))?;
    Ok(input)
}

/// Hex-encode an image ID (`[u32; 8]` as generated by risc0-build) in the same
/// byte order a [`risc0_zkvm::Digest`] would expose, i.e. each word little
/// endian for 32 bytes total.
pub fn image_id_hex(image_id: [u32; 8]) -> String {
    let mut bytes = [0u8; 32];
    for (i, word) in image_id.iter().enumerate() {
        bytes[i * 4..i * 4 + 4].copy_from_slice(&word.to_le_bytes());
    }
    hex::encode(bytes)
}

/// Re-compute the SHA-256 input commitment exactly the way the guest does it:
/// SHA-256 over the shared canonical encoding. The guest uses the zkVM
/// accelerated SHA-256; both are standard FIPS 180-4 SHA-256, so the digests
/// must be identical for the same batch.
pub fn host_input_commitment(values: &[i32]) -> [u8; 32] {
    let mut hasher = Sha256::new();
    hasher.update(encode_batch(values));
    hasher.finalize().into()
}

/// Timings for the three distinct protocol phases, in milliseconds.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PhaseTimings {
    /// Run the guest in the executor only (trace generation, no STARK).
    pub execute_ms: u128,
    /// Generate the cryptographic receipt (STARK proving; zero-crypto in dev
    /// mode, which is always flagged).
    pub prove_ms: u128,
    /// Verify the receipt seal, image ID and journal binding on the host.
    pub verify_ms: u128,
}

/// Result returned to the caller *only after* the receipt and program ID have
/// been fully verified. Never constructed on a failed or dev-mode check.
#[derive(Debug, Clone, Serialize)]
pub struct VerifiedOutput {
    /// Whether this output is backed by a real cryptographic proof.
    /// Always `true`: callers receive this struct only post-verification;
    /// dev-mode receipts are rejected and an error returned instead.
    pub verified: bool,
    pub image_id: String,
    pub receipt_kind: String,
    pub seal_bytes: usize,
    pub length: u32,
    pub median: i32,
    pub input_commitment: String,
    pub timings: PhaseTimings,
    pub segments: usize,
    pub total_cycles: u64,
    pub user_cycles: u64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub receipt_path: Option<String>,
}

/// Convenience: decode the journal, re-check the input binding and length
/// against the batch the host actually sent. Returns the typed journal.
pub fn check_journal_binding(journal: &JournalData, values: &[i32]) -> Result<(), String> {
    if journal.length as usize != values.len() {
        return Err(format!(
            "journal length {} does not match input length {}",
            journal.length,
            values.len()
        ));
    }
    let recomputed = host_input_commitment(values);
    if journal.input_commitment != recomputed {
        return Err(
            "input commitment mismatch: journal is not bound to the supplied batch".to_string(),
        );
    }
    Ok(())
}
