//! Security-critical verification logic.
//!
//! The host MUST NOT return a "verified" result unless:
//! 1. the receipt inner is a real cryptographic seal (never `Fake`),
//! 2. verification runs with dev mode explicitly *disabled* (so a
//!    `RISC0_DEV_MODE=1` in the environment cannot downgrade checking),
//! 3. the receipt verifies against the expected program (image) ID, and
//! 4. the journal binds to the exact batch the host supplied and its length
//!    is consistent.

use anyhow::{anyhow, bail, Result};
use risc0_zkvm::{InnerReceipt, Receipt, VerifierContext};
use shared::JournalData;

use crate::io::check_journal_binding;

/// Human-readable name of the receipt's inner seal type.
pub fn receipt_kind_name(receipt: &Receipt) -> &'static str {
    match receipt.inner {
        InnerReceipt::Composite(_) => "composite",
        InnerReceipt::Succinct(_) => "succinct",
        InnerReceipt::Groth16(_) => "groth16",
        InnerReceipt::Fake(_) => "fake (dev-mode, NO cryptographic proof)",
        // InnerReceipt is #[non_exhaustive]; any unknown future arm is not a
        // known fake, so it is named conservatively and still must verify
        // cryptographically below.
        _ => "unknown",
    }
}

/// Returns `true` iff the receipt carries a development-only fake seal.
///
/// A fake receipt has zero cryptographic integrity: in dev mode its
/// "verification" is a pass-through. It must never be presented as a verified
/// result, regardless of any environment variable.
pub fn is_fake(receipt: &Receipt) -> bool {
    // `matches!` supplies its own wildcard arm, so this remains exhaustive
    // even though InnerReceipt is #[non_exhaustive].
    matches!(receipt.inner, InnerReceipt::Fake(_))
}

/// Fully verify a receipt and return the decoded journal.
///
/// * `expected_image_id` — the image ID of the program we intended to run
///   (`MEDIAN_GUEST_ID`, generated by risc0-build as `[u32; 8]`).
/// * `values` — the exact batch sent into the zkVM; the journal is checked to
///   bind to it.
///
/// Every failure is reported as an `Err`; this function never falls back to a
/// dev-mode accept.
pub fn verify_strict(
    receipt: &Receipt,
    expected_image_id: [u32; 8],
    values: &[i32],
) -> Result<JournalData> {
    // (1) Reject dev-mode fake receipts outright. Even with
    // RISC0_DEV_MODE=1 in the environment, a Fake seal is not a proof.
    if is_fake(receipt) {
        bail!(
            "REFUSED: receipt is a dev-mode FAKE receipt (InnerReceipt::Fake); \
             it carries no cryptographic proof and cannot be accepted as verified"
        );
    }

    // (2) Verify seal + image ID with dev mode forcibly disabled in the
    // verifier context, so ambient environment configuration cannot weaken
    // verification.
    let strict_ctx = VerifierContext::default().with_dev_mode(false);
    if let Err(err) = receipt.verify_with_context(&strict_ctx, expected_image_id) {
        bail!("receipt cryptographic/image-ID verification FAILED: {err}");
    }

    // (3) Decode the public journal.
    let journal: JournalData = receipt
        .journal
        .decode()
        .map_err(|err| anyhow!("journal decode FAILED: {err}"))?;

    // (4) Bind the journal to the actual batch and cross-check length.
    if let Err(msg) = check_journal_binding(&journal, values) {
        bail!("journal binding check FAILED: {msg}");
    }

    Ok(journal)
}
