# Generated by Django 5.0.14 on 2026-09-20 17:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=16, unique=True, verbose_name='资产符号')),
                ('name', models.CharField(blank=True, default='', max_length=64, verbose_name='名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '资产',
                'verbose_name_plural': '资产',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('USER', '用户'), ('FEE', '手续费账户'), ('FUNDING', '资金发行账户')], max_length=16, verbose_name='账户类型')),
                ('available', models.DecimalField(decimal_places=8, default=0, max_digits=36, verbose_name='可用余额')),
                ('frozen', models.DecimalField(decimal_places=8, default=0, max_digits=36, verbose_name='冻结余额')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='所属用户(系统账户挂保留 SYSTEM 用户)')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.asset', verbose_name='资产')),
            ],
            options={
                'verbose_name': '账户',
                'verbose_name_plural': '账户',
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_group', models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name='交易组')),
                ('seq', models.PositiveIntegerField(verbose_name='组内序号')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=36, verbose_name='带符号金额')),
                ('memo', models.CharField(max_length=64, verbose_name='摘要')),
                ('ref_type', models.CharField(max_length=32, verbose_name='关联类型')),
                ('ref_id', models.CharField(max_length=64, verbose_name='关联ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='accounts.account', verbose_name='账户')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.asset', verbose_name='资产')),
            ],
            options={
                'verbose_name': '账本分录',
                'verbose_name_plural': '账本分录',
            },
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('user', 'asset', 'account_type'), name='uniq_user_asset_type_account'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(check=models.Q(('account_type', 'FUNDING'), ('available__gte', 0), _connector='OR'), name='chk_available_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(check=models.Q(('account_type', 'FUNDING'), ('frozen__gte', 0), _connector='OR'), name='chk_frozen_nonneg'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['account', 'created_at'], name='accounts_le_account_a66391_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['ref_type', 'ref_id'], name='accounts_le_ref_typ_7c4005_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.UniqueConstraint(fields=('tx_group', 'seq'), name='uniq_ledger_group_seq'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(check=models.Q(('amount', 0), _negated=True), name='chk_ledger_amount_nonzero'),
        ),
    ]
