// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: anomaly.sql

package dbgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const createAnomalyRun = `-- name: CreateAnomalyRun :one
INSERT INTO anomaly_runs (kind, import_id)
VALUES ($1, $2)
RETURNING id, kind, import_id, created_at
`

type CreateAnomalyRunParams struct {
	Kind     string      `json:"kind"`
	ImportID pgtype.Text `json:"import_id"`
}

func (q *Queries) CreateAnomalyRun(ctx context.Context, arg CreateAnomalyRunParams) (AnomalyRun, error) {
	row := q.db.QueryRow(ctx, createAnomalyRun, arg.Kind, arg.ImportID)
	var i AnomalyRun
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ImportID,
		&i.CreatedAt,
	)
	return i, err
}

const listAnomalyHistoryScoped = `-- name: ListAnomalyHistoryScoped :many
SELECT e.id, e.run_id, r.kind AS run_kind, e.account_id, e.currency, e.cost_date,
       e.actual_amount, e.baseline_mean, e.baseline_std, e.threshold, e.status, e.created_at
FROM anomaly_evaluations e
JOIN anomaly_runs r ON r.id = e.run_id
JOIN accounts a ON a.id = e.account_id
WHERE a.org_id = ANY($1::uuid[])
  AND ($2::uuid IS NULL OR e.account_id = $2)
  AND ($3::char(3) IS NULL OR e.currency = $3)
  AND ($4::date IS NULL OR e.cost_date >= $4)
  AND ($5::date IS NULL OR e.cost_date <= $5)
ORDER BY e.cost_date DESC, a.id, e.created_at DESC
LIMIT 10000
`

type ListAnomalyHistoryScopedParams struct {
	Column1   []string    `json:"column_1"`
	AccountID pgtype.Text `json:"account_id"`
	Currency  pgtype.Text `json:"currency"`
	DateFrom  pgtype.Date `json:"date_from"`
	DateTo    pgtype.Date `json:"date_to"`
}

type ListAnomalyHistoryScopedRow struct {
	ID           string           `json:"id"`
	RunID        string           `json:"run_id"`
	RunKind      string           `json:"run_kind"`
	AccountID    string           `json:"account_id"`
	Currency     string           `json:"currency"`
	CostDate     time.Time        `json:"cost_date"`
	ActualAmount decimal.Decimal  `json:"actual_amount"`
	BaselineMean *decimal.Decimal `json:"baseline_mean"`
	BaselineStd  *decimal.Decimal `json:"baseline_std"`
	Threshold    *decimal.Decimal `json:"threshold"`
	Status       string           `json:"status"`
	CreatedAt    time.Time        `json:"created_at"`
}

// Full versioned history: old evaluations stay visible after late data changes a baseline.
func (q *Queries) ListAnomalyHistoryScoped(ctx context.Context, arg ListAnomalyHistoryScopedParams) ([]ListAnomalyHistoryScopedRow, error) {
	rows, err := q.db.Query(ctx, listAnomalyHistoryScoped,
		arg.Column1,
		arg.AccountID,
		arg.Currency,
		arg.DateFrom,
		arg.DateTo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAnomalyHistoryScopedRow
	for rows.Next() {
		var i ListAnomalyHistoryScopedRow
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.RunKind,
			&i.AccountID,
			&i.Currency,
			&i.CostDate,
			&i.ActualAmount,
			&i.BaselineMean,
			&i.BaselineStd,
			&i.Threshold,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestAnomalyAlertsScoped = `-- name: ListLatestAnomalyAlertsScoped :many
SELECT la.id, la.run_id, la.account_id, la.currency, la.cost_date,
       la.actual_amount, la.baseline_mean, la.baseline_std, la.threshold, la.created_at
FROM latest_anomaly_alerts la
JOIN accounts a ON a.id = la.account_id
WHERE a.org_id = ANY($1::uuid[])
  AND ($2::uuid IS NULL OR la.account_id = $2)
  AND ($3::char(3) IS NULL OR la.currency = $3)
  AND ($4::date IS NULL OR la.cost_date >= $4)
  AND ($5::date IS NULL OR la.cost_date <= $5)
ORDER BY la.cost_date DESC, la.account_id
`

type ListLatestAnomalyAlertsScopedParams struct {
	Column1   []string    `json:"column_1"`
	AccountID pgtype.Text `json:"account_id"`
	Currency  pgtype.Text `json:"currency"`
	DateFrom  pgtype.Date `json:"date_from"`
	DateTo    pgtype.Date `json:"date_to"`
}

func (q *Queries) ListLatestAnomalyAlertsScoped(ctx context.Context, arg ListLatestAnomalyAlertsScopedParams) ([]LatestAnomalyAlert, error) {
	rows, err := q.db.Query(ctx, listLatestAnomalyAlertsScoped,
		arg.Column1,
		arg.AccountID,
		arg.Currency,
		arg.DateFrom,
		arg.DateTo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LatestAnomalyAlert
	for rows.Next() {
		var i LatestAnomalyAlert
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.AccountID,
			&i.Currency,
			&i.CostDate,
			&i.ActualAmount,
			&i.BaselineMean,
			&i.BaselineStd,
			&i.Threshold,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
