// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: assets.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const getAssetByID = `-- name: GetAssetByID :one
SELECT id, project_id, rel_path, width, height, size_bytes, sha256, uploaded_by, created_at FROM assets WHERE id = $1
`

func (q *Queries) GetAssetByID(ctx context.Context, id uuid.UUID) (Asset, error) {
	row := q.db.QueryRow(ctx, getAssetByID, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RelPath,
		&i.Width,
		&i.Height,
		&i.SizeBytes,
		&i.Sha256,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getAssetByPath = `-- name: GetAssetByPath :one
SELECT id, project_id, rel_path, width, height, size_bytes, sha256, uploaded_by, created_at FROM assets
WHERE project_id = $1 AND rel_path = $2
`

type GetAssetByPathParams struct {
	ProjectID uuid.UUID
	RelPath   string
}

func (q *Queries) GetAssetByPath(ctx context.Context, arg GetAssetByPathParams) (Asset, error) {
	row := q.db.QueryRow(ctx, getAssetByPath, arg.ProjectID, arg.RelPath)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RelPath,
		&i.Width,
		&i.Height,
		&i.SizeBytes,
		&i.Sha256,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listAssets = `-- name: ListAssets :many
SELECT id, project_id, rel_path, width, height, size_bytes, sha256, uploaded_by, created_at FROM assets WHERE project_id = $1 ORDER BY rel_path
`

func (q *Queries) ListAssets(ctx context.Context, projectID uuid.UUID) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listAssets, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.RelPath,
			&i.Width,
			&i.Height,
			&i.SizeBytes,
			&i.Sha256,
			&i.UploadedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAsset = `-- name: UpsertAsset :one
INSERT INTO assets (project_id, rel_path, width, height, size_bytes, sha256, uploaded_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (project_id, rel_path) DO UPDATE
SET width       = EXCLUDED.width,
    height      = EXCLUDED.height,
    size_bytes  = EXCLUDED.size_bytes,
    sha256      = EXCLUDED.sha256,
    uploaded_by = EXCLUDED.uploaded_by,
    created_at  = now()
RETURNING id, project_id, rel_path, width, height, size_bytes, sha256, uploaded_by, created_at
`

type UpsertAssetParams struct {
	ProjectID  uuid.UUID
	RelPath    string
	Width      int32
	Height     int32
	SizeBytes  int64
	Sha256     string
	UploadedBy uuid.UUID
}

func (q *Queries) UpsertAsset(ctx context.Context, arg UpsertAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, upsertAsset,
		arg.ProjectID,
		arg.RelPath,
		arg.Width,
		arg.Height,
		arg.SizeBytes,
		arg.Sha256,
		arg.UploadedBy,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RelPath,
		&i.Width,
		&i.Height,
		&i.SizeBytes,
		&i.Sha256,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}
