// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: auth.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const authByAPIKeyHash = `-- name: AuthByAPIKeyHash :one
SELECT u.id, u.login, u.full_name, u.role,
       (SELECT COALESCE(array_agg(us.org_id ORDER BY us.org_id), '{}')
          FROM user_org_scopes us WHERE us.user_id = u.id)::uuid[] AS org_ids
FROM api_keys k
JOIN app_users u ON u.id = k.user_id
WHERE k.key_hash = $1 AND k.revoked_at IS NULL
`

type AuthByAPIKeyHashRow struct {
	ID       string   `json:"id"`
	Login    string   `json:"login"`
	FullName string   `json:"full_name"`
	Role     RoleKind `json:"role"`
	OrgIds   []string `json:"org_ids"`
}

func (q *Queries) AuthByAPIKeyHash(ctx context.Context, keyHash string) (AuthByAPIKeyHashRow, error) {
	row := q.db.QueryRow(ctx, authByAPIKeyHash, keyHash)
	var i AuthByAPIKeyHashRow
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.FullName,
		&i.Role,
		&i.OrgIds,
	)
	return i, err
}

const countAllImports = `-- name: CountAllImports :one
SELECT count(*) FROM cost_imports
`

func (q *Queries) CountAllImports(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllImports)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countImportsScoped = `-- name: CountImportsScoped :one
SELECT count(*) FROM cost_imports ci WHERE ci.org_id = ANY($1::uuid[])
`

func (q *Queries) CountImportsScoped(ctx context.Context, dollar_1 []string) (int64, error) {
	row := q.db.QueryRow(ctx, countImportsScoped, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createImport = `-- name: CreateImport :one
INSERT INTO cost_imports
    (org_id, user_id, filename, status, raw_row_count, row_count, error_line, error_code, error_message)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, org_id, user_id, filename, status, raw_row_count, row_count, error_line, error_code, error_message, created_at
`

type CreateImportParams struct {
	OrgID        pgtype.Text  `json:"org_id"`
	UserID       pgtype.Text  `json:"user_id"`
	Filename     string       `json:"filename"`
	Status       ImportStatus `json:"status"`
	RawRowCount  int32        `json:"raw_row_count"`
	RowCount     int32        `json:"row_count"`
	ErrorLine    pgtype.Int4  `json:"error_line"`
	ErrorCode    pgtype.Text  `json:"error_code"`
	ErrorMessage pgtype.Text  `json:"error_message"`
}

func (q *Queries) CreateImport(ctx context.Context, arg CreateImportParams) (CostImport, error) {
	row := q.db.QueryRow(ctx, createImport,
		arg.OrgID,
		arg.UserID,
		arg.Filename,
		arg.Status,
		arg.RawRowCount,
		arg.RowCount,
		arg.ErrorLine,
		arg.ErrorCode,
		arg.ErrorMessage,
	)
	var i CostImport
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Filename,
		&i.Status,
		&i.RawRowCount,
		&i.RowCount,
		&i.ErrorLine,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const getImportScoped = `-- name: GetImportScoped :one
SELECT ci.id, ci.org_id, ci.user_id, ci.filename, ci.status, ci.raw_row_count, ci.row_count, ci.error_line, ci.error_code, ci.error_message, ci.created_at FROM cost_imports ci
WHERE ci.id = $1 AND ci.org_id = ANY($2::uuid[])
`

type GetImportScopedParams struct {
	ID      string   `json:"id"`
	Column2 []string `json:"column_2"`
}

func (q *Queries) GetImportScoped(ctx context.Context, arg GetImportScopedParams) (CostImport, error) {
	row := q.db.QueryRow(ctx, getImportScoped, arg.ID, arg.Column2)
	var i CostImport
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Filename,
		&i.Status,
		&i.RawRowCount,
		&i.RowCount,
		&i.ErrorLine,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const listAllImports = `-- name: ListAllImports :many
SELECT id, org_id, user_id, filename, status, raw_row_count, row_count, error_line, error_code, error_message, created_at FROM cost_imports
ORDER BY created_at DESC, id DESC
LIMIT $1 OFFSET $2
`

type ListAllImportsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAllImports(ctx context.Context, arg ListAllImportsParams) ([]CostImport, error) {
	rows, err := q.db.Query(ctx, listAllImports, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CostImport
	for rows.Next() {
		var i CostImport
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.Filename,
			&i.Status,
			&i.RawRowCount,
			&i.RowCount,
			&i.ErrorLine,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportsScoped = `-- name: ListImportsScoped :many
SELECT ci.id, ci.org_id, ci.user_id, ci.filename, ci.status, ci.raw_row_count, ci.row_count, ci.error_line, ci.error_code, ci.error_message, ci.created_at FROM cost_imports ci
WHERE ci.org_id = ANY($1::uuid[])
ORDER BY ci.created_at DESC, ci.id DESC
LIMIT $2 OFFSET $3
`

type ListImportsScopedParams struct {
	Column1 []string `json:"column_1"`
	Limit   int32    `json:"limit"`
	Offset  int32    `json:"offset"`
}

func (q *Queries) ListImportsScoped(ctx context.Context, arg ListImportsScopedParams) ([]CostImport, error) {
	rows, err := q.db.Query(ctx, listImportsScoped, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CostImport
	for rows.Next() {
		var i CostImport
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.Filename,
			&i.Status,
			&i.RawRowCount,
			&i.RowCount,
			&i.ErrorLine,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setImportSucceeded = `-- name: SetImportSucceeded :exec
UPDATE cost_imports
SET status = 'succeeded', row_count = $2,
    error_line = NULL, error_code = NULL, error_message = NULL
WHERE id = $1
`

type SetImportSucceededParams struct {
	ID       string `json:"id"`
	RowCount int32  `json:"row_count"`
}

func (q *Queries) SetImportSucceeded(ctx context.Context, arg SetImportSucceededParams) error {
	_, err := q.db.Exec(ctx, setImportSucceeded, arg.ID, arg.RowCount)
	return err
}
