// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package dbgen

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Asset struct {
	ID         uuid.UUID
	ProjectID  uuid.UUID
	RelPath    string
	Width      int32
	Height     int32
	SizeBytes  int64
	Sha256     string
	UploadedBy uuid.UUID
	CreatedAt  pgtype.Timestamptz
}

type Composition struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	Name      string
	Width     int32
	Height    int32
	CreatedBy uuid.UUID
	CreatedAt pgtype.Timestamptz
}

type Frame struct {
	ID           uuid.UUID
	JobID        uuid.UUID
	FrameNo      int32
	Status       string
	Attempts     int32
	MaxAttempts  int32
	Generation   int64
	OutputSha256 string
	OutputSize   int64
	LastError    string
	LeasedBy     *string
	LeasedUntil  pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Job struct {
	ID         uuid.UUID
	VersionID  uuid.UUID
	ProjectID  uuid.UUID
	CreatedBy  uuid.UUID
	Priority   int32
	FrameStart int32
	FrameEnd   int32
	Status     string
	Error      string
	EnqueuedAt pgtype.Timestamptz
	StartedAt  pgtype.Timestamptz
	FinishedAt pgtype.Timestamptz
	CanceledBy *uuid.UUID
	CreatedAt  pgtype.Timestamptz
}

type Project struct {
	ID        uuid.UUID
	Name      string
	OwnerID   uuid.UUID
	CreatedAt pgtype.Timestamptz
}

type ProjectMember struct {
	ProjectID uuid.UUID
	UserID    uuid.UUID
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID         uuid.UUID
	Username   string
	Role       string
	ApiKeyHash string
	CreatedAt  pgtype.Timestamptz
}

type Version struct {
	ID             uuid.UUID
	CompositionID  uuid.UUID
	VersionNo      int64
	Manifest       []byte
	ManifestSha256 string
	CreatedBy      uuid.UUID
	CreatedAt      pgtype.Timestamptz
}

type VersionResource struct {
	VersionID uuid.UUID
	LayerID   string
	AssetID   uuid.UUID
	Sha256    string
}
