// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: summary.sql

package dbgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDailyAccountSlice = `-- name: DeleteDailyAccountSlice :exec

DELETE FROM daily_account_summary
WHERE cost_date BETWEEN $1 AND $2
  AND account_id = ANY($3::uuid[])
`

type DeleteDailyAccountSliceParams struct {
	CostDate   time.Time `json:"cost_date"`
	CostDate_2 time.Time `json:"cost_date_2"`
	Column3    []string  `json:"column_3"`
}

// ===== Incremental: delete affected slices =====
func (q *Queries) DeleteDailyAccountSlice(ctx context.Context, arg DeleteDailyAccountSliceParams) error {
	_, err := q.db.Exec(ctx, deleteDailyAccountSlice, arg.CostDate, arg.CostDate_2, arg.Column3)
	return err
}

const deleteDailyCostCenterSlice = `-- name: DeleteDailyCostCenterSlice :exec
DELETE FROM daily_cost_center_summary
WHERE cost_date BETWEEN $1 AND $2
  AND cost_center_id = ANY($3::uuid[])
`

type DeleteDailyCostCenterSliceParams struct {
	CostDate   time.Time `json:"cost_date"`
	CostDate_2 time.Time `json:"cost_date_2"`
	Column3    []string  `json:"column_3"`
}

func (q *Queries) DeleteDailyCostCenterSlice(ctx context.Context, arg DeleteDailyCostCenterSliceParams) error {
	_, err := q.db.Exec(ctx, deleteDailyCostCenterSlice, arg.CostDate, arg.CostDate_2, arg.Column3)
	return err
}

const deleteMonthlyAccountSlice = `-- name: DeleteMonthlyAccountSlice :exec
DELETE FROM monthly_account_summary
WHERE period = ANY($1::date[])
  AND account_id = ANY($2::uuid[])
`

type DeleteMonthlyAccountSliceParams struct {
	Column1 []time.Time `json:"column_1"`
	Column2 []string    `json:"column_2"`
}

func (q *Queries) DeleteMonthlyAccountSlice(ctx context.Context, arg DeleteMonthlyAccountSliceParams) error {
	_, err := q.db.Exec(ctx, deleteMonthlyAccountSlice, arg.Column1, arg.Column2)
	return err
}

const deleteMonthlyCostCenterSlice = `-- name: DeleteMonthlyCostCenterSlice :exec
DELETE FROM monthly_cost_center_summary
WHERE period = ANY($1::date[])
  AND cost_center_id = ANY($2::uuid[])
`

type DeleteMonthlyCostCenterSliceParams struct {
	Column1 []time.Time `json:"column_1"`
	Column2 []string    `json:"column_2"`
}

func (q *Queries) DeleteMonthlyCostCenterSlice(ctx context.Context, arg DeleteMonthlyCostCenterSliceParams) error {
	_, err := q.db.Exec(ctx, deleteMonthlyCostCenterSlice, arg.Column1, arg.Column2)
	return err
}

const listDailyAccountScoped = `-- name: ListDailyAccountScoped :many

SELECT s.account_id, s.currency, s.cost_date, s.total, s.row_count FROM daily_account_summary s
JOIN accounts a ON a.id = s.account_id
WHERE a.org_id = ANY($1::uuid[])
  AND ($2::uuid IS NULL OR s.account_id = $2)
  AND ($3::date IS NULL OR s.cost_date >= $3)
  AND ($4::date IS NULL OR s.cost_date <= $4)
  AND ($5::char(3) IS NULL OR s.currency = $5)
ORDER BY s.cost_date, s.account_id
`

type ListDailyAccountScopedParams struct {
	Column1   []string    `json:"column_1"`
	AccountID pgtype.Text `json:"account_id"`
	DateFrom  pgtype.Date `json:"date_from"`
	DateTo    pgtype.Date `json:"date_to"`
	Currency  pgtype.Text `json:"currency"`
}

// ===== Scoped reads =====
func (q *Queries) ListDailyAccountScoped(ctx context.Context, arg ListDailyAccountScopedParams) ([]DailyAccountSummary, error) {
	rows, err := q.db.Query(ctx, listDailyAccountScoped,
		arg.Column1,
		arg.AccountID,
		arg.DateFrom,
		arg.DateTo,
		arg.Currency,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailyAccountSummary
	for rows.Next() {
		var i DailyAccountSummary
		if err := rows.Scan(
			&i.AccountID,
			&i.Currency,
			&i.CostDate,
			&i.Total,
			&i.RowCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDailyCostCenterScoped = `-- name: ListDailyCostCenterScoped :many
SELECT s.cost_center_id, s.currency, s.cost_date, s.total, s.row_count FROM daily_cost_center_summary s
JOIN cost_centers cc ON cc.id = s.cost_center_id
WHERE cc.org_id = ANY($1::uuid[])
  AND ($2::uuid IS NULL OR s.cost_center_id = $2)
  AND ($3::date IS NULL OR s.cost_date >= $3)
  AND ($4::date IS NULL OR s.cost_date <= $4)
  AND ($5::char(3) IS NULL OR s.currency = $5)
ORDER BY s.cost_date, s.cost_center_id
`

type ListDailyCostCenterScopedParams struct {
	Column1      []string    `json:"column_1"`
	CostCenterID pgtype.Text `json:"cost_center_id"`
	DateFrom     pgtype.Date `json:"date_from"`
	DateTo       pgtype.Date `json:"date_to"`
	Currency     pgtype.Text `json:"currency"`
}

func (q *Queries) ListDailyCostCenterScoped(ctx context.Context, arg ListDailyCostCenterScopedParams) ([]DailyCostCenterSummary, error) {
	rows, err := q.db.Query(ctx, listDailyCostCenterScoped,
		arg.Column1,
		arg.CostCenterID,
		arg.DateFrom,
		arg.DateTo,
		arg.Currency,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailyCostCenterSummary
	for rows.Next() {
		var i DailyCostCenterSummary
		if err := rows.Scan(
			&i.CostCenterID,
			&i.Currency,
			&i.CostDate,
			&i.Total,
			&i.RowCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonthlyAccountScoped = `-- name: ListMonthlyAccountScoped :many
SELECT s.account_id, s.currency, s.period, s.total, s.row_count FROM monthly_account_summary s
JOIN accounts a ON a.id = s.account_id
WHERE a.org_id = ANY($1::uuid[])
  AND ($2::uuid IS NULL OR s.account_id = $2)
  AND ($3::date IS NULL OR s.period >= $3)
  AND ($4::date IS NULL OR s.period <= $4)
  AND ($5::char(3) IS NULL OR s.currency = $5)
ORDER BY s.period, s.account_id
`

type ListMonthlyAccountScopedParams struct {
	Column1   []string    `json:"column_1"`
	AccountID pgtype.Text `json:"account_id"`
	DateFrom  pgtype.Date `json:"date_from"`
	DateTo    pgtype.Date `json:"date_to"`
	Currency  pgtype.Text `json:"currency"`
}

func (q *Queries) ListMonthlyAccountScoped(ctx context.Context, arg ListMonthlyAccountScopedParams) ([]MonthlyAccountSummary, error) {
	rows, err := q.db.Query(ctx, listMonthlyAccountScoped,
		arg.Column1,
		arg.AccountID,
		arg.DateFrom,
		arg.DateTo,
		arg.Currency,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MonthlyAccountSummary
	for rows.Next() {
		var i MonthlyAccountSummary
		if err := rows.Scan(
			&i.AccountID,
			&i.Currency,
			&i.Period,
			&i.Total,
			&i.RowCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonthlyCostCenterScoped = `-- name: ListMonthlyCostCenterScoped :many
SELECT s.cost_center_id, s.currency, s.period, s.total, s.row_count FROM monthly_cost_center_summary s
JOIN cost_centers cc ON cc.id = s.cost_center_id
WHERE cc.org_id = ANY($1::uuid[])
  AND ($2::uuid IS NULL OR s.cost_center_id = $2)
  AND ($3::date IS NULL OR s.period >= $3)
  AND ($4::date IS NULL OR s.period <= $4)
  AND ($5::char(3) IS NULL OR s.currency = $5)
ORDER BY s.period, s.cost_center_id
`

type ListMonthlyCostCenterScopedParams struct {
	Column1      []string    `json:"column_1"`
	CostCenterID pgtype.Text `json:"cost_center_id"`
	DateFrom     pgtype.Date `json:"date_from"`
	DateTo       pgtype.Date `json:"date_to"`
	Currency     pgtype.Text `json:"currency"`
}

func (q *Queries) ListMonthlyCostCenterScoped(ctx context.Context, arg ListMonthlyCostCenterScopedParams) ([]MonthlyCostCenterSummary, error) {
	rows, err := q.db.Query(ctx, listMonthlyCostCenterScoped,
		arg.Column1,
		arg.CostCenterID,
		arg.DateFrom,
		arg.DateTo,
		arg.Currency,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MonthlyCostCenterSummary
	for rows.Next() {
		var i MonthlyCostCenterSummary
		if err := rows.Scan(
			&i.CostCenterID,
			&i.Currency,
			&i.Period,
			&i.Total,
			&i.RowCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const monthlyCostCenterTotalsForPeriod = `-- name: MonthlyCostCenterTotalsForPeriod :many

SELECT cost_center_id, currency, period, total, row_count
FROM monthly_cost_center_summary
WHERE period = $1
  AND cost_center_id = ANY($2::uuid[])
`

type MonthlyCostCenterTotalsForPeriodParams struct {
	Period  time.Time `json:"period"`
	Column2 []string  `json:"column_2"`
}

// ===== Budget evaluation: month totals by CC/currency/period slices =====
// All currency totals for given cost centers and one month (budget evaluation).
func (q *Queries) MonthlyCostCenterTotalsForPeriod(ctx context.Context, arg MonthlyCostCenterTotalsForPeriodParams) ([]MonthlyCostCenterSummary, error) {
	rows, err := q.db.Query(ctx, monthlyCostCenterTotalsForPeriod, arg.Period, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MonthlyCostCenterSummary
	for rows.Next() {
		var i MonthlyCostCenterSummary
		if err := rows.Scan(
			&i.CostCenterID,
			&i.Currency,
			&i.Period,
			&i.Total,
			&i.RowCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recomputeDailyAccount = `-- name: RecomputeDailyAccount :exec

INSERT INTO daily_account_summary (account_id, currency, cost_date, total, row_count)
SELECT c.account_id, c.currency, c.cost_date, SUM(c.amount), COUNT(*)
FROM costs c
WHERE c.cost_date BETWEEN $1 AND $2
  AND c.account_id = ANY($3::uuid[])
GROUP BY c.account_id, c.currency, c.cost_date
`

type RecomputeDailyAccountParams struct {
	CostDate   time.Time `json:"cost_date"`
	CostDate_2 time.Time `json:"cost_date_2"`
	Column3    []string  `json:"column_3"`
}

// ===== Recompute aggregates from raw costs (restricted to affected accounts) =====
func (q *Queries) RecomputeDailyAccount(ctx context.Context, arg RecomputeDailyAccountParams) error {
	_, err := q.db.Exec(ctx, recomputeDailyAccount, arg.CostDate, arg.CostDate_2, arg.Column3)
	return err
}

const recomputeDailyCostCenter = `-- name: RecomputeDailyCostCenter :exec
INSERT INTO daily_cost_center_summary (cost_center_id, currency, cost_date, total, row_count)
SELECT a.cost_center_id, c.currency, c.cost_date, SUM(c.amount), COUNT(*)
FROM costs c JOIN accounts a ON a.id = c.account_id
WHERE c.cost_date BETWEEN $1 AND $2
  AND c.account_id = ANY($3::uuid[])
GROUP BY a.cost_center_id, c.currency, c.cost_date
`

type RecomputeDailyCostCenterParams struct {
	CostDate   time.Time `json:"cost_date"`
	CostDate_2 time.Time `json:"cost_date_2"`
	Column3    []string  `json:"column_3"`
}

func (q *Queries) RecomputeDailyCostCenter(ctx context.Context, arg RecomputeDailyCostCenterParams) error {
	_, err := q.db.Exec(ctx, recomputeDailyCostCenter, arg.CostDate, arg.CostDate_2, arg.Column3)
	return err
}

const recomputeMonthlyAccount = `-- name: RecomputeMonthlyAccount :exec
INSERT INTO monthly_account_summary (account_id, currency, period, total, row_count)
SELECT c.account_id, c.currency, date_trunc('month', c.cost_date)::date, SUM(c.amount), COUNT(*)
FROM costs c
WHERE c.cost_date BETWEEN $1 AND $2
  AND c.account_id = ANY($3::uuid[])
GROUP BY c.account_id, c.currency, date_trunc('month', c.cost_date)::date
`

type RecomputeMonthlyAccountParams struct {
	CostDate   time.Time `json:"cost_date"`
	CostDate_2 time.Time `json:"cost_date_2"`
	Column3    []string  `json:"column_3"`
}

func (q *Queries) RecomputeMonthlyAccount(ctx context.Context, arg RecomputeMonthlyAccountParams) error {
	_, err := q.db.Exec(ctx, recomputeMonthlyAccount, arg.CostDate, arg.CostDate_2, arg.Column3)
	return err
}

const recomputeMonthlyCostCenter = `-- name: RecomputeMonthlyCostCenter :exec
INSERT INTO monthly_cost_center_summary (cost_center_id, currency, period, total, row_count)
SELECT a.cost_center_id, c.currency, date_trunc('month', c.cost_date)::date,
       SUM(c.amount), COUNT(*)
FROM costs c JOIN accounts a ON a.id = c.account_id
WHERE c.cost_date BETWEEN $1 AND $2
  AND c.account_id = ANY($3::uuid[])
GROUP BY a.cost_center_id, c.currency, date_trunc('month', c.cost_date)::date
`

type RecomputeMonthlyCostCenterParams struct {
	CostDate   time.Time `json:"cost_date"`
	CostDate_2 time.Time `json:"cost_date_2"`
	Column3    []string  `json:"column_3"`
}

func (q *Queries) RecomputeMonthlyCostCenter(ctx context.Context, arg RecomputeMonthlyCostCenterParams) error {
	_, err := q.db.Exec(ctx, recomputeMonthlyCostCenter, arg.CostDate, arg.CostDate_2, arg.Column3)
	return err
}

const truncateSummaries = `-- name: TruncateSummaries :exec

TRUNCATE daily_account_summary,
          monthly_account_summary,
          daily_cost_center_summary,
          monthly_cost_center_summary
`

// ===== Rebuild: wipe all derived data =====
func (q *Queries) TruncateSummaries(ctx context.Context) error {
	_, err := q.db.Exec(ctx, truncateSummaries)
	return err
}
