package engine

import (
	"os"
	"reflect"
	"testing"

	"causal-broadcast/internal/vec"
)

// assertCausal verifies, per node, that every delivery is causally legal:
// before delivering m, all non-self dependencies and the same-origin
// predecessor must already appear earlier in that node's delivery list.
func assertCausal(t *testing.T, r *Response) {
	t.Helper()
	seen := map[string]map[vec.Key]bool{}
	for _, id := range r.Nodes {
		seen[id] = map[vec.Key]bool{}
	}
	for _, d := range r.Deliveries {
		s := seen[d.Node]
		for _, dep := range depsOf(r, d.Origin) {
			if dep.Node == d.Origin.Node {
				continue
			}
			if !s[dep] {
				t.Fatalf("CAUSAL VIOLATION node=%s delivered %s before dependency %s",
					d.Node, d.Origin, dep)
			}
		}
		pred := vec.Key{Node: d.Origin.Node, Seq: d.Origin.Seq - 1}
		if pred.Seq > 0 && !s[pred] {
			t.Fatalf("CAUSAL VIOLATION node=%s delivered %s before predecessor %s",
				d.Node, d.Origin, pred)
		}
		s[d.Origin] = true
	}
}

// depsOf reconstructs the dependency vector from the first delivery record
// of an origin (its clock_after minus itself equals its causal past).
func depsOf(r *Response, k vec.Key) []vec.Key {
	for _, d := range r.Deliveries {
		if d.Origin == k && d.Node == k.Node {
			out := []vec.Key{}
			for n, max := range d.Clock {
				for s := 1; s <= max; s++ {
					kk := vec.Key{Node: n, Seq: s}
					if kk != k {
						out = append(out, kk)
					}
				}
			}
			return out
		}
	}
	return nil
}

func deliveriesAt(r *Response, node string) []vec.Key {
	var out []vec.Key
	for _, d := range r.Deliveries {
		if d.Node == node {
			out = append(out, d.Origin)
		}
	}
	return out
}

func baseReq() *Request {
	return &Request{
		Seed:      1,
		Nodes:     []string{"n1", "n2", "n3"},
		EndTimeMs: 100,
		Network:   PolicyNoFaults(),
	}
}

// TestAcceptChainBufferRelease: chain generated by a trigger; n3 receives the
// root very late (30ms); the child must never deliver at n3 before the root,
// and after release both land in causal order.
func TestAcceptChainBufferRelease(t *testing.T) {
	req := baseReq()
	req.Topology = map[string][]string{
		"n1": {"n2", "n3"}, "n2": {"n3"}, "n3": {},
	}
	req.Faults = faultList{
		{origin: "n1", seq: 1, from: "n1", to: "n3", action: "delay", delayMs: 30},
		{origin: "n1", seq: 1, from: "n2", to: "n3", action: "delay", delayMs: 30},
		{origin: "n1", seq: 1, from: "n1", to: "n2", action: "deliver", delayMs: 2},
	}.toFaults()
	req.Broadcasts = []BroadcastSpec{{AtMs: 0, Node: "n1", Payload: "root"}}
	req.Triggers = []TriggerSpec{
		{WhenNode: "n2", AfterOrigin: vec.Key{Node: "n1", Seq: 1}, Payload: "child"},
	}
	r := Run(req)
	if r.Status != "ok" {
		t.Fatalf("run error: %s", r.Error)
	}
	assertCausal(t, r)

	n3 := deliveriesAt(r, "n3")
	if len(n3) != 2 || n3[0] != (vec.Key{Node: "n1", Seq: 1}) || n3[1] != (vec.Key{Node: "n2", Seq: 1}) {
		t.Fatalf("n3 delivery order wrong: %v", n3)
	}
	// Root arrived at t=30 at n3; child released in the same or a later event.
	var rootT, childT int64
	for _, d := range r.Deliveries {
		switch d.Origin {
		case vec.Key{Node: "n1", Seq: 1}:
			if d.Node == "n3" {
				rootT = d.Time
			}
		case vec.Key{Node: "n2", Seq: 1}:
			if d.Node == "n3" {
				childT = d.Time
			}
		}
	}
	if rootT != 30 || childT < 30 {
		t.Fatalf("release timing root=%d child=%d", rootT, childT)
	}
	if len(r.Final.RootMissingBlockers) != 0 {
		t.Fatalf("unexpected missing blockers: %v", r.Final.RootMissingBlockers)
	}
}

// TestAcceptConcurrentReorderDuplicate: two independent broadcasts cross; n3
// receives n2's before n1's (20ms reorder) and n4 gets a duplicated copy.
// Delivery must stay causal and duplicates are suppressed.
func TestAcceptConcurrentReorderDuplicate(t *testing.T) {
	req := &Request{
		Seed:      7,
		Nodes:     []string{"n1", "n2", "n3", "n4"},
		EndTimeMs: 100,
		Topology: map[string][]string{
			"n1": {"n3", "n4"}, "n2": {"n3", "n4"}, "n3": {}, "n4": {},
		},
		Network: PolicyNoFaults(),
		Faults: faultList{
			{origin: "n1", seq: 1, from: "n1", to: "n3", action: "delay", delayMs: 20},
			{origin: "n2", seq: 1, from: "n2", to: "n3", action: "deliver", delayMs: 2},
			{origin: "n2", seq: 1, from: "n2", to: "n4", action: "duplicate", delayMs: 5},
		}.toFaults(),
		Broadcasts: []BroadcastSpec{
			{AtMs: 0, Node: "n1", Payload: "a"},
			{AtMs: 0, Node: "n2", Payload: "b"},
		},
	}
	r := Run(req)
	if r.Status != "ok" {
		t.Fatal(r.Error)
	}
	assertCausal(t, r)

	n3 := deliveriesAt(r, "n3")
	if len(n3) != 2 || n3[0] != (vec.Key{Node: "n2", Seq: 1}) || n3[1] != (vec.Key{Node: "n1", Seq: 1}) {
		t.Fatalf("expected reordered concurrent delivery n2:1 then n1:1, got %v", n3)
	}
	if r.Duplicates["n4"] == 0 {
		t.Fatal("n4 should have suppressed a duplicated copy")
	}
	count := map[vec.Key]int{}
	for _, d := range r.Deliveries {
		if d.Node == "n4" {
			count[d.Origin]++
		}
	}
	for k, c := range count {
		if c != 1 {
			t.Fatalf("n4 delivered %s %d times", k, c)
		}
	}
}

// TestAcceptLossThenRepair: first-hop copies to n2/n3 are dropped; they hold
// nothing until the explicit retransmit at t=40, then both deliver. Verifies
// "前驱补齐后释放" across an actual loss.
func TestAcceptLossThenRepair(t *testing.T) {
	req := baseReq()
	req.Topology = map[string][]string{
		"n1": {"n2", "n3"}, "n2": {}, "n3": {},
	}
	req.Faults = faultList{
		{origin: "n1", seq: 1, from: "n1", to: "n2", action: "drop"},
		{origin: "n1", seq: 1, from: "n1", to: "n3", action: "drop"},
	}.toFaults()
	req.Broadcasts = []BroadcastSpec{{AtMs: 0, Node: "n1", Payload: "x"}}
	req.Retransmits = []RetransmitSpec{
		{AtMs: 40, From: "n1", FromOrigin: vec.Key{Node: "n1", Seq: 1}, To: []string{"n2", "n3"}, DelayMs: 2},
	}
	r := Run(req)
	if r.Status != "ok" {
		t.Fatal(r.Error)
	}
	assertCausal(t, r)
	for _, id := range []string{"n2", "n3"} {
		got := deliveriesAt(r, id)
		if len(got) != 1 || got[0] != (vec.Key{Node: "n1", Seq: 1}) {
			t.Fatalf("%s deliveries %v", id, got)
		}
	}
	var t42 int
	for _, d := range r.Deliveries {
		if d.Node != "n1" {
			if d.Time != 42 {
				t.Fatalf("repair delivery at %d, want 42", d.Time)
			}
			t42++
		}
	}
	if t42 != 2 {
		t.Fatalf("expected 2 repaired deliveries at t=42, got %d", t42)
	}
}

// TestAcceptPermanentLossDiagnostics: within end_time_ms n3 never receives
// n1:1 (delayed beyond window) and buffers n1:2; n1:3 is dropped to all
// receivers. Diagnostics must identify the buffer gap and the root blocker.
func TestAcceptPermanentLossDiagnostics(t *testing.T) {
	req := baseReq()
	req.Topology = map[string][]string{
		"n1": {"n2", "n3"}, "n2": {"n3"}, "n3": {},
	}
	req.Faults = faultList{
		{origin: "n1", seq: 1, from: "n1", to: "n3", action: "delay", delayMs: 500},
		{origin: "n1", seq: 1, from: "n2", to: "n3", action: "drop"},
		{origin: "n1", seq: 2, from: "n1", to: "n2", action: "deliver", delayMs: 2},
		{origin: "n1", seq: 2, from: "n1", to: "n3", action: "deliver", delayMs: 3},
		{origin: "n1", seq: 3, from: "n1", to: "n2", action: "drop"},
		{origin: "n1", seq: 3, from: "n1", to: "n3", action: "drop"},
	}.toFaults()
	req.Broadcasts = []BroadcastSpec{
		{AtMs: 0, Node: "n1", Payload: "late"},
		{AtMs: 1, Node: "n1", Payload: "held"},
		{AtMs: 2, Node: "n1", Payload: "gone"},
	}
	r := Run(req)
	if r.Status != "ok" {
		t.Fatal(r.Error)
	}
	assertCausal(t, r)

	buf := r.Final.BufferedPerNode["n3"]
	if len(buf) != 1 || buf[0] != (vec.Key{Node: "n1", Seq: 2}) {
		t.Fatalf("n3 should buffer n1:2, got %v", buf)
	}
	miss := r.Final.MissingForBuffered["n3"]["n1:2"]
	if len(miss) != 1 || miss[0] != (vec.Key{Node: "n1", Seq: 1}) {
		t.Fatalf("n3 buffered n1:2 should wait on n1:1, got %v", miss)
	}
	roots := r.Final.RootMissingBlockers
	if len(roots) != 1 || roots[0] != (vec.Key{Node: "n1", Seq: 3}) {
		t.Fatalf("root blocker should be n1:3, got %v", roots)
	}
	if len(r.Final.Diagnostics) == 0 {
		t.Fatal("expected human-readable diagnostics")
	}
}

// TestAcceptBackpressure: cap=1 at n2; n1:1 delayed to t=40, n1:2 and n1:3
// arrive early. Backpressure events must fire, causality must hold, and with
// unlimited retry everything eventually flushes in order.
func TestAcceptBackpressure(t *testing.T) {
	req := baseReq()
	req.BufferCapacity = 1
	req.Topology = map[string][]string{
		"n1": {"n2", "n3"}, "n2": {}, "n3": {},
	}
	req.Faults = faultList{
		{origin: "n1", seq: 1, from: "n1", to: "n2", action: "deliver", delayMs: 40},
		{origin: "n1", seq: 2, from: "n1", to: "n2", action: "deliver", delayMs: 5},
		{origin: "n1", seq: 3, from: "n1", to: "n2", action: "deliver", delayMs: 8},
	}.toFaults()
	req.Broadcasts = []BroadcastSpec{
		{AtMs: 0, Node: "n1", Payload: "1"},
		{AtMs: 1, Node: "n1", Payload: "2"},
		{AtMs: 2, Node: "n1", Payload: "3"},
	}
	req.BackpressureRetry = BackpressureRetryCfg{DelayMs: 5, MaxAttempts: -1}
	r := Run(req)
	if r.Status != "ok" {
		t.Fatal(r.Error)
	}
	if len(r.Backpressure) == 0 {
		t.Fatal("expected backpressure events")
	}
	assertCausal(t, r)
	n2 := deliveriesAt(r, "n2")
	want := []vec.Key{{Node: "n1", Seq: 1}, {Node: "n1", Seq: 2}, {Node: "n1", Seq: 3}}
	if len(n2) != 3 {
		t.Fatalf("n2 deliveries %v", n2)
	}
	for i := range want {
		if n2[i] != want[i] {
			t.Fatalf("n2 order %v want %v", n2, want)
		}
	}
}

// TestBackpressureGiveUp: with retries disabled (default), rejected copies
// are given up; the missed message is reported as undelivered, causal order
// for the rest still intact.
func TestBackpressureGiveUp(t *testing.T) {
	req := baseReq()
	req.BufferCapacity = 1
	req.Topology = map[string][]string{
		"n1": {"n2", "n3"}, "n2": {}, "n3": {},
	}
	req.Faults = faultList{
		{origin: "n1", seq: 1, from: "n1", to: "n2", action: "deliver", delayMs: 40},
		{origin: "n1", seq: 2, from: "n1", to: "n2", action: "deliver", delayMs: 5},
		{origin: "n1", seq: 3, from: "n1", to: "n2", action: "deliver", delayMs: 8},
	}.toFaults()
	req.Broadcasts = []BroadcastSpec{
		{AtMs: 0, Node: "n1", Payload: "1"},
		{AtMs: 1, Node: "n1", Payload: "2"},
		{AtMs: 2, Node: "n1", Payload: "3"},
	}
	r := Run(req)
	if r.Status != "ok" {
		t.Fatal(r.Error)
	}
	assertCausal(t, r)
	if len(r.Retries) == 0 || r.Retries[0].Result != "given_up" {
		t.Fatalf("expected given_up retry event, got %+v", r.Retries)
	}
	// n1:1 arrives at 40 and releases the buffered n1:2; the rejected n1:3
	// (retries disabled) is the one permanently missing at n2 — order of the
	// rest stayed intact.
	n2 := deliveriesAt(r, "n2")
	want := []vec.Key{{Node: "n1", Seq: 1}, {Node: "n1", Seq: 2}}
	if len(n2) != 2 || n2[0] != want[0] || n2[1] != want[1] {
		t.Fatalf("n2 deliveries %v, want %v", n2, want)
	}
	var missing3 bool
	for _, k := range r.Final.UndeliveredOrigins {
		if k == (vec.Key{Node: "n1", Seq: 3}) {
			missing3 = true
		}
	}
	if !missing3 {
		t.Fatal("given-up n1:3 should appear in undelivered_origins")
	}
}

// TestDeterminism: identical requests replay byte-identically.
func TestDeterminism(t *testing.T) {
	build := func() *Request {
		req := &Request{
			Seed:      555,
			Nodes:     []string{"a", "b", "c", "d"},
			EndTimeMs: 200,
			Network:   PolicyRandom(0.2, 0.15, 1, 9),
			Broadcasts: []BroadcastSpec{
				{AtMs: 0, Node: "a", Payload: "x"},
				{AtMs: 3, Node: "b", Payload: "y"},
			},
		}
		return req
	}
	r1 := Run(build())
	r2 := Run(build())
	if len(r1.Deliveries) != len(r2.Deliveries) {
		t.Fatal("delivery length differs")
	}
	for i := range r1.Deliveries {
		if !reflect.DeepEqual(r1.Deliveries[i], r2.Deliveries[i]) {
			t.Fatalf("delivery %d differs:\n%+v\n%+v", i, r1.Deliveries[i], r2.Deliveries[i])
		}
	}
	if len(r1.NetworkDecisions) != len(r2.NetworkDecisions) {
		t.Fatal("network decisions diverge in length")
	}
	for i := range r1.NetworkDecisions {
		if r1.NetworkDecisions[i] != r2.NetworkDecisions[i] {
			t.Fatalf("decision %d diverges", i)
		}
	}
}

// TestExampleFilesRun: every shipped JSON sample is a valid, successful run.
func TestExampleFilesRun(t *testing.T) {
	files := []string{
		"../../examples/01-chain-buffer-release.json",
		"../../examples/02-concurrent-reorder-dup.json",
		"../../examples/03-loss-repair.json",
		"../../examples/04-backpressure-retry.json",
		"../../examples/05-permanent-loss-diagnosis.json",
	}
	for _, f := range files {
		t.Run(f, func(t *testing.T) {
			if _, err := os.Stat(f); err != nil {
				t.Skip("example file not present")
			}
			req := mustReadRequest(t, f)
			r := Run(req)
			if r.Status != "ok" {
				t.Fatalf("example %s status=%s error=%s", f, r.Status, r.Error)
			}
			assertCausal(t, r)
		})
	}
}

func TestValidationErrors(t *testing.T) {
	cases := map[string]*Request{
		"one node":     {Nodes: []string{"a"}, EndTimeMs: 10},
		"dup nodes":    {Nodes: []string{"a", "a"}, EndTimeMs: 10},
		"bad end time": {Nodes: []string{"a", "b"}},
		"bad loss":     {Nodes: []string{"a", "b"}, EndTimeMs: 10, Network: PolicyRandom(1.2, 0, 1, 2)},
		"unknown broadcast node": {
			Nodes: []string{"a", "b"}, EndTimeMs: 10,
			Broadcasts: []BroadcastSpec{{AtMs: 0, Node: "z"}},
		},
		"bad topology edge": {
			Nodes: []string{"a", "b"}, EndTimeMs: 10,
			Topology: map[string][]string{"a": {"z"}, "b": {}},
		},
		"invalid fault action": {
			Nodes: []string{"a", "b"}, EndTimeMs: 10,
			Faults: faultList{{origin: "a", seq: 1, to: "b", action: "explode"}}.toFaults(),
		},
	}
	for name, req := range cases {
		t.Run(name, func(t *testing.T) {
			if r := Run(req); r.Status != "error" {
				t.Fatalf("%s: expected validation error, got %s (%s)", name, r.Status, r.Error)
			}
		})
	}
}
