apiVersion: v1
kind: Namespace
metadata:
  name: team-a-1
  labels:
    team: a
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-a-2
  labels:
    team: a
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-b-1
  labels:
    team: b
