# Generated by Django 5.0.14 on 2026-09-21 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('experiments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=64, unique=True)),
                ('event_type', models.CharField(choices=[('impression', 'Impression request'), ('fill', 'Fill'), ('revenue', 'Revenue'), ('failure', 'Failure')], max_length=16)),
                ('event_time', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('revenue', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('experiment_variant', models.CharField(blank=True, default='', max_length=8)),
                ('user_key_hash', models.CharField(blank=True, default='', max_length=64)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='catalog.app')),
                ('config_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='catalog.configversion')),
                ('experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='experiments.experiment')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='catalog.adnetwork')),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='catalog.placement')),
            ],
            options={
                'ordering': ['event_time'],
                'indexes': [models.Index(fields=['event_time'], name='ingestion_a_event_t_62ff3a_idx'), models.Index(fields=['app', 'event_time'], name='ingestion_a_app_id_22faf0_idx'), models.Index(fields=['placement', 'network', 'event_time'], name='ingestion_a_placeme_94f643_idx'), models.Index(fields=['experiment', 'experiment_variant'], name='ingestion_a_experim_41d0f5_idx')],
            },
        ),
    ]
