# Generated by Django 5.0.14 on 2026-09-20 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_courses', to=settings.AUTH_USER_MODEL)),
                ('teachers', models.ManyToManyField(blank=True, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('size_bytes', models.PositiveIntegerField()),
                ('content_sha256', models.CharField(db_index=True, max_length=64)),
                ('text', models.TextField()),
                ('char_count', models.PositiveIntegerField(default=0)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='analysis.course')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Waiting for a worker'), ('running', 'Claimed by a worker'), ('succeeded', 'Result stored'), ('failed', 'Permanently failed (max attempts reached)')], db_index=True, default='pending', max_length=20)),
                ('stage', models.CharField(choices=[('queued', 'Queued'), ('extract', 'Text normalisation'), ('parse', 'Linguistic parsing (spaCy/NLTK)'), ('metrics', 'Metric computation'), ('style', 'Style similarity against course samples'), ('persist', 'Storing the versioned result')], default='queued', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('worker_id', models.CharField(blank=True, default='', max_length=64)),
                ('leased_at', models.DateTimeField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('generation', models.PositiveIntegerField(default=0)),
                ('error_stage', models.CharField(blank=True, default='', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='analysis.document')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('algorithm_version', models.CharField(max_length=20)),
                ('input_sha256', models.CharField(max_length=64)),
                ('metrics_json', models.JSONField()),
                ('style_vector', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='result', to='analysis.analysistask')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='analysis.document')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='analysis.course')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='analysis.submissionbatch'),
        ),
        migrations.CreateModel(
            name='UploadAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('content_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('created', 'Created new document'), ('duplicate', 'Duplicate of an existing document in this course'), ('rejected', 'Rejected before storage')], max_length=20)),
                ('detail', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='analysis.submissionbatch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='analysis.course')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='analysis.document')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='analysistask',
            index=models.Index(fields=['status', 'lease_expires_at'], name='analysis_an_status_a6282f_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisresult',
            index=models.Index(fields=['document', '-version'], name='analysis_an_documen_0d9a7f_idx'),
        ),
        migrations.AddConstraint(
            model_name='analysisresult',
            constraint=models.UniqueConstraint(fields=('document', 'version'), name='uniq_result_version'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['course', 'created_at'], name='analysis_do_course__01c3b5_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('course', 'content_sha256'), name='uniq_document_per_course_content'),
        ),
    ]
