# Generated by Django 5.0.14 on 2026-09-21 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('trading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FREEZE', 'Freeze on new order'), ('RELEASE', 'Release on cancel / leftover'), ('TRADE', 'Trade settlement'), ('DEPOSIT', 'Simulated deposit'), ('WITHDRAWAL', 'Simulated withdrawal'), ('MAINTENANCE', 'Maintenance bulk release')], max_length=16)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_events', to='trading.order')),
                ('trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_events', to='trading.trade')),
            ],
            options={
                'db_table': 'ledger_events',
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subaccount', models.CharField(choices=[('AVAILABLE', 'Available'), ('FROZEN', 'Frozen')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=30)),
                ('balance_after', models.DecimalField(decimal_places=8, max_digits=30)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='accounts.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='ledger.ledgerevent')),
            ],
            options={
                'db_table': 'ledger_entries',
                'indexes': [models.Index(fields=['user', 'asset', '-id'], name='ix_ledger_user_asset')],
            },
        ),
    ]
