// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: courses.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCourse = `-- name: CreateCourse :one
INSERT INTO courses (community_id, title, status)
VALUES ($1, $2, 'draft')
RETURNING id, community_id, title, status, published_snapshot_id,
          created_at, updated_at
`

type CreateCourseParams struct {
	CommunityID int64  `json:"community_id"`
	Title       string `json:"title"`
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, createCourse, arg.CommunityID, arg.Title)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.CommunityID,
		&i.Title,
		&i.Status,
		&i.PublishedSnapshotID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllModules = `-- name: DeleteAllModules :exec
DELETE FROM course_modules WHERE course_id = $1
`

func (q *Queries) DeleteAllModules(ctx context.Context, courseID int64) error {
	_, err := q.db.Exec(ctx, deleteAllModules, courseID)
	return err
}

const deleteLessonsFromPosition = `-- name: DeleteLessonsFromPosition :exec
DELETE FROM course_lessons WHERE module_id = $1 AND position >= $2
`

type DeleteLessonsFromPositionParams struct {
	ModuleID int64 `json:"module_id"`
	Position int32 `json:"position"`
}

func (q *Queries) DeleteLessonsFromPosition(ctx context.Context, arg DeleteLessonsFromPositionParams) error {
	_, err := q.db.Exec(ctx, deleteLessonsFromPosition, arg.ModuleID, arg.Position)
	return err
}

const deleteModulesFromPosition = `-- name: DeleteModulesFromPosition :exec
DELETE FROM course_modules WHERE course_id = $1 AND position >= $2
`

type DeleteModulesFromPositionParams struct {
	CourseID int64 `json:"course_id"`
	Position int32 `json:"position"`
}

func (q *Queries) DeleteModulesFromPosition(ctx context.Context, arg DeleteModulesFromPositionParams) error {
	_, err := q.db.Exec(ctx, deleteModulesFromPosition, arg.CourseID, arg.Position)
	return err
}

const getCourse = `-- name: GetCourse :one
SELECT id, community_id, title, status, published_snapshot_id,
       created_at, updated_at
FROM courses WHERE id = $1
`

func (q *Queries) GetCourse(ctx context.Context, id int64) (Course, error) {
	row := q.db.QueryRow(ctx, getCourse, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.CommunityID,
		&i.Title,
		&i.Status,
		&i.PublishedSnapshotID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDraftStructure = `-- name: GetDraftStructure :many
SELECT cl.content_version_id AS content_version_id,
       cm.position AS module_position,
       cl.position AS lesson_position
FROM course_modules cm
JOIN course_lessons cl ON cl.module_id = cm.id
WHERE cm.course_id = $1
ORDER BY cm.position, cl.position
`

type GetDraftStructureRow struct {
	ContentVersionID pgtype.Int8 `json:"content_version_id"`
	ModulePosition   int32       `json:"module_position"`
	LessonPosition   int32       `json:"lesson_position"`
}

// All lessons of a course with module positions, used at publish validation.
func (q *Queries) GetDraftStructure(ctx context.Context, courseID int64) ([]GetDraftStructureRow, error) {
	rows, err := q.db.Query(ctx, getDraftStructure, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDraftStructureRow
	for rows.Next() {
		var i GetDraftStructureRow
		if err := rows.Scan(&i.ContentVersionID, &i.ModulePosition, &i.LessonPosition); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSnapshot = `-- name: GetSnapshot :one
SELECT id, course_id, title, published_at, published_by
FROM course_publish_snapshots WHERE id = $1
`

func (q *Queries) GetSnapshot(ctx context.Context, id int64) (CoursePublishSnapshot, error) {
	row := q.db.QueryRow(ctx, getSnapshot, id)
	var i CoursePublishSnapshot
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.PublishedAt,
		&i.PublishedBy,
	)
	return i, err
}

const getVersionsForPublish = `-- name: GetVersionsForPublish :many
SELECT pv.id, pv.post_id, pv.version_number, pv.title, pv.review_status,
       p.status AS post_status, p.published_version_id
FROM post_versions pv
JOIN posts p ON p.id = pv.post_id
WHERE pv.id = ANY($1::bigint[])
`

type GetVersionsForPublishRow struct {
	ID                 int64       `json:"id"`
	PostID             int64       `json:"post_id"`
	VersionNumber      int32       `json:"version_number"`
	Title              string      `json:"title"`
	ReviewStatus       string      `json:"review_status"`
	PostStatus         string      `json:"post_status"`
	PublishedVersionID pgtype.Int8 `json:"published_version_id"`
}

func (q *Queries) GetVersionsForPublish(ctx context.Context, dollar_1 []int64) ([]GetVersionsForPublishRow, error) {
	rows, err := q.db.Query(ctx, getVersionsForPublish, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetVersionsForPublishRow
	for rows.Next() {
		var i GetVersionsForPublishRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.VersionNumber,
			&i.Title,
			&i.ReviewStatus,
			&i.PostStatus,
			&i.PublishedVersionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSnapshot = `-- name: InsertSnapshot :one
INSERT INTO course_publish_snapshots (course_id, title, published_by)
VALUES ($1, $2, $3)
RETURNING id, course_id, title, published_at, published_by
`

type InsertSnapshotParams struct {
	CourseID    int64  `json:"course_id"`
	Title       string `json:"title"`
	PublishedBy int64  `json:"published_by"`
}

func (q *Queries) InsertSnapshot(ctx context.Context, arg InsertSnapshotParams) (CoursePublishSnapshot, error) {
	row := q.db.QueryRow(ctx, insertSnapshot, arg.CourseID, arg.Title, arg.PublishedBy)
	var i CoursePublishSnapshot
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.PublishedAt,
		&i.PublishedBy,
	)
	return i, err
}

const insertSnapshotLesson = `-- name: InsertSnapshotLesson :one
INSERT INTO course_snapshot_lessons (snap_module_id, position, title,
                                     content_version_id)
VALUES ($1, $2, $3, $4)
RETURNING id, snap_module_id, position, title, content_version_id
`

type InsertSnapshotLessonParams struct {
	SnapModuleID     int64  `json:"snap_module_id"`
	Position         int32  `json:"position"`
	Title            string `json:"title"`
	ContentVersionID int64  `json:"content_version_id"`
}

func (q *Queries) InsertSnapshotLesson(ctx context.Context, arg InsertSnapshotLessonParams) (CourseSnapshotLesson, error) {
	row := q.db.QueryRow(ctx, insertSnapshotLesson,
		arg.SnapModuleID,
		arg.Position,
		arg.Title,
		arg.ContentVersionID,
	)
	var i CourseSnapshotLesson
	err := row.Scan(
		&i.ID,
		&i.SnapModuleID,
		&i.Position,
		&i.Title,
		&i.ContentVersionID,
	)
	return i, err
}

const insertSnapshotModule = `-- name: InsertSnapshotModule :one
INSERT INTO course_snapshot_modules (snapshot_id, position, title)
VALUES ($1, $2, $3)
RETURNING id, snapshot_id, position, title
`

type InsertSnapshotModuleParams struct {
	SnapshotID int64  `json:"snapshot_id"`
	Position   int32  `json:"position"`
	Title      string `json:"title"`
}

func (q *Queries) InsertSnapshotModule(ctx context.Context, arg InsertSnapshotModuleParams) (CourseSnapshotModule, error) {
	row := q.db.QueryRow(ctx, insertSnapshotModule, arg.SnapshotID, arg.Position, arg.Title)
	var i CourseSnapshotModule
	err := row.Scan(
		&i.ID,
		&i.SnapshotID,
		&i.Position,
		&i.Title,
	)
	return i, err
}

const listCourses = `-- name: ListCourses :many
SELECT id, community_id, title, status, published_snapshot_id,
       created_at, updated_at
FROM courses WHERE community_id = $1 ORDER BY id DESC
`

func (q *Queries) ListCourses(ctx context.Context, communityID int64) ([]Course, error) {
	rows, err := q.db.Query(ctx, listCourses, communityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Course
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.CommunityID,
			&i.Title,
			&i.Status,
			&i.PublishedSnapshotID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDraftLessons = `-- name: ListDraftLessons :many
SELECT id, module_id, position, title, content_version_id
FROM course_lessons WHERE module_id = $1 ORDER BY position
`

func (q *Queries) ListDraftLessons(ctx context.Context, moduleID int64) ([]CourseLesson, error) {
	rows, err := q.db.Query(ctx, listDraftLessons, moduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CourseLesson
	for rows.Next() {
		var i CourseLesson
		if err := rows.Scan(
			&i.ID,
			&i.ModuleID,
			&i.Position,
			&i.Title,
			&i.ContentVersionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDraftModules = `-- name: ListDraftModules :many
SELECT id, course_id, position, title
FROM course_modules WHERE course_id = $1 ORDER BY position
`

func (q *Queries) ListDraftModules(ctx context.Context, courseID int64) ([]CourseModule, error) {
	rows, err := q.db.Query(ctx, listDraftModules, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CourseModule
	for rows.Next() {
		var i CourseModule
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Position,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshotLessons = `-- name: ListSnapshotLessons :many
SELECT id, snap_module_id, position, title, content_version_id
FROM course_snapshot_lessons
WHERE snap_module_id = ANY($1::bigint[]) ORDER BY snap_module_id, position
`

func (q *Queries) ListSnapshotLessons(ctx context.Context, dollar_1 []int64) ([]CourseSnapshotLesson, error) {
	rows, err := q.db.Query(ctx, listSnapshotLessons, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CourseSnapshotLesson
	for rows.Next() {
		var i CourseSnapshotLesson
		if err := rows.Scan(
			&i.ID,
			&i.SnapModuleID,
			&i.Position,
			&i.Title,
			&i.ContentVersionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshotModules = `-- name: ListSnapshotModules :many
SELECT id, snapshot_id, position, title
FROM course_snapshot_modules WHERE snapshot_id = $1 ORDER BY position
`

func (q *Queries) ListSnapshotModules(ctx context.Context, snapshotID int64) ([]CourseSnapshotModule, error) {
	rows, err := q.db.Query(ctx, listSnapshotModules, snapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CourseSnapshotModule
	for rows.Next() {
		var i CourseSnapshotModule
		if err := rows.Scan(
			&i.ID,
			&i.SnapshotID,
			&i.Position,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCoursePublished = `-- name: MarkCoursePublished :one

UPDATE courses
SET status = 'published', published_snapshot_id = $2, updated_at = now()
WHERE id = $1 AND community_id = $3
RETURNING id, community_id, title, status, published_snapshot_id,
          created_at, updated_at
`

type MarkCoursePublishedParams struct {
	ID                  int64       `json:"id"`
	PublishedSnapshotID pgtype.Int8 `json:"published_snapshot_id"`
	CommunityID         int64       `json:"community_id"`
}

// Publishing ------------------------------------------------------------------
func (q *Queries) MarkCoursePublished(ctx context.Context, arg MarkCoursePublishedParams) (Course, error) {
	row := q.db.QueryRow(ctx, markCoursePublished, arg.ID, arg.PublishedSnapshotID, arg.CommunityID)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.CommunityID,
		&i.Title,
		&i.Status,
		&i.PublishedSnapshotID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resetCourseToDraft = `-- name: ResetCourseToDraft :one
UPDATE courses SET status = 'draft', updated_at = now()
WHERE id = $1 AND community_id = $2
RETURNING id, community_id, title, status, published_snapshot_id,
          created_at, updated_at
`

type ResetCourseToDraftParams struct {
	ID          int64 `json:"id"`
	CommunityID int64 `json:"community_id"`
}

func (q *Queries) ResetCourseToDraft(ctx context.Context, arg ResetCourseToDraftParams) (Course, error) {
	row := q.db.QueryRow(ctx, resetCourseToDraft, arg.ID, arg.CommunityID)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.CommunityID,
		&i.Title,
		&i.Status,
		&i.PublishedSnapshotID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCourseTitle = `-- name: UpdateCourseTitle :exec
UPDATE courses SET title = $2, updated_at = now()
WHERE id = $1 AND status = 'draft'
`

type UpdateCourseTitleParams struct {
	ID    int64  `json:"id"`
	Title string `json:"title"`
}

func (q *Queries) UpdateCourseTitle(ctx context.Context, arg UpdateCourseTitleParams) error {
	_, err := q.db.Exec(ctx, updateCourseTitle, arg.ID, arg.Title)
	return err
}

const upsertLesson = `-- name: UpsertLesson :one
INSERT INTO course_lessons (module_id, position, title, content_version_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (module_id, position) DO UPDATE
SET title = EXCLUDED.title,
    content_version_id = EXCLUDED.content_version_id
RETURNING id, module_id, position, title, content_version_id
`

type UpsertLessonParams struct {
	ModuleID         int64       `json:"module_id"`
	Position         int32       `json:"position"`
	Title            string      `json:"title"`
	ContentVersionID pgtype.Int8 `json:"content_version_id"`
}

func (q *Queries) UpsertLesson(ctx context.Context, arg UpsertLessonParams) (CourseLesson, error) {
	row := q.db.QueryRow(ctx, upsertLesson,
		arg.ModuleID,
		arg.Position,
		arg.Title,
		arg.ContentVersionID,
	)
	var i CourseLesson
	err := row.Scan(
		&i.ID,
		&i.ModuleID,
		&i.Position,
		&i.Title,
		&i.ContentVersionID,
	)
	return i, err
}

const upsertModule = `-- name: UpsertModule :one

INSERT INTO course_modules (course_id, position, title)
VALUES ($1, $2, $3)
ON CONFLICT (course_id, position) DO UPDATE SET title = EXCLUDED.title
RETURNING id, course_id, position, title
`

type UpsertModuleParams struct {
	CourseID int64  `json:"course_id"`
	Position int32  `json:"position"`
	Title    string `json:"title"`
}

// Draft modules / lessons -----------------------------------------------------
func (q *Queries) UpsertModule(ctx context.Context, arg UpsertModuleParams) (CourseModule, error) {
	row := q.db.QueryRow(ctx, upsertModule, arg.CourseID, arg.Position, arg.Title)
	var i CourseModule
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Position,
		&i.Title,
	)
	return i, err
}
