// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlcgen

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Attachment struct {
	ID          int64     `json:"id"`
	VersionID   int64     `json:"version_id"`
	Filename    string    `json:"filename"`
	ContentType string    `json:"content_type"`
	Data        []byte    `json:"data"`
	CreatedAt   time.Time `json:"created_at"`
}

type Community struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedBy int64     `json:"created_by"`
	CreatedAt time.Time `json:"created_at"`
}

type CommunityReviewer struct {
	CommunityID int64     `json:"community_id"`
	UserID      int64     `json:"user_id"`
	CreatedAt   time.Time `json:"created_at"`
}

type Course struct {
	ID                  int64       `json:"id"`
	CommunityID         int64       `json:"community_id"`
	Title               string      `json:"title"`
	Status              string      `json:"status"`
	PublishedSnapshotID pgtype.Int8 `json:"published_snapshot_id"`
	CreatedAt           time.Time   `json:"created_at"`
	UpdatedAt           time.Time   `json:"updated_at"`
}

type CourseLesson struct {
	ID               int64       `json:"id"`
	ModuleID         int64       `json:"module_id"`
	Position         int32       `json:"position"`
	Title            string      `json:"title"`
	ContentVersionID pgtype.Int8 `json:"content_version_id"`
}

type CourseModule struct {
	ID       int64  `json:"id"`
	CourseID int64  `json:"course_id"`
	Position int32  `json:"position"`
	Title    string `json:"title"`
}

type CoursePublishSnapshot struct {
	ID          int64     `json:"id"`
	CourseID    int64     `json:"course_id"`
	Title       string    `json:"title"`
	PublishedAt time.Time `json:"published_at"`
	PublishedBy int64     `json:"published_by"`
}

type CourseSnapshotLesson struct {
	ID               int64  `json:"id"`
	SnapModuleID     int64  `json:"snap_module_id"`
	Position         int32  `json:"position"`
	Title            string `json:"title"`
	ContentVersionID int64  `json:"content_version_id"`
}

type CourseSnapshotModule struct {
	ID         int64  `json:"id"`
	SnapshotID int64  `json:"snapshot_id"`
	Position   int32  `json:"position"`
	Title      string `json:"title"`
}

type Membership struct {
	ID          int64     `json:"id"`
	CommunityID int64     `json:"community_id"`
	UserID      int64     `json:"user_id"`
	TierID      int64     `json:"tier_id"`
	StartsAt    time.Time `json:"starts_at"`
	ExpiresAt   time.Time `json:"expires_at"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
}

type Payment struct {
	ID           int64     `json:"id"`
	CommunityID  int64     `json:"community_id"`
	RequestID    string    `json:"request_id"`
	UserID       int64     `json:"user_id"`
	TierID       int64     `json:"tier_id"`
	AmountCents  int64     `json:"amount_cents"`
	ExtendDays   int32     `json:"extend_days"`
	MembershipID int64     `json:"membership_id"`
	RecordedBy   int64     `json:"recorded_by"`
	CreatedAt    time.Time `json:"created_at"`
}

type Post struct {
	ID                    int64       `json:"id"`
	CommunityID           int64       `json:"community_id"`
	AuthorID              int64       `json:"author_id"`
	RequiredTierLevel     int32       `json:"required_tier_level"`
	Title                 string      `json:"title"`
	Status                string      `json:"status"`
	CurrentVersionID      pgtype.Int8 `json:"current_version_id"`
	PublishedVersionID    pgtype.Int8 `json:"published_version_id"`
	RemovedReason         string      `json:"removed_reason"`
	RestoredFromVersionID pgtype.Int8 `json:"restored_from_version_id"`
	CreatedAt             time.Time   `json:"created_at"`
	UpdatedAt             time.Time   `json:"updated_at"`
}

type PostVersion struct {
	ID                int64     `json:"id"`
	PostID            int64     `json:"post_id"`
	VersionNumber     int32     `json:"version_number"`
	Title             string    `json:"title"`
	Body              string    `json:"body"`
	RequiredTierLevel int32     `json:"required_tier_level"`
	AuthorID          int64     `json:"author_id"`
	ReviewStatus      string    `json:"review_status"`
	CreatedAt         time.Time `json:"created_at"`
}

type Report struct {
	ID              int64     `json:"id"`
	CommunityID     int64     `json:"community_id"`
	ReporterID      int64     `json:"reporter_id"`
	PostID          int64     `json:"post_id"`
	TargetVersionID int64     `json:"target_version_id"`
	Category        string    `json:"category"`
	Reason          string    `json:"reason"`
	Status          string    `json:"status"`
	CreatedAt       time.Time `json:"created_at"`
}

type ReportDecision struct {
	ID        int64     `json:"id"`
	ReportID  int64     `json:"report_id"`
	Action    string    `json:"action"`
	ActorID   int64     `json:"actor_id"`
	Reason    string    `json:"reason"`
	CreatedAt time.Time `json:"created_at"`
}

type Review struct {
	ID             int64     `json:"id"`
	PostID         int64     `json:"post_id"`
	VersionID      int64     `json:"version_id"`
	ReviewerID     int64     `json:"reviewer_id"`
	Action         string    `json:"action"`
	Reason         string    `json:"reason"`
	ExpectedStatus string    `json:"expected_status"`
	Success        bool      `json:"success"`
	CreatedAt      time.Time `json:"created_at"`
}

type Tier struct {
	ID           int64  `json:"id"`
	CommunityID  int64  `json:"community_id"`
	Level        int32  `json:"level"`
	Name         string `json:"name"`
	PriceCents   int64  `json:"price_cents"`
	DurationDays int32  `json:"duration_days"`
}

type User struct {
	ID           int64     `json:"id"`
	Email        string    `json:"email"`
	DisplayName  string    `json:"display_name"`
	Role         string    `json:"role"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
}
