# Generated by Django 4.2.16 on 2026-09-21 18:49

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_start', models.DateTimeField(unique=True)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('finalized', models.BooleanField(default=False)),
                ('items_hash', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-slot_start'],
            },
        ),
        migrations.CreateModel(
            name='ScoreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fills', models.PositiveIntegerField(default=0)),
                ('failures', models.PositiveIntegerField(default=0)),
                ('errors', models.PositiveIntegerField(default=0)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=14)),
                ('opportunities', models.PositiveIntegerField(default=0)),
                ('fill_rate', models.DecimalField(decimal_places=9, default=Decimal('0'), max_digits=12)),
                ('ecpm', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=14)),
                ('reliability', models.DecimalField(decimal_places=9, default=Decimal('0'), max_digits=12)),
                ('norm_fill_rate', models.DecimalField(decimal_places=9, default=Decimal('0'), max_digits=12)),
                ('norm_ecpm', models.DecimalField(decimal_places=9, default=Decimal('0'), max_digits=12)),
                ('norm_reliability', models.DecimalField(decimal_places=9, default=Decimal('0'), max_digits=12)),
                ('total_score', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=12)),
                ('rank', models.PositiveSmallIntegerField()),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='score_items', to='applications.adnetwork')),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_items', to='applications.placement')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='scoring.scorerun')),
            ],
            options={
                'ordering': ['run_id', 'placement_id', 'rank', 'network_id'],
                'indexes': [models.Index(fields=['placement', '-run', 'rank'], name='scoring_sco_placeme_182b7a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='scoreitem',
            constraint=models.UniqueConstraint(fields=('run', 'placement', 'network'), name='uniq_scoreitem_per_run_placement_network'),
        ),
    ]
