// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID         int64              `json:"id"`
	ActorUser  *uuid.UUID         `json:"actor_user"`
	ActorRole  string             `json:"actor_role"`
	MerchantID *uuid.UUID         `json:"merchant_id"`
	Action     string             `json:"action"`
	TargetType pgtype.Text        `json:"target_type"`
	TargetID   pgtype.Text        `json:"target_id"`
	Masked     bool               `json:"masked"`
	Detail     []byte             `json:"detail"`
	Ip         pgtype.Text        `json:"ip"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ChannelEvent struct {
	ID          int64              `json:"id"`
	MerchantID  uuid.UUID          `json:"merchant_id"`
	EventDate   pgtype.Date        `json:"event_date"`
	EventType   string             `json:"event_type"`
	PaymentID   uuid.UUID          `json:"payment_id"`
	RefundID    *uuid.UUID         `json:"refund_id"`
	GrossAmount int64              `json:"gross_amount"`
	FeeDelta    int64              `json:"fee_delta"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type IdempotentRequest struct {
	ID           uuid.UUID          `json:"id"`
	MerchantID   uuid.UUID          `json:"merchant_id"`
	IdemKey      string             `json:"idem_key"`
	Route        string             `json:"route"`
	RequestHash  string             `json:"request_hash"`
	StatusCode   int32              `json:"status_code"`
	ResponseBody []byte             `json:"response_body"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type LedgerAccount struct {
	ID        uuid.UUID          `json:"id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	Kind      string             `json:"kind"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type LedgerEntry struct {
	ID        int64              `json:"id"`
	AccountID uuid.UUID          `json:"account_id"`
	RefType   string             `json:"ref_type"`
	RefID     uuid.UUID          `json:"ref_id"`
	Amount    int64              `json:"amount"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Merchant struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	FeeBps       int32              `json:"fee_bps"`
	FeeFixed     int64              `json:"fee_fixed"`
	Status       string             `json:"status"`
	ApiKeyHash   pgtype.Text        `json:"api_key_hash"`
	ApiKeyPrefix pgtype.Text        `json:"api_key_prefix"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Payment struct {
	ID                uuid.UUID          `json:"id"`
	MerchantID        uuid.UUID          `json:"merchant_id"`
	IdempotencyKey    string             `json:"idempotency_key"`
	Status            string             `json:"status"`
	AuthorizedAmount  int64              `json:"authorized_amount"`
	CapturedAmount    int64              `json:"captured_amount"`
	FeeBps            int32              `json:"fee_bps"`
	FeeFixed          int64              `json:"fee_fixed"`
	FeeAmount         int64              `json:"fee_amount"`
	RefundedAmount    int64              `json:"refunded_amount"`
	RefundedFee       int64              `json:"refunded_fee"`
	Currency          string             `json:"currency"`
	ExternalRef       pgtype.Text        `json:"external_ref"`
	AuthorizedAt      pgtype.Timestamptz `json:"authorized_at"`
	CapturedAt        pgtype.Timestamptz `json:"captured_at"`
	VoidedAt          pgtype.Timestamptz `json:"voided_at"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	SettlementBatchID *uuid.UUID         `json:"settlement_batch_id"`
}

type ReconciliationItem struct {
	ID         int64              `json:"id"`
	RunID      uuid.UUID          `json:"run_id"`
	CheckName  string             `json:"check_name"`
	Expected   int64              `json:"expected"`
	Actual     int64              `json:"actual"`
	Difference int64              `json:"difference"`
	Severity   string             `json:"severity"`
	Detail     pgtype.Text        `json:"detail"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ReconciliationRun struct {
	ID            uuid.UUID          `json:"id"`
	MerchantID    uuid.UUID          `json:"merchant_id"`
	RunDate       pgtype.Date        `json:"run_date"`
	Status        string             `json:"status"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	DetailSummary []byte             `json:"detail_summary"`
}

type Refund struct {
	ID             uuid.UUID          `json:"id"`
	PaymentID      uuid.UUID          `json:"payment_id"`
	MerchantID     uuid.UUID          `json:"merchant_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	Amount         int64              `json:"amount"`
	FeeRefund      int64              `json:"fee_refund"`
	Reason         pgtype.Text        `json:"reason"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type SettlementBatch struct {
	ID            uuid.UUID          `json:"id"`
	MerchantID    uuid.UUID          `json:"merchant_id"`
	BatchDate     pgtype.Date        `json:"batch_date"`
	Status        string             `json:"status"`
	GrossCaptured int64              `json:"gross_captured"`
	TotalFees     int64              `json:"total_fees"`
	TotalRefunds  int64              `json:"total_refunds"`
	RefundedFees  int64              `json:"refunded_fees"`
	NetAmount     int64              `json:"net_amount"`
	PaymentCount  int32              `json:"payment_count"`
	LockedBy      pgtype.Text        `json:"locked_by"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	MerchantID   *uuid.UUID         `json:"merchant_id"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type VAccountBalance struct {
	ID          uuid.UUID   `json:"id"`
	Code        string      `json:"code"`
	Kind        string      `json:"kind"`
	Balance     interface{} `json:"balance"`
	LastEntryID interface{} `json:"last_entry_id"`
}

type VInternalDailyCapture struct {
	MerchantID   uuid.UUID   `json:"merchant_id"`
	Day          pgtype.Date `json:"day"`
	CaptureGross int64       `json:"capture_gross"`
	FeeCharged   int64       `json:"fee_charged"`
	CaptureCount int64       `json:"capture_count"`
}

type VInternalDailyRefund struct {
	MerchantID  uuid.UUID   `json:"merchant_id"`
	Day         pgtype.Date `json:"day"`
	RefundGross int64       `json:"refund_gross"`
	FeeRefunded int64       `json:"fee_refunded"`
	RefundCount int64       `json:"refund_count"`
}

type VUnbalancedPosting struct {
	RefType string    `json:"ref_type"`
	RefID   uuid.UUID `json:"ref_id"`
	Net     int64     `json:"net"`
}
