// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ActionItem struct {
	ID                 pgtype.UUID        `json:"id"`
	IncidentID         pgtype.UUID        `json:"incident_id"`
	Title              string             `json:"title"`
	OwnerID            pgtype.UUID        `json:"owner_id"`
	DueAt              pgtype.Timestamptz `json:"due_at"`
	Status             string             `json:"status"`
	DueVersion         int64              `json:"due_version"`
	RemindedDueVersion int64              `json:"reminded_due_version"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type AuditEvent struct {
	ID         pgtype.UUID        `json:"id"`
	IncidentID pgtype.UUID        `json:"incident_id"`
	ActorID    pgtype.UUID        `json:"actor_id"`
	EventType  string             `json:"event_type"`
	Payload    []byte             `json:"payload"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Evidence struct {
	ID         pgtype.UUID        `json:"id"`
	IncidentID pgtype.UUID        `json:"incident_id"`
	Seq        int32              `json:"seq"`
	Content    string             `json:"content"`
	AuthorID   pgtype.UUID        `json:"author_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type EvidenceNote struct {
	ID         pgtype.UUID        `json:"id"`
	EvidenceID pgtype.UUID        `json:"evidence_id"`
	Content    string             `json:"content"`
	AuthorID   pgtype.UUID        `json:"author_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Incident struct {
	ID             pgtype.UUID        `json:"id"`
	Title          string             `json:"title"`
	Description    string             `json:"description"`
	Severity       string             `json:"severity"`
	Status         string             `json:"status"`
	Version        int64              `json:"version"`
	AssigneeID     pgtype.UUID        `json:"assignee_id"`
	RootCause      string             `json:"root_cause"`
	LessonsLearned string             `json:"lessons_learned"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type PhaseTransition struct {
	ID           pgtype.UUID        `json:"id"`
	IncidentID   pgtype.UUID        `json:"incident_id"`
	RequestID    string             `json:"request_id"`
	FromStatus   string             `json:"from_status"`
	ToStatus     string             `json:"to_status"`
	ActorID      pgtype.UUID        `json:"actor_id"`
	Note         string             `json:"note"`
	VersionAfter int64              `json:"version_after"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Reminder struct {
	ID           pgtype.UUID        `json:"id"`
	ActionItemID pgtype.UUID        `json:"action_item_id"`
	DueVersion   int64              `json:"due_version"`
	SentAt       pgtype.Timestamptz `json:"sent_at"`
}

type User struct {
	ID        pgtype.UUID        `json:"id"`
	Username  string             `json:"username"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
