// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: payments.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const applyRefund = `-- name: ApplyRefund :one
UPDATE payments
SET refunded_amount = refunded_amount + $3,
    refunded_fee    = refunded_fee + $4,
    status = CASE WHEN settlement_batch_id IS NOT NULL THEN 'settled'
                  WHEN refunded_amount + $3 = captured_amount
                  THEN 'refunded' ELSE 'partially_refunded' END
WHERE id = $1 AND merchant_id = $2
RETURNING id, merchant_id, idempotency_key, status, authorized_amount, captured_amount, fee_bps, fee_fixed, fee_amount, refunded_amount, refunded_fee, currency, external_ref, authorized_at, captured_at, voided_at, expires_at, created_at, updated_at, settlement_batch_id
`

type ApplyRefundParams struct {
	ID             uuid.UUID `json:"id"`
	MerchantID     uuid.UUID `json:"merchant_id"`
	RefundedAmount int64     `json:"refunded_amount"`
	RefundedFee    int64     `json:"refunded_fee"`
}

func (q *Queries) ApplyRefund(ctx context.Context, arg ApplyRefundParams) (Payment, error) {
	row := q.db.QueryRow(ctx, applyRefund,
		arg.ID,
		arg.MerchantID,
		arg.RefundedAmount,
		arg.RefundedFee,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.IdempotencyKey,
		&i.Status,
		&i.AuthorizedAmount,
		&i.CapturedAmount,
		&i.FeeBps,
		&i.FeeFixed,
		&i.FeeAmount,
		&i.RefundedAmount,
		&i.RefundedFee,
		&i.Currency,
		&i.ExternalRef,
		&i.AuthorizedAt,
		&i.CapturedAt,
		&i.VoidedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SettlementBatchID,
	)
	return i, err
}

const capturePayment = `-- name: CapturePayment :one
UPDATE payments
SET status = 'captured',
    captured_amount = $3,
    fee_amount = $4,
    captured_at = now()
WHERE id = $1 AND merchant_id = $2 AND status = 'authorized'
RETURNING id, merchant_id, idempotency_key, status, authorized_amount, captured_amount, fee_bps, fee_fixed, fee_amount, refunded_amount, refunded_fee, currency, external_ref, authorized_at, captured_at, voided_at, expires_at, created_at, updated_at, settlement_batch_id
`

type CapturePaymentParams struct {
	ID             uuid.UUID `json:"id"`
	MerchantID     uuid.UUID `json:"merchant_id"`
	CapturedAmount int64     `json:"captured_amount"`
	FeeAmount      int64     `json:"fee_amount"`
}

func (q *Queries) CapturePayment(ctx context.Context, arg CapturePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, capturePayment,
		arg.ID,
		arg.MerchantID,
		arg.CapturedAmount,
		arg.FeeAmount,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.IdempotencyKey,
		&i.Status,
		&i.AuthorizedAmount,
		&i.CapturedAmount,
		&i.FeeBps,
		&i.FeeFixed,
		&i.FeeAmount,
		&i.RefundedAmount,
		&i.RefundedFee,
		&i.Currency,
		&i.ExternalRef,
		&i.AuthorizedAt,
		&i.CapturedAt,
		&i.VoidedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SettlementBatchID,
	)
	return i, err
}

const countUnsettledCapturedPayments = `-- name: CountUnsettledCapturedPayments :one
SELECT COUNT(*)::int FROM payments
WHERE merchant_id = $1
  AND captured_at IS NOT NULL
  AND captured_at < ($2::timestamptz)
  AND settlement_batch_id IS NULL
  AND status IN ('captured','partially_refunded')
`

type CountUnsettledCapturedPaymentsParams struct {
	MerchantID uuid.UUID          `json:"merchant_id"`
	Column2    pgtype.Timestamptz `json:"column_2"`
}

func (q *Queries) CountUnsettledCapturedPayments(ctx context.Context, arg CountUnsettledCapturedPaymentsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countUnsettledCapturedPayments, arg.MerchantID, arg.Column2)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createIdempotentRequest = `-- name: CreateIdempotentRequest :one
INSERT INTO idempotent_requests (merchant_id, idem_key, route, request_hash, status_code, response_body)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, merchant_id, idem_key, route, request_hash, status_code, response_body, created_at
`

type CreateIdempotentRequestParams struct {
	MerchantID   uuid.UUID `json:"merchant_id"`
	IdemKey      string    `json:"idem_key"`
	Route        string    `json:"route"`
	RequestHash  string    `json:"request_hash"`
	StatusCode   int32     `json:"status_code"`
	ResponseBody []byte    `json:"response_body"`
}

func (q *Queries) CreateIdempotentRequest(ctx context.Context, arg CreateIdempotentRequestParams) (IdempotentRequest, error) {
	row := q.db.QueryRow(ctx, createIdempotentRequest,
		arg.MerchantID,
		arg.IdemKey,
		arg.Route,
		arg.RequestHash,
		arg.StatusCode,
		arg.ResponseBody,
	)
	var i IdempotentRequest
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.IdemKey,
		&i.Route,
		&i.RequestHash,
		&i.StatusCode,
		&i.ResponseBody,
		&i.CreatedAt,
	)
	return i, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
    merchant_id, idempotency_key, status, authorized_amount,
    fee_bps, fee_fixed, external_ref, expires_at
) VALUES ($1, $2, 'authorized', $3, $4, $5, $6,
          now() + make_interval(secs => $7))
RETURNING id, merchant_id, idempotency_key, status, authorized_amount, captured_amount, fee_bps, fee_fixed, fee_amount, refunded_amount, refunded_fee, currency, external_ref, authorized_at, captured_at, voided_at, expires_at, created_at, updated_at, settlement_batch_id
`

type CreatePaymentParams struct {
	MerchantID       uuid.UUID   `json:"merchant_id"`
	IdempotencyKey   string      `json:"idempotency_key"`
	AuthorizedAmount int64       `json:"authorized_amount"`
	FeeBps           int32       `json:"fee_bps"`
	FeeFixed         int64       `json:"fee_fixed"`
	ExternalRef      pgtype.Text `json:"external_ref"`
	Secs             float64     `json:"secs"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.MerchantID,
		arg.IdempotencyKey,
		arg.AuthorizedAmount,
		arg.FeeBps,
		arg.FeeFixed,
		arg.ExternalRef,
		arg.Secs,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.IdempotencyKey,
		&i.Status,
		&i.AuthorizedAmount,
		&i.CapturedAmount,
		&i.FeeBps,
		&i.FeeFixed,
		&i.FeeAmount,
		&i.RefundedAmount,
		&i.RefundedFee,
		&i.Currency,
		&i.ExternalRef,
		&i.AuthorizedAt,
		&i.CapturedAt,
		&i.VoidedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SettlementBatchID,
	)
	return i, err
}

const createRefund = `-- name: CreateRefund :one
INSERT INTO refunds (payment_id, merchant_id, idempotency_key, amount, fee_refund, reason)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, payment_id, merchant_id, idempotency_key, amount, fee_refund, reason, created_at
`

type CreateRefundParams struct {
	PaymentID      uuid.UUID   `json:"payment_id"`
	MerchantID     uuid.UUID   `json:"merchant_id"`
	IdempotencyKey string      `json:"idempotency_key"`
	Amount         int64       `json:"amount"`
	FeeRefund      int64       `json:"fee_refund"`
	Reason         pgtype.Text `json:"reason"`
}

func (q *Queries) CreateRefund(ctx context.Context, arg CreateRefundParams) (Refund, error) {
	row := q.db.QueryRow(ctx, createRefund,
		arg.PaymentID,
		arg.MerchantID,
		arg.IdempotencyKey,
		arg.Amount,
		arg.FeeRefund,
		arg.Reason,
	)
	var i Refund
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.MerchantID,
		&i.IdempotencyKey,
		&i.Amount,
		&i.FeeRefund,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const getIdempotentRequest = `-- name: GetIdempotentRequest :one
SELECT id, merchant_id, idem_key, route, request_hash, status_code, response_body, created_at FROM idempotent_requests WHERE merchant_id = $1 AND idem_key = $2
`

type GetIdempotentRequestParams struct {
	MerchantID uuid.UUID `json:"merchant_id"`
	IdemKey    string    `json:"idem_key"`
}

func (q *Queries) GetIdempotentRequest(ctx context.Context, arg GetIdempotentRequestParams) (IdempotentRequest, error) {
	row := q.db.QueryRow(ctx, getIdempotentRequest, arg.MerchantID, arg.IdemKey)
	var i IdempotentRequest
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.IdemKey,
		&i.Route,
		&i.RequestHash,
		&i.StatusCode,
		&i.ResponseBody,
		&i.CreatedAt,
	)
	return i, err
}

const getPayment = `-- name: GetPayment :one
SELECT id, merchant_id, idempotency_key, status, authorized_amount, captured_amount, fee_bps, fee_fixed, fee_amount, refunded_amount, refunded_fee, currency, external_ref, authorized_at, captured_at, voided_at, expires_at, created_at, updated_at, settlement_batch_id FROM payments WHERE id = $1 AND merchant_id = $2
`

type GetPaymentParams struct {
	ID         uuid.UUID `json:"id"`
	MerchantID uuid.UUID `json:"merchant_id"`
}

func (q *Queries) GetPayment(ctx context.Context, arg GetPaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, getPayment, arg.ID, arg.MerchantID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.IdempotencyKey,
		&i.Status,
		&i.AuthorizedAmount,
		&i.CapturedAmount,
		&i.FeeBps,
		&i.FeeFixed,
		&i.FeeAmount,
		&i.RefundedAmount,
		&i.RefundedFee,
		&i.Currency,
		&i.ExternalRef,
		&i.AuthorizedAt,
		&i.CapturedAt,
		&i.VoidedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SettlementBatchID,
	)
	return i, err
}

const getPaymentForUpdate = `-- name: GetPaymentForUpdate :one
SELECT id, merchant_id, idempotency_key, status, authorized_amount, captured_amount, fee_bps, fee_fixed, fee_amount, refunded_amount, refunded_fee, currency, external_ref, authorized_at, captured_at, voided_at, expires_at, created_at, updated_at, settlement_batch_id FROM payments WHERE id = $1 AND merchant_id = $2 FOR UPDATE
`

type GetPaymentForUpdateParams struct {
	ID         uuid.UUID `json:"id"`
	MerchantID uuid.UUID `json:"merchant_id"`
}

func (q *Queries) GetPaymentForUpdate(ctx context.Context, arg GetPaymentForUpdateParams) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentForUpdate, arg.ID, arg.MerchantID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.IdempotencyKey,
		&i.Status,
		&i.AuthorizedAmount,
		&i.CapturedAmount,
		&i.FeeBps,
		&i.FeeFixed,
		&i.FeeAmount,
		&i.RefundedAmount,
		&i.RefundedFee,
		&i.Currency,
		&i.ExternalRef,
		&i.AuthorizedAt,
		&i.CapturedAt,
		&i.VoidedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SettlementBatchID,
	)
	return i, err
}

const getRefundByIdemKey = `-- name: GetRefundByIdemKey :one
SELECT id, payment_id, merchant_id, idempotency_key, amount, fee_refund, reason, created_at FROM refunds WHERE merchant_id = $1 AND idempotency_key = $2
`

type GetRefundByIdemKeyParams struct {
	MerchantID     uuid.UUID `json:"merchant_id"`
	IdempotencyKey string    `json:"idempotency_key"`
}

func (q *Queries) GetRefundByIdemKey(ctx context.Context, arg GetRefundByIdemKeyParams) (Refund, error) {
	row := q.db.QueryRow(ctx, getRefundByIdemKey, arg.MerchantID, arg.IdempotencyKey)
	var i Refund
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.MerchantID,
		&i.IdempotencyKey,
		&i.Amount,
		&i.FeeRefund,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const listUnsettledCapturedPayments = `-- name: ListUnsettledCapturedPayments :many
SELECT id, merchant_id, idempotency_key, status, authorized_amount, captured_amount, fee_bps, fee_fixed, fee_amount, refunded_amount, refunded_fee, currency, external_ref, authorized_at, captured_at, voided_at, expires_at, created_at, updated_at, settlement_batch_id FROM payments
WHERE merchant_id = $1
  AND captured_at IS NOT NULL
  AND captured_at < ($2::timestamptz)
  AND settlement_batch_id IS NULL
  AND status IN ('captured','partially_refunded')
ORDER BY captured_at
LIMIT $3
FOR UPDATE SKIP LOCKED
`

type ListUnsettledCapturedPaymentsParams struct {
	MerchantID uuid.UUID          `json:"merchant_id"`
	Column2    pgtype.Timestamptz `json:"column_2"`
	Limit      int32              `json:"limit"`
}

func (q *Queries) ListUnsettledCapturedPayments(ctx context.Context, arg ListUnsettledCapturedPaymentsParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listUnsettledCapturedPayments, arg.MerchantID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.IdempotencyKey,
			&i.Status,
			&i.AuthorizedAmount,
			&i.CapturedAmount,
			&i.FeeBps,
			&i.FeeFixed,
			&i.FeeAmount,
			&i.RefundedAmount,
			&i.RefundedFee,
			&i.Currency,
			&i.ExternalRef,
			&i.AuthorizedAt,
			&i.CapturedAt,
			&i.VoidedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SettlementBatchID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPaymentSettled = `-- name: MarkPaymentSettled :many
UPDATE payments
SET settlement_batch_id = $3,
    status = 'settled'
WHERE id = ANY($1::uuid[]) AND merchant_id = $2
  AND status IN ('captured','partially_refunded')
RETURNING id
`

type MarkPaymentSettledParams struct {
	Column1           []uuid.UUID `json:"column_1"`
	MerchantID        uuid.UUID   `json:"merchant_id"`
	SettlementBatchID *uuid.UUID  `json:"settlement_batch_id"`
}

func (q *Queries) MarkPaymentSettled(ctx context.Context, arg MarkPaymentSettledParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, markPaymentSettled, arg.Column1, arg.MerchantID, arg.SettlementBatchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const voidPayment = `-- name: VoidPayment :one
UPDATE payments
SET status = 'voided', voided_at = now()
WHERE id = $1 AND merchant_id = $2 AND status = 'authorized'
RETURNING id, merchant_id, idempotency_key, status, authorized_amount, captured_amount, fee_bps, fee_fixed, fee_amount, refunded_amount, refunded_fee, currency, external_ref, authorized_at, captured_at, voided_at, expires_at, created_at, updated_at, settlement_batch_id
`

type VoidPaymentParams struct {
	ID         uuid.UUID `json:"id"`
	MerchantID uuid.UUID `json:"merchant_id"`
}

func (q *Queries) VoidPayment(ctx context.Context, arg VoidPaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, voidPayment, arg.ID, arg.MerchantID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.IdempotencyKey,
		&i.Status,
		&i.AuthorizedAmount,
		&i.CapturedAmount,
		&i.FeeBps,
		&i.FeeFixed,
		&i.FeeAmount,
		&i.RefundedAmount,
		&i.RefundedFee,
		&i.Currency,
		&i.ExternalRef,
		&i.AuthorizedAt,
		&i.CapturedAt,
		&i.VoidedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SettlementBatchID,
	)
	return i, err
}
