// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AccountBalance(ctx context.Context, accountID uuid.UUID) (int64, error)
	AggregatePaymentsForBatchDay(ctx context.Context, arg AggregatePaymentsForBatchDayParams) (AggregatePaymentsForBatchDayRow, error)
	ApplyRefund(ctx context.Context, arg ApplyRefundParams) (Payment, error)
	CapturePayment(ctx context.Context, arg CapturePaymentParams) (Payment, error)
	ChannelCaptureTotals(ctx context.Context, arg ChannelCaptureTotalsParams) (ChannelCaptureTotalsRow, error)
	ChannelRefundTotals(ctx context.Context, arg ChannelRefundTotalsParams) (ChannelRefundTotalsRow, error)
	CompleteReconRun(ctx context.Context, arg CompleteReconRunParams) (ReconciliationRun, error)
	CompleteSettlementBatch(ctx context.Context, arg CompleteSettlementBatchParams) (SettlementBatch, error)
	CountPaymentsForBatchDay(ctx context.Context, arg CountPaymentsForBatchDayParams) (int32, error)
	CountUnsettledCapturedPayments(ctx context.Context, arg CountUnsettledCapturedPaymentsParams) (int32, error)
	CreateIdempotentRequest(ctx context.Context, arg CreateIdempotentRequestParams) (IdempotentRequest, error)
	CreateLedgerAccount(ctx context.Context, arg CreateLedgerAccountParams) (LedgerAccount, error)
	CreateMerchant(ctx context.Context, arg CreateMerchantParams) (Merchant, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreateRefund(ctx context.Context, arg CreateRefundParams) (Refund, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteReconItems(ctx context.Context, runID uuid.UUID) error
	EntriesForRef(ctx context.Context, arg EntriesForRefParams) ([]LedgerEntry, error)
	FailReconRun(ctx context.Context, id uuid.UUID) error
	FailSettlementBatch(ctx context.Context, id uuid.UUID) error
	GetIdempotentRequest(ctx context.Context, arg GetIdempotentRequestParams) (IdempotentRequest, error)
	GetLedgerAccountByCode(ctx context.Context, code string) (LedgerAccount, error)
	GetMerchant(ctx context.Context, id uuid.UUID) (Merchant, error)
	GetMerchantByAPIKeyHash(ctx context.Context, apiKeyHash pgtype.Text) (Merchant, error)
	GetPayment(ctx context.Context, arg GetPaymentParams) (Payment, error)
	GetPaymentAnyMerchant(ctx context.Context, id uuid.UUID) (Payment, error)
	GetPaymentForUpdate(ctx context.Context, arg GetPaymentForUpdateParams) (Payment, error)
	GetReconRun(ctx context.Context, arg GetReconRunParams) (ReconciliationRun, error)
	GetReconRunForUpdate(ctx context.Context, arg GetReconRunForUpdateParams) (ReconciliationRun, error)
	GetRefundByIdemKey(ctx context.Context, arg GetRefundByIdemKeyParams) (Refund, error)
	GetSettlementBatch(ctx context.Context, id uuid.UUID) (SettlementBatch, error)
	GetSettlementBatchForUpdate(ctx context.Context, arg GetSettlementBatchForUpdateParams) (SettlementBatch, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GlobalAccountForUpdate(ctx context.Context, code string) (LedgerAccount, error)
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	InsertChannelEvent(ctx context.Context, arg InsertChannelEventParams) error
	InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) error
	InsertReconItem(ctx context.Context, arg InsertReconItemParams) error
	InternalCaptureTotals(ctx context.Context, arg InternalCaptureTotalsParams) (InternalCaptureTotalsRow, error)
	InternalRefundTotals(ctx context.Context, arg InternalRefundTotalsParams) (InternalRefundTotalsRow, error)
	ListAllReconRuns(ctx context.Context, arg ListAllReconRunsParams) ([]ListAllReconRunsRow, error)
	ListAllRefundsForMerchant(ctx context.Context, arg ListAllRefundsForMerchantParams) ([]Refund, error)
	ListAllSettlementBatches(ctx context.Context, arg ListAllSettlementBatchesParams) ([]ListAllSettlementBatchesRow, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	ListAuditLogsForMerchant(ctx context.Context, arg ListAuditLogsForMerchantParams) ([]AuditLog, error)
	// One row per (merchant, capture-day) that still has un-batched captures,
	// restricted to days entirely before the cutoff (day end <= cutoff), so the
	// worker never settles a day that can still receive events.
	ListMerchantDaysToSettle(ctx context.Context, cutoff pgtype.Timestamptz) ([]ListMerchantDaysToSettleRow, error)
	ListMerchants(ctx context.Context) ([]Merchant, error)
	ListPaymentsAnyMerchant(ctx context.Context, arg ListPaymentsAnyMerchantParams) ([]Payment, error)
	ListPaymentsForMerchant(ctx context.Context, arg ListPaymentsForMerchantParams) ([]Payment, error)
	ListPaymentsInBatch(ctx context.Context, settlementBatchID *uuid.UUID) ([]Payment, error)
	ListReconItems(ctx context.Context, runID uuid.UUID) ([]ReconciliationItem, error)
	ListReconRunsForMerchant(ctx context.Context, arg ListReconRunsForMerchantParams) ([]ReconciliationRun, error)
	ListRefundsForPayment(ctx context.Context, arg ListRefundsForPaymentParams) ([]Refund, error)
	ListRefundsForPaymentAnyMerchant(ctx context.Context, paymentID uuid.UUID) ([]Refund, error)
	ListSettlementBatches(ctx context.Context, arg ListSettlementBatchesParams) ([]SettlementBatch, error)
	ListUnsettledCapturedPayments(ctx context.Context, arg ListUnsettledCapturedPaymentsParams) ([]Payment, error)
	ListUsers(ctx context.Context) ([]User, error)
	ListUsersByMerchant(ctx context.Context, merchantID *uuid.UUID) ([]User, error)
	MarkBatchPaymentsSettled(ctx context.Context, arg MarkBatchPaymentsSettledParams) error
	MarkPaymentSettled(ctx context.Context, arg MarkPaymentSettledParams) ([]uuid.UUID, error)
	MerchantsWithCaptureOn(ctx context.Context, day pgtype.Date) ([]uuid.UUID, error)
	MerchantsWithRefundOn(ctx context.Context, day pgtype.Date) ([]uuid.UUID, error)
	PayableAccountForUpdate(ctx context.Context, dollar_1 string) (LedgerAccount, error)
	// Locks the exact set of payments that belong in this (merchant, day) batch.
	// SKIP LOCKED lets two workers on different merchants/days proceed in parallel.
	PaymentsForBatchDay(ctx context.Context, arg PaymentsForBatchDayParams) ([]Payment, error)
	RotateMerchantAPIKey(ctx context.Context, arg RotateMerchantAPIKeyParams) (Merchant, error)
	SetMerchantStatus(ctx context.Context, arg SetMerchantStatusParams) (Merchant, error)
	UnbalancedPostingCount(ctx context.Context) (int32, error)
	UpsertReconRun(ctx context.Context, arg UpsertReconRunParams) (ReconciliationRun, error)
	UpsertSettlementBatch(ctx context.Context, arg UpsertSettlementBatchParams) (SettlementBatch, error)
	VoidPayment(ctx context.Context, arg VoidPaymentParams) (Payment, error)
}

var _ Querier = (*Queries)(nil)
