// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: reads.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const getPaymentAnyMerchant = `-- name: GetPaymentAnyMerchant :one
SELECT id, merchant_id, idempotency_key, status, authorized_amount, captured_amount, fee_bps, fee_fixed, fee_amount, refunded_amount, refunded_fee, currency, external_ref, authorized_at, captured_at, voided_at, expires_at, created_at, updated_at, settlement_batch_id FROM payments WHERE id = $1
`

func (q *Queries) GetPaymentAnyMerchant(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentAnyMerchant, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.IdempotencyKey,
		&i.Status,
		&i.AuthorizedAmount,
		&i.CapturedAmount,
		&i.FeeBps,
		&i.FeeFixed,
		&i.FeeAmount,
		&i.RefundedAmount,
		&i.RefundedFee,
		&i.Currency,
		&i.ExternalRef,
		&i.AuthorizedAt,
		&i.CapturedAt,
		&i.VoidedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SettlementBatchID,
	)
	return i, err
}

const listAllRefundsForMerchant = `-- name: ListAllRefundsForMerchant :many
SELECT id, payment_id, merchant_id, idempotency_key, amount, fee_refund, reason, created_at FROM refunds WHERE merchant_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListAllRefundsForMerchantParams struct {
	MerchantID uuid.UUID `json:"merchant_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) ListAllRefundsForMerchant(ctx context.Context, arg ListAllRefundsForMerchantParams) ([]Refund, error) {
	rows, err := q.db.Query(ctx, listAllRefundsForMerchant, arg.MerchantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Refund{}
	for rows.Next() {
		var i Refund
		if err := rows.Scan(
			&i.ID,
			&i.PaymentID,
			&i.MerchantID,
			&i.IdempotencyKey,
			&i.Amount,
			&i.FeeRefund,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsAnyMerchant = `-- name: ListPaymentsAnyMerchant :many
SELECT id, merchant_id, idempotency_key, status, authorized_amount, captured_amount, fee_bps, fee_fixed, fee_amount, refunded_amount, refunded_fee, currency, external_ref, authorized_at, captured_at, voided_at, expires_at, created_at, updated_at, settlement_batch_id FROM payments
WHERE ($1::uuid IS NULL OR merchant_id = $1::uuid)
ORDER BY created_at DESC LIMIT $3 OFFSET $2
`

type ListPaymentsAnyMerchantParams struct {
	MerchantID *uuid.UUID `json:"merchant_id"`
	RowOffset  int32      `json:"row_offset"`
	RowLimit   int32      `json:"row_limit"`
}

func (q *Queries) ListPaymentsAnyMerchant(ctx context.Context, arg ListPaymentsAnyMerchantParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsAnyMerchant, arg.MerchantID, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.IdempotencyKey,
			&i.Status,
			&i.AuthorizedAmount,
			&i.CapturedAmount,
			&i.FeeBps,
			&i.FeeFixed,
			&i.FeeAmount,
			&i.RefundedAmount,
			&i.RefundedFee,
			&i.Currency,
			&i.ExternalRef,
			&i.AuthorizedAt,
			&i.CapturedAt,
			&i.VoidedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SettlementBatchID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsForMerchant = `-- name: ListPaymentsForMerchant :many
SELECT id, merchant_id, idempotency_key, status, authorized_amount, captured_amount, fee_bps, fee_fixed, fee_amount, refunded_amount, refunded_fee, currency, external_ref, authorized_at, captured_at, voided_at, expires_at, created_at, updated_at, settlement_batch_id FROM payments WHERE merchant_id = $1
ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListPaymentsForMerchantParams struct {
	MerchantID uuid.UUID `json:"merchant_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) ListPaymentsForMerchant(ctx context.Context, arg ListPaymentsForMerchantParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsForMerchant, arg.MerchantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.IdempotencyKey,
			&i.Status,
			&i.AuthorizedAmount,
			&i.CapturedAmount,
			&i.FeeBps,
			&i.FeeFixed,
			&i.FeeAmount,
			&i.RefundedAmount,
			&i.RefundedFee,
			&i.Currency,
			&i.ExternalRef,
			&i.AuthorizedAt,
			&i.CapturedAt,
			&i.VoidedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SettlementBatchID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRefundsForPayment = `-- name: ListRefundsForPayment :many
SELECT id, payment_id, merchant_id, idempotency_key, amount, fee_refund, reason, created_at FROM refunds WHERE payment_id = $1 AND merchant_id = $2 ORDER BY created_at
`

type ListRefundsForPaymentParams struct {
	PaymentID  uuid.UUID `json:"payment_id"`
	MerchantID uuid.UUID `json:"merchant_id"`
}

func (q *Queries) ListRefundsForPayment(ctx context.Context, arg ListRefundsForPaymentParams) ([]Refund, error) {
	rows, err := q.db.Query(ctx, listRefundsForPayment, arg.PaymentID, arg.MerchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Refund{}
	for rows.Next() {
		var i Refund
		if err := rows.Scan(
			&i.ID,
			&i.PaymentID,
			&i.MerchantID,
			&i.IdempotencyKey,
			&i.Amount,
			&i.FeeRefund,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRefundsForPaymentAnyMerchant = `-- name: ListRefundsForPaymentAnyMerchant :many
SELECT id, payment_id, merchant_id, idempotency_key, amount, fee_refund, reason, created_at FROM refunds WHERE payment_id = $1 ORDER BY created_at
`

func (q *Queries) ListRefundsForPaymentAnyMerchant(ctx context.Context, paymentID uuid.UUID) ([]Refund, error) {
	rows, err := q.db.Query(ctx, listRefundsForPaymentAnyMerchant, paymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Refund{}
	for rows.Next() {
		var i Refund
		if err := rows.Scan(
			&i.ID,
			&i.PaymentID,
			&i.MerchantID,
			&i.IdempotencyKey,
			&i.Amount,
			&i.FeeRefund,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
