// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: settlement.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const aggregatePaymentsForBatchDay = `-- name: AggregatePaymentsForBatchDay :one
SELECT
    COUNT(*)::int                                   AS payment_count,
    COALESCE(SUM(captured_amount),0)::bigint        AS gross_captured,
    COALESCE(SUM(fee_amount),0)::bigint             AS total_fees,
    COALESCE(SUM(refunded_amount),0)::bigint        AS total_refunds,
    COALESCE(SUM(refunded_fee),0)::bigint           AS refunded_fees,
    COALESCE(SUM(captured_amount - refunded_amount
                 - fee_amount + refunded_fee),0)::bigint AS net_payable
FROM payments
WHERE merchant_id = $1
  AND (captured_at AT TIME ZONE 'UTC')::date = $2::date
  AND settlement_batch_id IS NULL
  AND captured_at IS NOT NULL
`

type AggregatePaymentsForBatchDayParams struct {
	MerchantID uuid.UUID   `json:"merchant_id"`
	BatchDate  pgtype.Date `json:"batch_date"`
}

type AggregatePaymentsForBatchDayRow struct {
	PaymentCount  int32 `json:"payment_count"`
	GrossCaptured int64 `json:"gross_captured"`
	TotalFees     int64 `json:"total_fees"`
	TotalRefunds  int64 `json:"total_refunds"`
	RefundedFees  int64 `json:"refunded_fees"`
	NetPayable    int64 `json:"net_payable"`
}

func (q *Queries) AggregatePaymentsForBatchDay(ctx context.Context, arg AggregatePaymentsForBatchDayParams) (AggregatePaymentsForBatchDayRow, error) {
	row := q.db.QueryRow(ctx, aggregatePaymentsForBatchDay, arg.MerchantID, arg.BatchDate)
	var i AggregatePaymentsForBatchDayRow
	err := row.Scan(
		&i.PaymentCount,
		&i.GrossCaptured,
		&i.TotalFees,
		&i.TotalRefunds,
		&i.RefundedFees,
		&i.NetPayable,
	)
	return i, err
}

const completeSettlementBatch = `-- name: CompleteSettlementBatch :one
UPDATE settlement_batches
SET status = 'completed',
    gross_captured = $1,
    total_fees = $2,
    total_refunds = $3,
    refunded_fees = $4,
    net_amount = $5,
    payment_count = $6,
    completed_at = now()
WHERE id = $7 AND merchant_id = $8 AND status = 'processing'
RETURNING id, merchant_id, batch_date, status, gross_captured, total_fees, total_refunds, refunded_fees, net_amount, payment_count, locked_by, started_at, completed_at
`

type CompleteSettlementBatchParams struct {
	GrossCaptured int64     `json:"gross_captured"`
	TotalFees     int64     `json:"total_fees"`
	TotalRefunds  int64     `json:"total_refunds"`
	RefundedFees  int64     `json:"refunded_fees"`
	NetAmount     int64     `json:"net_amount"`
	PaymentCount  int32     `json:"payment_count"`
	ID            uuid.UUID `json:"id"`
	MerchantID    uuid.UUID `json:"merchant_id"`
}

func (q *Queries) CompleteSettlementBatch(ctx context.Context, arg CompleteSettlementBatchParams) (SettlementBatch, error) {
	row := q.db.QueryRow(ctx, completeSettlementBatch,
		arg.GrossCaptured,
		arg.TotalFees,
		arg.TotalRefunds,
		arg.RefundedFees,
		arg.NetAmount,
		arg.PaymentCount,
		arg.ID,
		arg.MerchantID,
	)
	var i SettlementBatch
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.BatchDate,
		&i.Status,
		&i.GrossCaptured,
		&i.TotalFees,
		&i.TotalRefunds,
		&i.RefundedFees,
		&i.NetAmount,
		&i.PaymentCount,
		&i.LockedBy,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const countPaymentsForBatchDay = `-- name: CountPaymentsForBatchDay :one
SELECT COUNT(*)::int FROM payments
WHERE merchant_id = $1
  AND (captured_at AT TIME ZONE 'UTC')::date = $2::date
  AND settlement_batch_id IS NULL
  AND captured_at IS NOT NULL
`

type CountPaymentsForBatchDayParams struct {
	MerchantID uuid.UUID   `json:"merchant_id"`
	BatchDate  pgtype.Date `json:"batch_date"`
}

func (q *Queries) CountPaymentsForBatchDay(ctx context.Context, arg CountPaymentsForBatchDayParams) (int32, error) {
	row := q.db.QueryRow(ctx, countPaymentsForBatchDay, arg.MerchantID, arg.BatchDate)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const failSettlementBatch = `-- name: FailSettlementBatch :exec
UPDATE settlement_batches SET status = 'failed' WHERE id = $1 AND status = 'processing'
`

func (q *Queries) FailSettlementBatch(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, failSettlementBatch, id)
	return err
}

const getSettlementBatch = `-- name: GetSettlementBatch :one
SELECT id, merchant_id, batch_date, status, gross_captured, total_fees, total_refunds, refunded_fees, net_amount, payment_count, locked_by, started_at, completed_at FROM settlement_batches WHERE id = $1
`

func (q *Queries) GetSettlementBatch(ctx context.Context, id uuid.UUID) (SettlementBatch, error) {
	row := q.db.QueryRow(ctx, getSettlementBatch, id)
	var i SettlementBatch
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.BatchDate,
		&i.Status,
		&i.GrossCaptured,
		&i.TotalFees,
		&i.TotalRefunds,
		&i.RefundedFees,
		&i.NetAmount,
		&i.PaymentCount,
		&i.LockedBy,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getSettlementBatchForUpdate = `-- name: GetSettlementBatchForUpdate :one
SELECT id, merchant_id, batch_date, status, gross_captured, total_fees, total_refunds, refunded_fees, net_amount, payment_count, locked_by, started_at, completed_at FROM settlement_batches WHERE merchant_id = $1 AND batch_date = $2 FOR UPDATE
`

type GetSettlementBatchForUpdateParams struct {
	MerchantID uuid.UUID   `json:"merchant_id"`
	BatchDate  pgtype.Date `json:"batch_date"`
}

func (q *Queries) GetSettlementBatchForUpdate(ctx context.Context, arg GetSettlementBatchForUpdateParams) (SettlementBatch, error) {
	row := q.db.QueryRow(ctx, getSettlementBatchForUpdate, arg.MerchantID, arg.BatchDate)
	var i SettlementBatch
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.BatchDate,
		&i.Status,
		&i.GrossCaptured,
		&i.TotalFees,
		&i.TotalRefunds,
		&i.RefundedFees,
		&i.NetAmount,
		&i.PaymentCount,
		&i.LockedBy,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listAllSettlementBatches = `-- name: ListAllSettlementBatches :many
SELECT sb.id, sb.merchant_id, sb.batch_date, sb.status, sb.gross_captured, sb.total_fees, sb.total_refunds, sb.refunded_fees, sb.net_amount, sb.payment_count, sb.locked_by, sb.started_at, sb.completed_at, m.name AS merchant_name
FROM settlement_batches sb JOIN merchants m ON m.id = sb.merchant_id
ORDER BY batch_date DESC, m.name LIMIT $1 OFFSET $2
`

type ListAllSettlementBatchesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAllSettlementBatchesRow struct {
	ID            uuid.UUID          `json:"id"`
	MerchantID    uuid.UUID          `json:"merchant_id"`
	BatchDate     pgtype.Date        `json:"batch_date"`
	Status        string             `json:"status"`
	GrossCaptured int64              `json:"gross_captured"`
	TotalFees     int64              `json:"total_fees"`
	TotalRefunds  int64              `json:"total_refunds"`
	RefundedFees  int64              `json:"refunded_fees"`
	NetAmount     int64              `json:"net_amount"`
	PaymentCount  int32              `json:"payment_count"`
	LockedBy      pgtype.Text        `json:"locked_by"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	MerchantName  string             `json:"merchant_name"`
}

func (q *Queries) ListAllSettlementBatches(ctx context.Context, arg ListAllSettlementBatchesParams) ([]ListAllSettlementBatchesRow, error) {
	rows, err := q.db.Query(ctx, listAllSettlementBatches, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllSettlementBatchesRow{}
	for rows.Next() {
		var i ListAllSettlementBatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.BatchDate,
			&i.Status,
			&i.GrossCaptured,
			&i.TotalFees,
			&i.TotalRefunds,
			&i.RefundedFees,
			&i.NetAmount,
			&i.PaymentCount,
			&i.LockedBy,
			&i.StartedAt,
			&i.CompletedAt,
			&i.MerchantName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMerchantDaysToSettle = `-- name: ListMerchantDaysToSettle :many
SELECT DISTINCT p.merchant_id,
       m.name AS merchant_name,
       (p.captured_at AT TIME ZONE 'UTC')::date AS day
FROM payments p
JOIN merchants m ON m.id = p.merchant_id
WHERE p.captured_at IS NOT NULL AND p.settlement_batch_id IS NULL
  AND (p.captured_at AT TIME ZONE 'UTC')::date < ($1::timestamptz AT TIME ZONE 'UTC')::date
ORDER BY day, p.merchant_id
`

type ListMerchantDaysToSettleRow struct {
	MerchantID   uuid.UUID   `json:"merchant_id"`
	MerchantName string      `json:"merchant_name"`
	Day          pgtype.Date `json:"day"`
}

// One row per (merchant, capture-day) that still has un-batched captures,
// restricted to days entirely before the cutoff (day end <= cutoff), so the
// worker never settles a day that can still receive events.
func (q *Queries) ListMerchantDaysToSettle(ctx context.Context, cutoff pgtype.Timestamptz) ([]ListMerchantDaysToSettleRow, error) {
	rows, err := q.db.Query(ctx, listMerchantDaysToSettle, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMerchantDaysToSettleRow{}
	for rows.Next() {
		var i ListMerchantDaysToSettleRow
		if err := rows.Scan(&i.MerchantID, &i.MerchantName, &i.Day); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsInBatch = `-- name: ListPaymentsInBatch :many
SELECT id, merchant_id, idempotency_key, status, authorized_amount, captured_amount, fee_bps, fee_fixed, fee_amount, refunded_amount, refunded_fee, currency, external_ref, authorized_at, captured_at, voided_at, expires_at, created_at, updated_at, settlement_batch_id FROM payments WHERE settlement_batch_id = $1 ORDER BY captured_at
`

func (q *Queries) ListPaymentsInBatch(ctx context.Context, settlementBatchID *uuid.UUID) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsInBatch, settlementBatchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.IdempotencyKey,
			&i.Status,
			&i.AuthorizedAmount,
			&i.CapturedAmount,
			&i.FeeBps,
			&i.FeeFixed,
			&i.FeeAmount,
			&i.RefundedAmount,
			&i.RefundedFee,
			&i.Currency,
			&i.ExternalRef,
			&i.AuthorizedAt,
			&i.CapturedAt,
			&i.VoidedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SettlementBatchID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSettlementBatches = `-- name: ListSettlementBatches :many
SELECT id, merchant_id, batch_date, status, gross_captured, total_fees, total_refunds, refunded_fees, net_amount, payment_count, locked_by, started_at, completed_at FROM settlement_batches WHERE merchant_id = $1
ORDER BY batch_date DESC LIMIT $2 OFFSET $3
`

type ListSettlementBatchesParams struct {
	MerchantID uuid.UUID `json:"merchant_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) ListSettlementBatches(ctx context.Context, arg ListSettlementBatchesParams) ([]SettlementBatch, error) {
	rows, err := q.db.Query(ctx, listSettlementBatches, arg.MerchantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SettlementBatch{}
	for rows.Next() {
		var i SettlementBatch
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.BatchDate,
			&i.Status,
			&i.GrossCaptured,
			&i.TotalFees,
			&i.TotalRefunds,
			&i.RefundedFees,
			&i.NetAmount,
			&i.PaymentCount,
			&i.LockedBy,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBatchPaymentsSettled = `-- name: MarkBatchPaymentsSettled :exec
UPDATE payments
SET settlement_batch_id = $1,
    status = CASE WHEN refunded_amount = captured_amount THEN status ELSE 'settled' END
WHERE merchant_id = $2
  AND (captured_at AT TIME ZONE 'UTC')::date = $3::date
  AND settlement_batch_id IS NULL
  AND captured_at IS NOT NULL
`

type MarkBatchPaymentsSettledParams struct {
	BatchID    *uuid.UUID  `json:"batch_id"`
	MerchantID uuid.UUID   `json:"merchant_id"`
	BatchDate  pgtype.Date `json:"batch_date"`
}

func (q *Queries) MarkBatchPaymentsSettled(ctx context.Context, arg MarkBatchPaymentsSettledParams) error {
	_, err := q.db.Exec(ctx, markBatchPaymentsSettled, arg.BatchID, arg.MerchantID, arg.BatchDate)
	return err
}

const paymentsForBatchDay = `-- name: PaymentsForBatchDay :many
SELECT id, merchant_id, idempotency_key, status, authorized_amount, captured_amount, fee_bps, fee_fixed, fee_amount, refunded_amount, refunded_fee, currency, external_ref, authorized_at, captured_at, voided_at, expires_at, created_at, updated_at, settlement_batch_id FROM payments
WHERE merchant_id = $1
  AND (captured_at AT TIME ZONE 'UTC')::date = $2::date
  AND settlement_batch_id IS NULL
  AND captured_at IS NOT NULL
ORDER BY captured_at
LIMIT $3
FOR UPDATE SKIP LOCKED
`

type PaymentsForBatchDayParams struct {
	MerchantID uuid.UUID   `json:"merchant_id"`
	BatchDate  pgtype.Date `json:"batch_date"`
	RowLimit   int32       `json:"row_limit"`
}

// Locks the exact set of payments that belong in this (merchant, day) batch.
// SKIP LOCKED lets two workers on different merchants/days proceed in parallel.
func (q *Queries) PaymentsForBatchDay(ctx context.Context, arg PaymentsForBatchDayParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, paymentsForBatchDay, arg.MerchantID, arg.BatchDate, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.IdempotencyKey,
			&i.Status,
			&i.AuthorizedAmount,
			&i.CapturedAmount,
			&i.FeeBps,
			&i.FeeFixed,
			&i.FeeAmount,
			&i.RefundedAmount,
			&i.RefundedFee,
			&i.Currency,
			&i.ExternalRef,
			&i.AuthorizedAt,
			&i.CapturedAt,
			&i.VoidedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SettlementBatchID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSettlementBatch = `-- name: UpsertSettlementBatch :one
INSERT INTO settlement_batches (merchant_id, batch_date, status, locked_by)
VALUES ($1, $2, 'processing', $3)
ON CONFLICT (merchant_id, batch_date) DO NOTHING
RETURNING id, merchant_id, batch_date, status, gross_captured, total_fees, total_refunds, refunded_fees, net_amount, payment_count, locked_by, started_at, completed_at
`

type UpsertSettlementBatchParams struct {
	MerchantID uuid.UUID   `json:"merchant_id"`
	BatchDate  pgtype.Date `json:"batch_date"`
	LockedBy   pgtype.Text `json:"locked_by"`
}

func (q *Queries) UpsertSettlementBatch(ctx context.Context, arg UpsertSettlementBatchParams) (SettlementBatch, error) {
	row := q.db.QueryRow(ctx, upsertSettlementBatch, arg.MerchantID, arg.BatchDate, arg.LockedBy)
	var i SettlementBatch
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.BatchDate,
		&i.Status,
		&i.GrossCaptured,
		&i.TotalFees,
		&i.TotalRefunds,
		&i.RefundedFees,
		&i.NetAmount,
		&i.PaymentCount,
		&i.LockedBy,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}
