# Generated by Django 5.0.14 on 2026-09-21 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('REGISTER', 'Register'), ('LOGIN', 'Login'), ('MARKET_CREATE', 'Market created'), ('FEE_UPDATE', 'Fees updated'), ('MAINTENANCE_ON', 'Maintenance on'), ('MAINTENANCE_OFF', 'Maintenance off'), ('ORDER_REJECTED', 'Order rejected'), ('IDEMPOTENCY_CONFLICT', 'Idempotency conflict'), ('DEPOSIT', 'Simulated deposit')], max_length=24)),
                ('target', models.CharField(blank=True, default='', max_length=128)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'indexes': [models.Index(fields=['action', '-created_at'], name='ix_audit_action'), models.Index(fields=['actor', '-created_at'], name='ix_audit_actor')],
            },
        ),
    ]
