"""initial schema

Revision ID: c9ee08669481
Revises: 
Create Date: 2026-09-19 23:59:45.763303
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'c9ee08669481'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('admin_key_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('access_points',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('capacity', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('capacity >= 0', name='ck_ap_capacity_nonneg'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_ap_tenant_name')
    )
    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('active', 'revoked', name='device_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_device_tenant_name')
    )
    op.create_table('address_pools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('access_point_id', sa.UUID(), nullable=False),
    sa.Column('cidr', sa.String(length=64), nullable=False),
    sa.Column('reserved_first', sa.BigInteger(), nullable=False),
    sa.Column('reserved_last', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('reserved_first >= 0 AND reserved_last >= 0', name='ck_pool_reserved_nonneg'),
    sa.ForeignKeyConstraint(['access_point_id'], ['access_points.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_point_id', 'cidr', name='uq_pool_ap_cidr')
    )
    op.create_table('leases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('access_point_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('pool_id', sa.UUID(), nullable=False),
    sa.Column('generation', sa.BigInteger(), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=False),
    sa.Column('status', sa.Enum('active', 'closed', 'expired', 'revoked', 'superseded', name='lease_status'), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('termination_reason', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['access_point_id'], ['access_points.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pool_id'], ['address_pools.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lease_ap_status', 'leases', ['access_point_id', 'status'], unique=False)
    op.create_index('ix_lease_last_seen', 'leases', ['last_seen_at'], unique=False)
    op.create_index('uq_lease_active_ap_ip', 'leases', ['access_point_id', 'ip_address'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_index('uq_lease_active_device', 'leases', ['device_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('lease_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('lease_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=128), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lease_id'], ['leases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lease_event_lease', 'lease_events', ['lease_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lease_event_lease', table_name='lease_events')
    op.drop_table('lease_events')
    op.drop_index('uq_lease_active_device', table_name='leases', postgresql_where=sa.text("status = 'active'"))
    op.drop_index('uq_lease_active_ap_ip', table_name='leases', postgresql_where=sa.text("status = 'active'"))
    op.drop_index('ix_lease_last_seen', table_name='leases')
    op.drop_index('ix_lease_ap_status', table_name='leases')
    op.drop_table('leases')
    op.drop_table('address_pools')
    op.drop_table('devices')
    op.drop_table('access_points')
    op.drop_table('tenants')
    # ### end Alembic commands ###
