// Package register implements a multi-version register whose conflicting
// (concurrent) writes are all retained. Each stored version carries the value
// and the vector clock at which it was produced.
//
// For a given key, the set of live versions always forms an antichain under
// the vector-clock happens-before order: no live version is dominated by
// another. Merging in a remote version is therefore deterministic:
//
//   - if it is before some live version, it is stale and discarded;
//   - if it dominates some live versions, those are causally overwritten;
//   - if it is concurrent, it is kept as an additional sibling.
//
// The merge is idempotent, commutative and associative, so re-delivering a
// message (at-least-once transport) or reordering messages cannot change the
// outcome: this is what convergence means here.
package register

import (
	"errors"
	"sort"
	"sync"

	"vcreg/internal/vclock"
)

// Version is one sibling value of a key.
type Version struct {
	Value string       `json:"value"`
	Clock vclock.Clock `json:"clock"`
	// Origin is the replica that produced this version (diagnostic only).
	Origin string `json:"origin"`
}

// Register holds the live sibling versions of one key.
type Register struct {
	mu       sync.Mutex
	versions []Version
}

// Versions returns a snapshot copy of the live versions, ordered by clock
// canonical form for stable output.
func (r *Register) Versions() []Version {
	r.mu.Lock()
	defer r.mu.Unlock()
	return cloneSorted(r.versions)
}

// receive admits one version under the register lock and reports whether it
// was new (true) or dropped as stale/duplicate (false).
func (r *Register) receive(v Version) bool {
	r.mu.Lock()
	defer r.mu.Unlock()
	already := containsVersion(r.versions, v)
	r.versions = mergeOne(r.versions, v)
	return !already && containsVersion(r.versions, v)
}

func containsVersion(set []Version, v Version) bool {
	for _, x := range set {
		if x.Clock.Canonical() == v.Clock.Canonical() {
			return true
		}
	}
	return false
}

// localWrite appends a new version produced on this replica and prunes
// anything it causally overwrites. Caller must not hold r.mu.
func (r *Register) localWrite(v Version) {
	r.mu.Lock()
	defer r.mu.Unlock()
	r.versions = mergeOne(r.versions, v)
}

// mergeOne returns versions after admitting candidate into cur.
//
// Equal clocks are treated as the same event: the candidate is a duplicate
// and is dropped (first write wins; in a correct deployment equal clocks are
// generated by the same logical event anyway).
func mergeOne(cur []Version, candidate Version) []Version {
	out := make([]Version, 0, len(cur)+1)
	for _, v := range cur {
		switch vclock.Compare(candidate.Clock, v.Clock) {
		case vclock.Before, vclock.Equal:
			// Stale or duplicate: candidate cannot overwrite v; keep v.
			out = append(out, v)
		case vclock.After:
			// Candidate causally overwrites v: drop v.
		case vclock.Concurrent:
			// Sibling conflict: keep both.
			out = append(out, v)
		}
	}
	admit := true
	for _, v := range cur {
		rel := vclock.Compare(candidate.Clock, v.Clock)
		if rel == vclock.Before || rel == vclock.Equal {
			admit = false
			break
		}
	}
	if admit {
		out = append(out, candidate)
	}
	return out
}

func cloneSorted(vs []Version) []Version {
	out := make([]Version, len(vs))
	copy(out, vs)
	sort.Slice(out, func(i, j int) bool {
		return out[i].Clock.Canonical() < out[j].Clock.Canonical()
	})
	return out
}

// Store holds all keys of one replica. The zero value is not usable; create
// one with NewStore.
type Store struct {
	mu      sync.Mutex
	keys    map[string]*Register
	replica string
}

// NewStore creates an empty store owned by replica id.
func NewStore(replica string) *Store {
	return &Store{keys: make(map[string]*Register), replica: replica}
}

// Replica returns the owning replica id.
func (s *Store) Replica() string { return s.replica }

// reg returns the register for key, creating it under lock.
func (s *Store) reg(key string) *Register {
	s.mu.Lock()
	r, ok := s.keys[key]
	if !ok {
		r = &Register{}
		s.keys[key] = r
	}
	s.mu.Unlock()
	return r
}

// Keys returns the sorted set of keys known to this store.
func (s *Store) Keys() []string {
	s.mu.Lock()
	defer s.mu.Unlock()
	out := make([]string, 0, len(s.keys))
	for k, r := range s.keys {
		if len(r.Versions()) > 0 {
			out = append(out, k)
		}
	}
	sort.Strings(out)
	return out
}

// Read returns the live versions of key (empty if unknown).
func (s *Store) Read(key string) []Version {
	return s.reg(key).Versions()
}

// Write applies a local event. A nil parent means "based on everything this
// replica currently knows for the key": the parent is the join of all live
// sibling clocks, so ordinary sequential writes on one replica form a causal
// chain. Pass an explicit (possibly empty) clock to write against a chosen
// context instead.
func (s *Store) Write(key, value string, parent vclock.Clock) Version {
	if parent == nil {
		parent = vclock.Clock{}
		for _, v := range s.reg(key).Versions() {
			parent = vclock.Join(parent, v.Clock)
		}
	}
	v := Version{
		Value:  value,
		Clock:  vclock.Increment(parent, s.replica),
		Origin: s.replica,
	}
	s.reg(key).localWrite(v)
	return v
}

// Receive merges one incoming version, as delivered by a peer's sync. It
// returns true if the version was admitted and false if it was stale or a
// duplicate. Concurrent versions are always admitted.
func (s *Store) Receive(key string, v Version) bool {
	return s.reg(key).receive(Version{
		Value:  v.Value,
		Clock:  vclock.Clock.Copy(v.Clock),
		Origin: v.Origin,
	})
}

// ErrUnknownContext is returned when an explicit merge cites a clock that is
// not among the current siblings of the key.
var ErrUnknownContext = errors.New("context clock is not a current sibling of the key")

// Resolve performs an explicit, context-bearing merge. It verifies that every
// clock in context identifies a live sibling (so the caller is merging values
// it has actually observed), produces a successor event on this replica with
// the merged value, and prunes the cited siblings. Siblings not listed in the
// context are preserved untouched; if the new version is concurrent with
// them, they remain as concurrent versions rather than being silently
// overwritten — but note the new clock dominates every cited clock.
func (s *Store) Resolve(key, value string, context []vclock.Clock) (Version, error) {
	r := s.reg(key)
	r.mu.Lock()
	defer r.mu.Unlock()

	if len(context) == 0 {
		// Default context: resolve against everything currently visible.
		for _, v := range r.versions {
			context = append(context, v.Clock)
		}
	} else {
		for _, want := range context {
			found := false
			for _, v := range r.versions {
				if vclock.Compare(want, v.Clock) == vclock.Equal {
					found = true
					break
				}
			}
			if !found {
				return Version{}, ErrUnknownContext
			}
		}
	}

	parent := vclock.Clock{}
	for _, c := range context {
		parent = vclock.Join(parent, c)
	}
	resolved := Version{
		Value:  value,
		Clock:  vclock.Increment(parent, s.replica),
		Origin: s.replica,
	}
	r.versions = mergeOne(r.versions, resolved)
	return resolved, nil
}

// Snapshot is an immutable-ish dump of a store, used for sync.
type Snapshot struct {
	Replica string               `json:"replica"`
	Data    map[string][]Version `json:"data"`
}

// Snapshot returns a point-in-time dump of every key and its versions.
func (s *Store) Snapshot() Snapshot {
	s.mu.Lock()
	keys := make([]string, 0, len(s.keys))
	for k := range s.keys {
		keys = append(keys, k)
	}
	s.mu.Unlock()

	snap := Snapshot{Replica: s.replica, Data: make(map[string][]Version)}
	for _, k := range keys {
		if vs := s.Read(k); len(vs) > 0 {
			snap.Data[k] = vs
		}
	}
	return snap
}

// MergeSnapshot joins a peer snapshot into this store and returns the number
// of versions admitted.
func (s *Store) MergeSnapshot(in Snapshot) int {
	admitted := 0
	keys := make([]string, 0, len(in.Data))
	for k := range in.Data {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		for _, v := range in.Data[k] {
			if s.Receive(k, v) {
				admitted++
			}
		}
	}
	return admitted
}
