# Generated by Django 5.0.14 on 2026-09-21 18:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('display_name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.SlugField(max_length=64)),
                ('sdk_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('app.create', 'App created'), ('placement.create', 'Placement created'), ('placement.update', 'Placement updated'), ('network.add', 'Network line added'), ('network.update', 'Network line updated'), ('network.remove', 'Network line removed'), ('config.publish', 'Configuration published'), ('experiment.create', 'Experiment created'), ('experiment.stop', 'Experiment stopped')], max_length=32)),
                ('target_type', models.CharField(max_length=64)),
                ('target_id', models.CharField(blank=True, default='', max_length=64)),
                ('target_repr', models.CharField(blank=True, default='', max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='catalog.app')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ConfigVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('published', 'Published'), ('active', 'Active')], default='published', max_length=16)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('published_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['placement_id', '-version'],
            },
        ),
        migrations.CreateModel(
            name='ConfigVersionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_code', models.SlugField(max_length=64)),
                ('network_name', models.CharField(max_length=120)),
                ('priority', models.PositiveSmallIntegerField()),
                ('cpm_floor', models.DecimalField(decimal_places=6, max_digits=20)),
                ('fallback_order', models.PositiveSmallIntegerField()),
                ('enabled', models.BooleanField(default=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='version_entries', to='catalog.adnetwork')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='catalog.configversion')),
            ],
            options={
                'ordering': ['priority', 'network_code'],
            },
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.SlugField(max_length=64)),
                ('format', models.CharField(choices=[('banner', 'Banner'), ('interstitial', 'Interstitial'), ('rewarded', 'Rewarded'), ('native', 'Native')], default='interstitial', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.configversion')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='catalog.app')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='configversion',
            name='placement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='catalog.placement'),
        ),
        migrations.CreateModel(
            name='PlacementNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField()),
                ('cpm_floor', models.DecimalField(decimal_places=6, max_digits=20)),
                ('fallback_order', models.PositiveSmallIntegerField()),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placement_lines', to='catalog.adnetwork')),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_lines', to='catalog.placement')),
            ],
            options={
                'ordering': ['placement_id', 'priority'],
            },
        ),
        migrations.AddConstraint(
            model_name='app',
            constraint=models.UniqueConstraint(fields=('owner', 'code'), name='uniq_app_code_per_owner'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['app', 'action'], name='catalog_aud_app_id_f556ba_idx'),
        ),
        migrations.AddConstraint(
            model_name='configversionentry',
            constraint=models.UniqueConstraint(fields=('version', 'network'), name='uniq_network_per_version'),
        ),
        migrations.AddConstraint(
            model_name='placement',
            constraint=models.UniqueConstraint(fields=('app', 'code'), name='uniq_placement_code_per_app'),
        ),
        migrations.AddConstraint(
            model_name='configversion',
            constraint=models.UniqueConstraint(fields=('placement', 'version'), name='uniq_version_per_placement'),
        ),
        migrations.AddConstraint(
            model_name='placementnetwork',
            constraint=models.UniqueConstraint(fields=('placement', 'network'), name='uniq_network_per_placement'),
        ),
        migrations.AddConstraint(
            model_name='placementnetwork',
            constraint=models.UniqueConstraint(condition=models.Q(('enabled', True)), fields=('placement', 'priority'), name='uniq_priority_per_placement'),
        ),
    ]
