// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: proto/syncpb/sync.proto

package syncpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BlockSync_ChainTip_FullMethodName      = "/syncpb.BlockSync/ChainTip"
	BlockSync_FetchSegments_FullMethodName = "/syncpb.BlockSync/FetchSegments"
)

// BlockSyncClient is the client API for BlockSync service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlockSyncClient interface {
	// 节点"宣称"的链尖高度与对应区块哈希。
	// 注意：该高度只是 Advertised（广告）信息，不代表同步器已验证的进度。
	ChainTip(ctx context.Context, in *GetTipRequest, opts ...grpc.CallOption) (*TipInfo, error)
	// 拉取半开区间 [start, start+limit) 内的区块。
	FetchSegments(ctx context.Context, in *GetSegmentsRequest, opts ...grpc.CallOption) (*Segment, error)
}

type blockSyncClient struct {
	cc grpc.ClientConnInterface
}

func NewBlockSyncClient(cc grpc.ClientConnInterface) BlockSyncClient {
	return &blockSyncClient{cc}
}

func (c *blockSyncClient) ChainTip(ctx context.Context, in *GetTipRequest, opts ...grpc.CallOption) (*TipInfo, error) {
	out := new(TipInfo)
	err := c.cc.Invoke(ctx, BlockSync_ChainTip_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockSyncClient) FetchSegments(ctx context.Context, in *GetSegmentsRequest, opts ...grpc.CallOption) (*Segment, error) {
	out := new(Segment)
	err := c.cc.Invoke(ctx, BlockSync_FetchSegments_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlockSyncServer is the server API for BlockSync service.
// All implementations must embed UnimplementedBlockSyncServer
// for forward compatibility
type BlockSyncServer interface {
	// 节点"宣称"的链尖高度与对应区块哈希。
	// 注意：该高度只是 Advertised（广告）信息，不代表同步器已验证的进度。
	ChainTip(context.Context, *GetTipRequest) (*TipInfo, error)
	// 拉取半开区间 [start, start+limit) 内的区块。
	FetchSegments(context.Context, *GetSegmentsRequest) (*Segment, error)
	mustEmbedUnimplementedBlockSyncServer()
}

// UnimplementedBlockSyncServer must be embedded to have forward compatible implementations.
type UnimplementedBlockSyncServer struct {
}

func (UnimplementedBlockSyncServer) ChainTip(context.Context, *GetTipRequest) (*TipInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChainTip not implemented")
}
func (UnimplementedBlockSyncServer) FetchSegments(context.Context, *GetSegmentsRequest) (*Segment, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchSegments not implemented")
}
func (UnimplementedBlockSyncServer) mustEmbedUnimplementedBlockSyncServer() {}

// UnsafeBlockSyncServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlockSyncServer will
// result in compilation errors.
type UnsafeBlockSyncServer interface {
	mustEmbedUnimplementedBlockSyncServer()
}

func RegisterBlockSyncServer(s grpc.ServiceRegistrar, srv BlockSyncServer) {
	s.RegisterService(&BlockSync_ServiceDesc, srv)
}

func _BlockSync_ChainTip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockSyncServer).ChainTip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlockSync_ChainTip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockSyncServer).ChainTip(ctx, req.(*GetTipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockSync_FetchSegments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSegmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockSyncServer).FetchSegments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlockSync_FetchSegments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockSyncServer).FetchSegments(ctx, req.(*GetSegmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BlockSync_ServiceDesc is the grpc.ServiceDesc for BlockSync service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlockSync_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "syncpb.BlockSync",
	HandlerType: (*BlockSyncServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ChainTip",
			Handler:    _BlockSync_ChainTip_Handler,
		},
		{
			MethodName: "FetchSegments",
			Handler:    _BlockSync_FetchSegments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/syncpb/sync.proto",
}
