// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: audit.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const insertAuditEvent = `-- name: InsertAuditEvent :one
INSERT INTO audit_events (incident_id, actor, action, from_status, to_status, detail, request_id)
VALUES ($1, $2, $3,
        $4::incident_status, $5::incident_status,
        $6, $7)
RETURNING id, incident_id, actor, action, from_status, to_status, detail, request_id, created_at
`

type InsertAuditEventParams struct {
	IncidentID uuid.UUID          `json:"incident_id"`
	Actor      string             `json:"actor"`
	Action     string             `json:"action"`
	FromStatus NullIncidentStatus `json:"from_status"`
	ToStatus   NullIncidentStatus `json:"to_status"`
	Detail     json.RawMessage    `json:"detail"`
	RequestID  *string            `json:"request_id"`
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (AuditEvent, error) {
	row := q.db.QueryRow(ctx, insertAuditEvent,
		arg.IncidentID,
		arg.Actor,
		arg.Action,
		arg.FromStatus,
		arg.ToStatus,
		arg.Detail,
		arg.RequestID,
	)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.Actor,
		&i.Action,
		&i.FromStatus,
		&i.ToStatus,
		&i.Detail,
		&i.RequestID,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT id, incident_id, actor, action, from_status, to_status, detail, request_id, created_at FROM audit_events WHERE incident_id = $1 ORDER BY id
`

func (q *Queries) ListAuditEvents(ctx context.Context, incidentID uuid.UUID) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEvents, incidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.IncidentID,
			&i.Actor,
			&i.Action,
			&i.FromStatus,
			&i.ToStatus,
			&i.Detail,
			&i.RequestID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
