// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: billing.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countBillingRecords = `-- name: CountBillingRecords :one
SELECT count(*) FROM billing_records r
WHERE (cardinality(COALESCE($3, ARRAY[]::bigint[])) = 0 OR r.account_id = ANY($3))
  AND ($4::boolean = FALSE OR r.currency = $5)
  AND r.usage_date BETWEEN $1 AND $2
`

type CountBillingRecordsParams struct {
	UsageDate      pgtype.Date `json:"usage_date"`
	UsageDate_2    pgtype.Date `json:"usage_date_2"`
	AccountIds     interface{} `json:"account_ids"`
	CurrencyFilter bool        `json:"currency_filter"`
	Currency       string      `json:"currency"`
}

func (q *Queries) CountBillingRecords(ctx context.Context, arg CountBillingRecordsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBillingRecords,
		arg.UsageDate,
		arg.UsageDate_2,
		arg.AccountIds,
		arg.CurrencyFilter,
		arg.Currency,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBatch = `-- name: CreateBatch :one
INSERT INTO import_batches
    (account_id, filename, total_rows, inserted_rows, duplicate_rows, status, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, account_id, filename, total_rows, inserted_rows, duplicate_rows,
          status, created_by, created_at
`

type CreateBatchParams struct {
	AccountID     int64       `json:"account_id"`
	Filename      string      `json:"filename"`
	TotalRows     int32       `json:"total_rows"`
	InsertedRows  int32       `json:"inserted_rows"`
	DuplicateRows int32       `json:"duplicate_rows"`
	Status        string      `json:"status"`
	CreatedBy     pgtype.Int8 `json:"created_by"`
}

func (q *Queries) CreateBatch(ctx context.Context, arg CreateBatchParams) (ImportBatch, error) {
	row := q.db.QueryRow(ctx, createBatch,
		arg.AccountID,
		arg.Filename,
		arg.TotalRows,
		arg.InsertedRows,
		arg.DuplicateRows,
		arg.Status,
		arg.CreatedBy,
	)
	var i ImportBatch
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Filename,
		&i.TotalRows,
		&i.InsertedRows,
		&i.DuplicateRows,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listBatches = `-- name: ListBatches :many
SELECT b.id, b.account_id, b.filename, b.total_rows, b.inserted_rows,
       b.duplicate_rows, b.status, b.created_by, b.created_at
FROM import_batches b
JOIN accounts a ON a.id = b.account_id
WHERE (cardinality(COALESCE($3, ARRAY[]::bigint[])) = 0 OR a.org_id = ANY($3))
ORDER BY b.id DESC
LIMIT $1 OFFSET $2
`

type ListBatchesParams struct {
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
	OrgIds interface{} `json:"org_ids"`
}

func (q *Queries) ListBatches(ctx context.Context, arg ListBatchesParams) ([]ImportBatch, error) {
	rows, err := q.db.Query(ctx, listBatches, arg.Limit, arg.Offset, arg.OrgIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImportBatch{}
	for rows.Next() {
		var i ImportBatch
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Filename,
			&i.TotalRows,
			&i.InsertedRows,
			&i.DuplicateRows,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBillingRecords = `-- name: ListBillingRecords :many
SELECT r.id, r.account_id, r.resource_id, r.service, r.usage_date,
       r.currency, r.amount, r.content_hash, r.batch_id, r.created_at
FROM billing_records r
WHERE (cardinality(COALESCE($5, ARRAY[]::bigint[])) = 0 OR r.account_id = ANY($5))
  AND ($6::boolean = FALSE OR r.currency = $7)
  AND r.usage_date BETWEEN $1 AND $2
ORDER BY r.usage_date, r.resource_id
LIMIT $3 OFFSET $4
`

type ListBillingRecordsParams struct {
	UsageDate      pgtype.Date `json:"usage_date"`
	UsageDate_2    pgtype.Date `json:"usage_date_2"`
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
	AccountIds     interface{} `json:"account_ids"`
	CurrencyFilter bool        `json:"currency_filter"`
	Currency       string      `json:"currency"`
}

func (q *Queries) ListBillingRecords(ctx context.Context, arg ListBillingRecordsParams) ([]BillingRecord, error) {
	rows, err := q.db.Query(ctx, listBillingRecords,
		arg.UsageDate,
		arg.UsageDate_2,
		arg.Limit,
		arg.Offset,
		arg.AccountIds,
		arg.CurrencyFilter,
		arg.Currency,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillingRecord{}
	for rows.Next() {
		var i BillingRecord
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.ResourceID,
			&i.Service,
			&i.UsageDate,
			&i.Currency,
			&i.Amount,
			&i.ContentHash,
			&i.BatchID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDailySummaries = `-- name: ListDailySummaries :many
SELECT id, scope, account_id, cost_center_id, usage_date, currency,
       total_amount, record_count, updated_at
FROM daily_summaries
WHERE scope = $1
  AND (CASE WHEN $1 = 'account'
            THEN (cardinality(COALESCE($4, ARRAY[]::bigint[])) = 0 OR account_id = ANY($4))
            ELSE (cardinality(COALESCE($5, ARRAY[]::bigint[])) = 0 OR cost_center_id = ANY($5))
       END)
  AND usage_date BETWEEN $2 AND $3
ORDER BY usage_date, currency
`

type ListDailySummariesParams struct {
	Scope       string      `json:"scope"`
	UsageDate   pgtype.Date `json:"usage_date"`
	UsageDate_2 pgtype.Date `json:"usage_date_2"`
	AccountIds  interface{} `json:"account_ids"`
	CcIds       interface{} `json:"cc_ids"`
}

func (q *Queries) ListDailySummaries(ctx context.Context, arg ListDailySummariesParams) ([]DailySummary, error) {
	rows, err := q.db.Query(ctx, listDailySummaries,
		arg.Scope,
		arg.UsageDate,
		arg.UsageDate_2,
		arg.AccountIds,
		arg.CcIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailySummary{}
	for rows.Next() {
		var i DailySummary
		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.AccountID,
			&i.CostCenterID,
			&i.UsageDate,
			&i.Currency,
			&i.TotalAmount,
			&i.RecordCount,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonthlySummaries = `-- name: ListMonthlySummaries :many
SELECT id, scope, account_id, cost_center_id, month, currency,
       total_amount, record_count, updated_at
FROM monthly_summaries
WHERE scope = $1
  AND (CASE WHEN $1 = 'account'
            THEN (cardinality(COALESCE($4, ARRAY[]::bigint[])) = 0 OR account_id = ANY($4))
            ELSE (cardinality(COALESCE($5, ARRAY[]::bigint[])) = 0 OR cost_center_id = ANY($5))
       END)
  AND month BETWEEN $2 AND $3
ORDER BY month, currency
`

type ListMonthlySummariesParams struct {
	Scope      string      `json:"scope"`
	Month      pgtype.Date `json:"month"`
	Month_2    pgtype.Date `json:"month_2"`
	AccountIds interface{} `json:"account_ids"`
	CcIds      interface{} `json:"cc_ids"`
}

func (q *Queries) ListMonthlySummaries(ctx context.Context, arg ListMonthlySummariesParams) ([]MonthlySummary, error) {
	rows, err := q.db.Query(ctx, listMonthlySummaries,
		arg.Scope,
		arg.Month,
		arg.Month_2,
		arg.AccountIds,
		arg.CcIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MonthlySummary{}
	for rows.Next() {
		var i MonthlySummary
		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.AccountID,
			&i.CostCenterID,
			&i.Month,
			&i.Currency,
			&i.TotalAmount,
			&i.RecordCount,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBatch = `-- name: MarkBatch :exec
UPDATE import_batches SET status = $2 WHERE id = $1
`

type MarkBatchParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) MarkBatch(ctx context.Context, arg MarkBatchParams) error {
	_, err := q.db.Exec(ctx, markBatch, arg.ID, arg.Status)
	return err
}
