// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: budgets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBudgetVersion = `-- name: CreateBudgetVersion :one
INSERT INTO budgets (cost_center_id, currency, month, version, monthly_limit, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, cost_center_id, currency, month, version, monthly_limit,
          active, created_by, created_at
`

type CreateBudgetVersionParams struct {
	CostCenterID int64          `json:"cost_center_id"`
	Currency     string         `json:"currency"`
	Month        pgtype.Date    `json:"month"`
	Version      int32          `json:"version"`
	MonthlyLimit pgtype.Numeric `json:"monthly_limit"`
	CreatedBy    pgtype.Int8    `json:"created_by"`
}

func (q *Queries) CreateBudgetVersion(ctx context.Context, arg CreateBudgetVersionParams) (Budget, error) {
	row := q.db.QueryRow(ctx, createBudgetVersion,
		arg.CostCenterID,
		arg.Currency,
		arg.Month,
		arg.Version,
		arg.MonthlyLimit,
		arg.CreatedBy,
	)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.CostCenterID,
		&i.Currency,
		&i.Month,
		&i.Version,
		&i.MonthlyLimit,
		&i.Active,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateBudget = `-- name: DeactivateBudget :exec
UPDATE budgets SET active = FALSE WHERE id = $1
`

func (q *Queries) DeactivateBudget(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deactivateBudget, id)
	return err
}

const getActiveBudget = `-- name: GetActiveBudget :one
SELECT id, cost_center_id, currency, month, version, monthly_limit,
       active, created_by, created_at
FROM budgets
WHERE cost_center_id = $1 AND currency = $2 AND month = $3 AND active
`

type GetActiveBudgetParams struct {
	CostCenterID int64       `json:"cost_center_id"`
	Currency     string      `json:"currency"`
	Month        pgtype.Date `json:"month"`
}

func (q *Queries) GetActiveBudget(ctx context.Context, arg GetActiveBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, getActiveBudget, arg.CostCenterID, arg.Currency, arg.Month)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.CostCenterID,
		&i.Currency,
		&i.Month,
		&i.Version,
		&i.MonthlyLimit,
		&i.Active,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertBudgetAlert = `-- name: InsertBudgetAlert :execrows
INSERT INTO budget_alerts
    (budget_id, threshold_pct, spent_amount, month, currency,
     triggered_by_batch)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (budget_id, threshold_pct) DO NOTHING
`

type InsertBudgetAlertParams struct {
	BudgetID         int64          `json:"budget_id"`
	ThresholdPct     int32          `json:"threshold_pct"`
	SpentAmount      pgtype.Numeric `json:"spent_amount"`
	Month            pgtype.Date    `json:"month"`
	Currency         string         `json:"currency"`
	TriggeredByBatch pgtype.Int8    `json:"triggered_by_batch"`
}

func (q *Queries) InsertBudgetAlert(ctx context.Context, arg InsertBudgetAlertParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertBudgetAlert,
		arg.BudgetID,
		arg.ThresholdPct,
		arg.SpentAmount,
		arg.Month,
		arg.Currency,
		arg.TriggeredByBatch,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listBudgetAlerts = `-- name: ListBudgetAlerts :many
SELECT a.id, a.budget_id, a.threshold_pct, a.spent_amount, a.month,
       a.currency, a.triggered_by_batch, a.triggered_at,
       b.cost_center_id, b.version AS budget_version
FROM budget_alerts a
JOIN budgets b ON b.id = a.budget_id
WHERE (cardinality(COALESCE($1, ARRAY[]::bigint[])) = 0 OR b.cost_center_id = ANY($1))
ORDER BY a.triggered_at DESC
`

type ListBudgetAlertsRow struct {
	ID               int64              `json:"id"`
	BudgetID         int64              `json:"budget_id"`
	ThresholdPct     int32              `json:"threshold_pct"`
	SpentAmount      pgtype.Numeric     `json:"spent_amount"`
	Month            pgtype.Date        `json:"month"`
	Currency         string             `json:"currency"`
	TriggeredByBatch pgtype.Int8        `json:"triggered_by_batch"`
	TriggeredAt      pgtype.Timestamptz `json:"triggered_at"`
	CostCenterID     int64              `json:"cost_center_id"`
	BudgetVersion    int32              `json:"budget_version"`
}

func (q *Queries) ListBudgetAlerts(ctx context.Context, ccIds interface{}) ([]ListBudgetAlertsRow, error) {
	rows, err := q.db.Query(ctx, listBudgetAlerts, ccIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBudgetAlertsRow{}
	for rows.Next() {
		var i ListBudgetAlertsRow
		if err := rows.Scan(
			&i.ID,
			&i.BudgetID,
			&i.ThresholdPct,
			&i.SpentAmount,
			&i.Month,
			&i.Currency,
			&i.TriggeredByBatch,
			&i.TriggeredAt,
			&i.CostCenterID,
			&i.BudgetVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBudgetVersions = `-- name: ListBudgetVersions :many
SELECT id, cost_center_id, currency, month, version, monthly_limit,
       active, created_by, created_at
FROM budgets
WHERE (cardinality(COALESCE($1, ARRAY[]::bigint[])) = 0 OR cost_center_id = ANY($1))
ORDER BY month DESC, cost_center_id, currency, version DESC
`

func (q *Queries) ListBudgetVersions(ctx context.Context, ccIds interface{}) ([]Budget, error) {
	rows, err := q.db.Query(ctx, listBudgetVersions, ccIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Budget{}
	for rows.Next() {
		var i Budget
		if err := rows.Scan(
			&i.ID,
			&i.CostCenterID,
			&i.Currency,
			&i.Month,
			&i.Version,
			&i.MonthlyLimit,
			&i.Active,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextBudgetVersion = `-- name: NextBudgetVersion :one
SELECT COALESCE(max(version), 0) + 1
FROM budgets
WHERE cost_center_id = $1 AND currency = $2 AND month = $3
`

type NextBudgetVersionParams struct {
	CostCenterID int64       `json:"cost_center_id"`
	Currency     string      `json:"currency"`
	Month        pgtype.Date `json:"month"`
}

func (q *Queries) NextBudgetVersion(ctx context.Context, arg NextBudgetVersionParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextBudgetVersion, arg.CostCenterID, arg.Currency, arg.Month)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
