// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: drafts.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDraftTempPrice = `-- name: CreateDraftTempPrice :one
INSERT INTO draft_temp_prices (store_id, item_key, price_cents, starts_at, ends_at)
VALUES ($1, $2, $3, $4, $5) RETURNING id, store_id, item_key, price_cents, starts_at, ends_at
`

type CreateDraftTempPriceParams struct {
	StoreID    pgtype.UUID `json:"store_id"`
	ItemKey    string      `json:"item_key"`
	PriceCents int32       `json:"price_cents"`
	StartsAt   time.Time   `json:"starts_at"`
	EndsAt     time.Time   `json:"ends_at"`
}

func (q *Queries) CreateDraftTempPrice(ctx context.Context, arg CreateDraftTempPriceParams) (DraftTempPrice, error) {
	row := q.db.QueryRow(ctx, createDraftTempPrice,
		arg.StoreID,
		arg.ItemKey,
		arg.PriceCents,
		arg.StartsAt,
		arg.EndsAt,
	)
	var i DraftTempPrice
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.ItemKey,
		&i.PriceCents,
		&i.StartsAt,
		&i.EndsAt,
	)
	return i, err
}

const deleteDraftItem = `-- name: DeleteDraftItem :execrows
DELETE FROM draft_items WHERE store_id = $1 AND item_key = $2
`

type DeleteDraftItemParams struct {
	StoreID pgtype.UUID `json:"store_id"`
	ItemKey string      `json:"item_key"`
}

func (q *Queries) DeleteDraftItem(ctx context.Context, arg DeleteDraftItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDraftItem, arg.StoreID, arg.ItemKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteDraftTempPrice = `-- name: DeleteDraftTempPrice :execrows
DELETE FROM draft_temp_prices WHERE store_id = $1 AND id = $2
`

type DeleteDraftTempPriceParams struct {
	StoreID pgtype.UUID `json:"store_id"`
	ID      pgtype.UUID `json:"id"`
}

func (q *Queries) DeleteDraftTempPrice(ctx context.Context, arg DeleteDraftTempPriceParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDraftTempPrice, arg.StoreID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDraftItem = `-- name: GetDraftItem :one
SELECT store_id, item_key, name, price_cents, sold_out_threshold, position FROM draft_items WHERE store_id = $1 AND item_key = $2
`

type GetDraftItemParams struct {
	StoreID pgtype.UUID `json:"store_id"`
	ItemKey string      `json:"item_key"`
}

func (q *Queries) GetDraftItem(ctx context.Context, arg GetDraftItemParams) (DraftItem, error) {
	row := q.db.QueryRow(ctx, getDraftItem, arg.StoreID, arg.ItemKey)
	var i DraftItem
	err := row.Scan(
		&i.StoreID,
		&i.ItemKey,
		&i.Name,
		&i.PriceCents,
		&i.SoldOutThreshold,
		&i.Position,
	)
	return i, err
}

const listDraftItems = `-- name: ListDraftItems :many
SELECT store_id, item_key, name, price_cents, sold_out_threshold, position FROM draft_items WHERE store_id = $1 ORDER BY position, item_key
`

func (q *Queries) ListDraftItems(ctx context.Context, storeID pgtype.UUID) ([]DraftItem, error) {
	rows, err := q.db.Query(ctx, listDraftItems, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DraftItem{}
	for rows.Next() {
		var i DraftItem
		if err := rows.Scan(
			&i.StoreID,
			&i.ItemKey,
			&i.Name,
			&i.PriceCents,
			&i.SoldOutThreshold,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDraftTempPrices = `-- name: ListDraftTempPrices :many
SELECT id, store_id, item_key, price_cents, starts_at, ends_at FROM draft_temp_prices WHERE store_id = $1 ORDER BY item_key, starts_at
`

func (q *Queries) ListDraftTempPrices(ctx context.Context, storeID pgtype.UUID) ([]DraftTempPrice, error) {
	rows, err := q.db.Query(ctx, listDraftTempPrices, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DraftTempPrice{}
	for rows.Next() {
		var i DraftTempPrice
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.ItemKey,
			&i.PriceCents,
			&i.StartsAt,
			&i.EndsAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDraftItem = `-- name: UpsertDraftItem :one
INSERT INTO draft_items (store_id, item_key, name, price_cents, sold_out_threshold, position)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (store_id, item_key) DO UPDATE SET
    name = EXCLUDED.name,
    price_cents = EXCLUDED.price_cents,
    sold_out_threshold = EXCLUDED.sold_out_threshold,
    position = EXCLUDED.position
RETURNING store_id, item_key, name, price_cents, sold_out_threshold, position
`

type UpsertDraftItemParams struct {
	StoreID          pgtype.UUID `json:"store_id"`
	ItemKey          string      `json:"item_key"`
	Name             string      `json:"name"`
	PriceCents       int32       `json:"price_cents"`
	SoldOutThreshold int32       `json:"sold_out_threshold"`
	Position         int32       `json:"position"`
}

func (q *Queries) UpsertDraftItem(ctx context.Context, arg UpsertDraftItemParams) (DraftItem, error) {
	row := q.db.QueryRow(ctx, upsertDraftItem,
		arg.StoreID,
		arg.ItemKey,
		arg.Name,
		arg.PriceCents,
		arg.SoldOutThreshold,
		arg.Position,
	)
	var i DraftItem
	err := row.Scan(
		&i.StoreID,
		&i.ItemKey,
		&i.Name,
		&i.PriceCents,
		&i.SoldOutThreshold,
		&i.Position,
	)
	return i, err
}
