// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: evidence.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addEvidenceNote = `-- name: AddEvidenceNote :one
INSERT INTO evidence_notes (evidence_id, note, created_by)
VALUES ($1, $2, $3)
RETURNING id, evidence_id, note, created_by, created_at
`

type AddEvidenceNoteParams struct {
	EvidenceID uuid.UUID `json:"evidence_id"`
	Note       string    `json:"note"`
	CreatedBy  string    `json:"created_by"`
}

func (q *Queries) AddEvidenceNote(ctx context.Context, arg AddEvidenceNoteParams) (EvidenceNote, error) {
	row := q.db.QueryRow(ctx, addEvidenceNote, arg.EvidenceID, arg.Note, arg.CreatedBy)
	var i EvidenceNote
	err := row.Scan(
		&i.ID,
		&i.EvidenceID,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getEvidence = `-- name: GetEvidence :one
SELECT id, incident_id, seq, content, submitted_by, submitted_at FROM evidence WHERE id = $1
`

func (q *Queries) GetEvidence(ctx context.Context, id uuid.UUID) (Evidence, error) {
	row := q.db.QueryRow(ctx, getEvidence, id)
	var i Evidence
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.Seq,
		&i.Content,
		&i.SubmittedBy,
		&i.SubmittedAt,
	)
	return i, err
}

const insertEvidence = `-- name: InsertEvidence :one
INSERT INTO evidence (incident_id, seq, content, submitted_by)
VALUES ($1, $2, $3, $4)
RETURNING id, incident_id, seq, content, submitted_by, submitted_at
`

type InsertEvidenceParams struct {
	IncidentID  uuid.UUID `json:"incident_id"`
	Seq         int32     `json:"seq"`
	Content     string    `json:"content"`
	SubmittedBy string    `json:"submitted_by"`
}

func (q *Queries) InsertEvidence(ctx context.Context, arg InsertEvidenceParams) (Evidence, error) {
	row := q.db.QueryRow(ctx, insertEvidence,
		arg.IncidentID,
		arg.Seq,
		arg.Content,
		arg.SubmittedBy,
	)
	var i Evidence
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.Seq,
		&i.Content,
		&i.SubmittedBy,
		&i.SubmittedAt,
	)
	return i, err
}

const listEvidence = `-- name: ListEvidence :many
SELECT id, incident_id, seq, content, submitted_by, submitted_at FROM evidence WHERE incident_id = $1 ORDER BY seq
`

func (q *Queries) ListEvidence(ctx context.Context, incidentID uuid.UUID) ([]Evidence, error) {
	rows, err := q.db.Query(ctx, listEvidence, incidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Evidence
	for rows.Next() {
		var i Evidence
		if err := rows.Scan(
			&i.ID,
			&i.IncidentID,
			&i.Seq,
			&i.Content,
			&i.SubmittedBy,
			&i.SubmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotesForIncident = `-- name: ListNotesForIncident :many
SELECT n.id, n.evidence_id, n.note, n.created_by, n.created_at FROM evidence_notes n
JOIN evidence e ON e.id = n.evidence_id
WHERE e.incident_id = $1
ORDER BY n.id
`

func (q *Queries) ListNotesForIncident(ctx context.Context, incidentID uuid.UUID) ([]EvidenceNote, error) {
	rows, err := q.db.Query(ctx, listNotesForIncident, incidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EvidenceNote
	for rows.Next() {
		var i EvidenceNote
		if err := rows.Scan(
			&i.ID,
			&i.EvidenceID,
			&i.Note,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
