// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: idempotency.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getIdempotency = `-- name: GetIdempotency :one
SELECT id, key, merchant_id, endpoint, request_hash, resource_id, response_status, response_body, created_at FROM idempotency_keys
WHERE key = $1 AND merchant_id = $2 AND endpoint = $3
FOR UPDATE
`

type GetIdempotencyParams struct {
	Key        string    `json:"key"`
	MerchantID uuid.UUID `json:"merchant_id"`
	Endpoint   string    `json:"endpoint"`
}

func (q *Queries) GetIdempotency(ctx context.Context, arg GetIdempotencyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotency, arg.Key, arg.MerchantID, arg.Endpoint)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.MerchantID,
		&i.Endpoint,
		&i.RequestHash,
		&i.ResourceID,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CreatedAt,
	)
	return i, err
}

const getIdempotencyByKeyEndpoint = `-- name: GetIdempotencyByKeyEndpoint :one
SELECT id, key, merchant_id, endpoint, request_hash, resource_id, response_status, response_body, created_at FROM idempotency_keys
WHERE key = $1 AND endpoint = $2
`

type GetIdempotencyByKeyEndpointParams struct {
	Key      string `json:"key"`
	Endpoint string `json:"endpoint"`
}

func (q *Queries) GetIdempotencyByKeyEndpoint(ctx context.Context, arg GetIdempotencyByKeyEndpointParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyByKeyEndpoint, arg.Key, arg.Endpoint)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.MerchantID,
		&i.Endpoint,
		&i.RequestHash,
		&i.ResourceID,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CreatedAt,
	)
	return i, err
}

const insertIdempotency = `-- name: InsertIdempotency :one
INSERT INTO idempotency_keys
    (key, merchant_id, endpoint, request_hash, resource_id, response_status, response_body)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, key, merchant_id, endpoint, request_hash, resource_id, response_status, response_body, created_at
`

type InsertIdempotencyParams struct {
	Key            string     `json:"key"`
	MerchantID     uuid.UUID  `json:"merchant_id"`
	Endpoint       string     `json:"endpoint"`
	RequestHash    string     `json:"request_hash"`
	ResourceID     *uuid.UUID `json:"resource_id"`
	ResponseStatus int32      `json:"response_status"`
	ResponseBody   []byte     `json:"response_body"`
}

func (q *Queries) InsertIdempotency(ctx context.Context, arg InsertIdempotencyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, insertIdempotency,
		arg.Key,
		arg.MerchantID,
		arg.Endpoint,
		arg.RequestHash,
		arg.ResourceID,
		arg.ResponseStatus,
		arg.ResponseBody,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.MerchantID,
		&i.Endpoint,
		&i.RequestHash,
		&i.ResourceID,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CreatedAt,
	)
	return i, err
}
