// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: ledger.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (merchant_id, code, kind, description)
VALUES ($1, $2, $3, $4)
RETURNING id, merchant_id, code, kind, description, created_at
`

type CreateAccountParams struct {
	MerchantID  *uuid.UUID `json:"merchant_id"`
	Code        string     `json:"code"`
	Kind        string     `json:"kind"`
	Description string     `json:"description"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.MerchantID,
		arg.Code,
		arg.Kind,
		arg.Description,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Code,
		&i.Kind,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, merchant_id, code, kind, description, created_at FROM accounts WHERE merchant_id IS NOT DISTINCT FROM $1 AND code = $2
`

type GetAccountParams struct {
	MerchantID *uuid.UUID `json:"merchant_id"`
	Code       string     `json:"code"`
}

func (q *Queries) GetAccount(ctx context.Context, arg GetAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, arg.MerchantID, arg.Code)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Code,
		&i.Kind,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, merchant_id, code, kind, description, created_at FROM accounts WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Code,
		&i.Kind,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const insertLedgerEntry = `-- name: InsertLedgerEntry :exec
INSERT INTO ledger_entries (tx_type, ref_type, ref_id, account_id, amount_cents, created_at)
VALUES ($1, $2, $3, $4, $5, $6::timestamptz)
`

type InsertLedgerEntryParams struct {
	TxType      string             `json:"tx_type"`
	RefType     string             `json:"ref_type"`
	RefID       uuid.UUID          `json:"ref_id"`
	AccountID   uuid.UUID          `json:"account_id"`
	AmountCents int64              `json:"amount_cents"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) error {
	_, err := q.db.Exec(ctx, insertLedgerEntry,
		arg.TxType,
		arg.RefType,
		arg.RefID,
		arg.AccountID,
		arg.AmountCents,
		arg.CreatedAt,
	)
	return err
}

const listAccountsByMerchant = `-- name: ListAccountsByMerchant :many
SELECT id, merchant_id, code, kind, description, created_at FROM accounts WHERE merchant_id = $1 ORDER BY code
`

func (q *Queries) ListAccountsByMerchant(ctx context.Context, merchantID *uuid.UUID) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccountsByMerchant, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Code,
			&i.Kind,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesByMerchant = `-- name: ListEntriesByMerchant :many
SELECT e.id, e.tx_type, e.ref_type, e.ref_id, e.account_id, e.amount_cents, e.created_at FROM ledger_entries e
JOIN accounts a ON a.id = e.account_id
WHERE a.merchant_id = $1
ORDER BY e.id
LIMIT $2 OFFSET $3
`

type ListEntriesByMerchantParams struct {
	MerchantID *uuid.UUID `json:"merchant_id"`
	Limit      int32      `json:"limit"`
	Offset     int32      `json:"offset"`
}

func (q *Queries) ListEntriesByMerchant(ctx context.Context, arg ListEntriesByMerchantParams) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, listEntriesByMerchant, arg.MerchantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerEntry{}
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.TxType,
			&i.RefType,
			&i.RefID,
			&i.AccountID,
			&i.AmountCents,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesByRef = `-- name: ListEntriesByRef :many
SELECT id, tx_type, ref_type, ref_id, account_id, amount_cents, created_at FROM ledger_entries WHERE ref_type = $1 AND ref_id = $2 ORDER BY id
`

type ListEntriesByRefParams struct {
	RefType string    `json:"ref_type"`
	RefID   uuid.UUID `json:"ref_id"`
}

func (q *Queries) ListEntriesByRef(ctx context.Context, arg ListEntriesByRefParams) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, listEntriesByRef, arg.RefType, arg.RefID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerEntry{}
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.TxType,
			&i.RefType,
			&i.RefID,
			&i.AccountID,
			&i.AmountCents,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumAccountEntries = `-- name: SumAccountEntries :one
SELECT COALESCE(SUM(amount_cents), 0)::BIGINT AS balance
FROM ledger_entries
WHERE account_id = $1
`

func (q *Queries) SumAccountEntries(ctx context.Context, accountID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumAccountEntries, accountID)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const sumAccountEntriesBefore = `-- name: SumAccountEntriesBefore :one
SELECT COALESCE(SUM(amount_cents), 0)::BIGINT AS balance
FROM ledger_entries e
WHERE e.account_id = $1 AND e.created_at <= $2
`

type SumAccountEntriesBeforeParams struct {
	AccountID uuid.UUID          `json:"account_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Reconciliation snapshots account balance from entries created on/before a cutoff.
func (q *Queries) SumAccountEntriesBefore(ctx context.Context, arg SumAccountEntriesBeforeParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumAccountEntriesBefore, arg.AccountID, arg.CreatedAt)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}
