// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: menu.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLiveMenu = `-- name: GetLiveMenu :many
SELECT
    mv.version,
    vi.item_key,
    vi.name,
    vi.position,
    vi.price_cents AS base_price_cents,
    COALESCE(tp.price_cents, vi.price_cents) AS effective_price_cents,
    (tp.id IS NOT NULL)::bool AS temp_price_active,
    vi.sold_out_threshold,
    COALESCE(ds.quantity, 0) AS sold_today,
    (vi.sold_out_threshold > 0 AND COALESCE(ds.quantity, 0) >= vi.sold_out_threshold)::bool AS sold_out
FROM stores s
JOIN menu_versions mv ON mv.store_id = s.id AND mv.version = s.current_version
JOIN version_items vi ON vi.version_id = mv.id
LEFT JOIN version_temp_prices tp
       ON tp.version_id = vi.version_id AND tp.item_key = vi.item_key
      AND tp.starts_at <= now() AND now() < tp.ends_at
LEFT JOIN daily_sales ds
       ON ds.store_id = s.id AND ds.item_key = vi.item_key
      AND ds.day = (now() AT TIME ZONE s.timezone)::date
WHERE s.id = $1
ORDER BY vi.position, vi.item_key
`

type GetLiveMenuRow struct {
	Version             int32  `json:"version"`
	ItemKey             string `json:"item_key"`
	Name                string `json:"name"`
	Position            int32  `json:"position"`
	BasePriceCents      int32  `json:"base_price_cents"`
	EffectivePriceCents int32  `json:"effective_price_cents"`
	TempPriceActive     bool   `json:"temp_price_active"`
	SoldOutThreshold    int32  `json:"sold_out_threshold"`
	SoldToday           int32  `json:"sold_today"`
	SoldOut             bool   `json:"sold_out"`
}

// One consistent snapshot of the live menu: effective price (active temp
// price band wins, half-open [starts_at, ends_at)) and derived sold-out flag
// from today's sales in the store timezone. A single query = a single
// database snapshot, so a response can never mix old and new state.
func (q *Queries) GetLiveMenu(ctx context.Context, id pgtype.UUID) ([]GetLiveMenuRow, error) {
	rows, err := q.db.Query(ctx, getLiveMenu, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLiveMenuRow{}
	for rows.Next() {
		var i GetLiveMenuRow
		if err := rows.Scan(
			&i.Version,
			&i.ItemKey,
			&i.Name,
			&i.Position,
			&i.BasePriceCents,
			&i.EffectivePriceCents,
			&i.TempPriceActive,
			&i.SoldOutThreshold,
			&i.SoldToday,
			&i.SoldOut,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVersionTempPrices = `-- name: ListVersionTempPrices :many
SELECT id, version_id, item_key, price_cents, starts_at, ends_at FROM version_temp_prices WHERE version_id = $1 ORDER BY item_key, starts_at
`

func (q *Queries) ListVersionTempPrices(ctx context.Context, versionID pgtype.UUID) ([]VersionTempPrice, error) {
	rows, err := q.db.Query(ctx, listVersionTempPrices, versionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VersionTempPrice{}
	for rows.Next() {
		var i VersionTempPrice
		if err := rows.Scan(
			&i.ID,
			&i.VersionID,
			&i.ItemKey,
			&i.PriceCents,
			&i.StartsAt,
			&i.EndsAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
