// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID           int64              `json:"id"`
	OrgID        int64              `json:"org_id"`
	CostCenterID int64              `json:"cost_center_id"`
	ExternalID   string             `json:"external_id"`
	Name         string             `json:"name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type AnomalyEvaluation struct {
	ID              int64              `json:"id"`
	AccountID       int64              `json:"account_id"`
	UsageDate       pgtype.Date        `json:"usage_date"`
	Currency        string             `json:"currency"`
	Version         int32              `json:"version"`
	Status          string             `json:"status"`
	ActualAmount    pgtype.Numeric     `json:"actual_amount"`
	BaselineMean    pgtype.Numeric     `json:"baseline_mean"`
	BaselineStd     pgtype.Numeric     `json:"baseline_std"`
	ThresholdAmount pgtype.Numeric     `json:"threshold_amount"`
	BaselineStart   pgtype.Date        `json:"baseline_start"`
	BaselineEnd     pgtype.Date        `json:"baseline_end"`
	BaselineDays    int32              `json:"baseline_days"`
	CreatedByBatch  pgtype.Int8        `json:"created_by_batch"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type BillingRecord struct {
	ID          int64              `json:"id"`
	AccountID   int64              `json:"account_id"`
	ResourceID  string             `json:"resource_id"`
	Service     string             `json:"service"`
	UsageDate   pgtype.Date        `json:"usage_date"`
	Currency    string             `json:"currency"`
	Amount      pgtype.Numeric     `json:"amount"`
	ContentHash string             `json:"content_hash"`
	BatchID     int64              `json:"batch_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Budget struct {
	ID           int64              `json:"id"`
	CostCenterID int64              `json:"cost_center_id"`
	Currency     string             `json:"currency"`
	Month        pgtype.Date        `json:"month"`
	Version      int32              `json:"version"`
	MonthlyLimit pgtype.Numeric     `json:"monthly_limit"`
	Active       bool               `json:"active"`
	CreatedBy    pgtype.Int8        `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type BudgetAlert struct {
	ID               int64              `json:"id"`
	BudgetID         int64              `json:"budget_id"`
	ThresholdPct     int32              `json:"threshold_pct"`
	SpentAmount      pgtype.Numeric     `json:"spent_amount"`
	Month            pgtype.Date        `json:"month"`
	Currency         string             `json:"currency"`
	TriggeredByBatch pgtype.Int8        `json:"triggered_by_batch"`
	TriggeredAt      pgtype.Timestamptz `json:"triggered_at"`
}

type CostCenter struct {
	ID        int64              `json:"id"`
	OrgID     int64              `json:"org_id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type DailySummary struct {
	ID           int64              `json:"id"`
	Scope        string             `json:"scope"`
	AccountID    int64              `json:"account_id"`
	CostCenterID int64              `json:"cost_center_id"`
	UsageDate    pgtype.Date        `json:"usage_date"`
	Currency     string             `json:"currency"`
	TotalAmount  pgtype.Numeric     `json:"total_amount"`
	RecordCount  int32              `json:"record_count"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type ImportBatch struct {
	ID            int64              `json:"id"`
	AccountID     int64              `json:"account_id"`
	Filename      string             `json:"filename"`
	TotalRows     int32              `json:"total_rows"`
	InsertedRows  int32              `json:"inserted_rows"`
	DuplicateRows int32              `json:"duplicate_rows"`
	Status        string             `json:"status"`
	CreatedBy     pgtype.Int8        `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type MonthlySummary struct {
	ID           int64              `json:"id"`
	Scope        string             `json:"scope"`
	AccountID    int64              `json:"account_id"`
	CostCenterID int64              `json:"cost_center_id"`
	Month        pgtype.Date        `json:"month"`
	Currency     string             `json:"currency"`
	TotalAmount  pgtype.Numeric     `json:"total_amount"`
	RecordCount  int32              `json:"record_count"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Organization struct {
	ID         int64              `json:"id"`
	ExternalID string             `json:"external_id"`
	Name       string             `json:"name"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type RebuildEvent struct {
	ID         int64              `json:"id"`
	Status     string             `json:"status"`
	StartedBy  pgtype.Int8        `json:"started_by"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
}

type User struct {
	ID        int64              `json:"id"`
	Username  string             `json:"username"`
	Role      string             `json:"role"`
	ApiToken  string             `json:"api_token"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type UserOrgGrant struct {
	UserID int64 `json:"user_id"`
	OrgID  int64 `json:"org_id"`
}
