// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: moderation.sql

package db

import (
	"context"

	"communityvault/internal/pgtypex"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelTaskForContent = `-- name: CancelTaskForContent :exec
UPDATE review_tasks SET status = 'cancelled', updated_at = now()
WHERE content_id = $1 AND status IN ('open','claimed')
`

func (q *Queries) CancelTaskForContent(ctx context.Context, contentID int64) error {
	_, err := q.db.Exec(ctx, cancelTaskForContent, contentID)
	return err
}

const claimNextTaskAdmin = `-- name: ClaimNextTaskAdmin :one
SELECT t.id, t.content_id, t.revision_id, t.status, t.created_at, t.updated_at
FROM review_tasks t
WHERE t.status = 'open'
ORDER BY t.id
LIMIT 1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) ClaimNextTaskAdmin(ctx context.Context) (ReviewTask, error) {
	row := q.db.QueryRow(ctx, claimNextTaskAdmin)
	var i ReviewTask
	err := row.Scan(
		&i.ID,
		&i.ContentID,
		&i.RevisionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimNextTaskModerator = `-- name: ClaimNextTaskModerator :one
SELECT t.id, t.content_id, t.revision_id, t.status, t.created_at, t.updated_at
FROM review_tasks t
JOIN contents ct ON ct.id = t.content_id
WHERE t.status = 'open'
  AND ct.category_id = ANY($1::bigint[])
ORDER BY t.id
LIMIT 1
FOR UPDATE SKIP LOCKED
`

// Claiming first recycles expired claims (RecycleExpiredClaims + DeleteClaim
// run in the same transaction before the pick below), then claims one open
// task with FOR UPDATE SKIP LOCKED so concurrent claimants never collide.
func (q *Queries) ClaimNextTaskModerator(ctx context.Context, dollar_1 []int64) (ReviewTask, error) {
	row := q.db.QueryRow(ctx, claimNextTaskModerator, dollar_1)
	var i ReviewTask
	err := row.Scan(
		&i.ID,
		&i.ContentID,
		&i.RevisionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeTaskWithGuard = `-- name: CompleteTaskWithGuard :one
UPDATE review_tasks t
SET status = 'done', updated_at = now()
FROM review_claims c
WHERE t.id = $1
  AND c.task_id = t.id
  AND c.claimant_id = $2
  AND c.expires_at > now()
  AND t.status = 'claimed'
  AND t.revision_id = $3
RETURNING t.id, t.content_id, t.revision_id, t.status, t.created_at, t.updated_at
`

type CompleteTaskWithGuardParams struct {
	ID         int64 `json:"id"`
	ClaimantID int64 `json:"claimant_id"`
	RevisionID int64 `json:"revision_id"`
}

// The WHERE guard is the stale-claim defense: an expired claim (or a claim
// recycled and re-claimed by someone else) updates 0 rows, so the late
// moderator's decision cannot overwrite the later resolution.
func (q *Queries) CompleteTaskWithGuard(ctx context.Context, arg CompleteTaskWithGuardParams) (ReviewTask, error) {
	row := q.db.QueryRow(ctx, completeTaskWithGuard, arg.ID, arg.ClaimantID, arg.RevisionID)
	var i ReviewTask
	err := row.Scan(
		&i.ID,
		&i.ContentID,
		&i.RevisionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteClaim = `-- name: DeleteClaim :exec
DELETE FROM review_claims WHERE task_id = $1
`

func (q *Queries) DeleteClaim(ctx context.Context, taskID int64) error {
	_, err := q.db.Exec(ctx, deleteClaim, taskID)
	return err
}

const deleteClaimForContent = `-- name: DeleteClaimForContent :exec
DELETE FROM review_claims
WHERE task_id = (SELECT id FROM review_tasks WHERE content_id = $1)
`

// Remove any claim attached to a content's task (used when the task is
// cancelled/reopened so the next claimant never hits the claims PK).
func (q *Queries) DeleteClaimForContent(ctx context.Context, contentID int64) error {
	_, err := q.db.Exec(ctx, deleteClaimForContent, contentID)
	return err
}

const getClaim = `-- name: GetClaim :one
SELECT task_id, claimant_id, claimed_at, expires_at FROM review_claims WHERE task_id = $1
`

func (q *Queries) GetClaim(ctx context.Context, taskID int64) (ReviewClaim, error) {
	row := q.db.QueryRow(ctx, getClaim, taskID)
	var i ReviewClaim
	err := row.Scan(
		&i.TaskID,
		&i.ClaimantID,
		&i.ClaimedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getTaskByContent = `-- name: GetTaskByContent :one
SELECT id, content_id, revision_id, status, created_at, updated_at FROM review_tasks WHERE content_id = $1
`

func (q *Queries) GetTaskByContent(ctx context.Context, contentID int64) (ReviewTask, error) {
	row := q.db.QueryRow(ctx, getTaskByContent, contentID)
	var i ReviewTask
	err := row.Scan(
		&i.ID,
		&i.ContentID,
		&i.RevisionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskForUpdate = `-- name: GetTaskForUpdate :one
SELECT id, content_id, revision_id, status, created_at, updated_at FROM review_tasks WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetTaskForUpdate(ctx context.Context, id int64) (ReviewTask, error) {
	row := q.db.QueryRow(ctx, getTaskForUpdate, id)
	var i ReviewTask
	err := row.Scan(
		&i.ID,
		&i.ContentID,
		&i.RevisionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertClaim = `-- name: InsertClaim :exec
INSERT INTO review_claims (task_id, claimant_id, claimed_at, expires_at)
VALUES ($1, $2, now(), $3)
`

type InsertClaimParams struct {
	TaskID     int64              `json:"task_id"`
	ClaimantID int64              `json:"claimant_id"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) InsertClaim(ctx context.Context, arg InsertClaimParams) error {
	_, err := q.db.Exec(ctx, insertClaim, arg.TaskID, arg.ClaimantID, arg.ExpiresAt)
	return err
}

const insertReview = `-- name: InsertReview :one
INSERT INTO reviews
    (content_id, revision_id, rule_version_id, reviewer_id, decision, reason, matched_words)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, content_id, revision_id, rule_version_id, reviewer_id, decision, reason, matched_words, created_at
`

type InsertReviewParams struct {
	ContentID     int64              `json:"content_id"`
	RevisionID    int64              `json:"revision_id"`
	RuleVersionID int64              `json:"rule_version_id"`
	ReviewerID    int64              `json:"reviewer_id"`
	Decision      string             `json:"decision"`
	Reason        string             `json:"reason"`
	MatchedWords  pgtypex.StringList `json:"matched_words"`
}

func (q *Queries) InsertReview(ctx context.Context, arg InsertReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, insertReview,
		arg.ContentID,
		arg.RevisionID,
		arg.RuleVersionID,
		arg.ReviewerID,
		arg.Decision,
		arg.Reason,
		arg.MatchedWords,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.ContentID,
		&i.RevisionID,
		&i.RuleVersionID,
		&i.ReviewerID,
		&i.Decision,
		&i.Reason,
		&i.MatchedWords,
		&i.CreatedAt,
	)
	return i, err
}

const listReviewsForContent = `-- name: ListReviewsForContent :many
SELECT id, content_id, revision_id, rule_version_id, reviewer_id, decision, reason, matched_words, created_at FROM reviews WHERE content_id = $1 ORDER BY id
`

func (q *Queries) ListReviewsForContent(ctx context.Context, contentID int64) ([]Review, error) {
	rows, err := q.db.Query(ctx, listReviewsForContent, contentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Review
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.ContentID,
			&i.RevisionID,
			&i.RuleVersionID,
			&i.ReviewerID,
			&i.Decision,
			&i.Reason,
			&i.MatchedWords,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsForRevision = `-- name: ListReviewsForRevision :many
SELECT id, content_id, revision_id, rule_version_id, reviewer_id, decision, reason, matched_words, created_at FROM reviews WHERE revision_id = $1 ORDER BY id
`

func (q *Queries) ListReviewsForRevision(ctx context.Context, revisionID int64) ([]Review, error) {
	rows, err := q.db.Query(ctx, listReviewsForRevision, revisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Review
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.ContentID,
			&i.RevisionID,
			&i.RuleVersionID,
			&i.ReviewerID,
			&i.Decision,
			&i.Reason,
			&i.MatchedWords,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTaskClaimed = `-- name: MarkTaskClaimed :one
UPDATE review_tasks
SET status = 'claimed', updated_at = now()
WHERE id = $1 AND status = 'open'
RETURNING id, content_id, revision_id, status, created_at, updated_at
`

func (q *Queries) MarkTaskClaimed(ctx context.Context, id int64) (ReviewTask, error) {
	row := q.db.QueryRow(ctx, markTaskClaimed, id)
	var i ReviewTask
	err := row.Scan(
		&i.ID,
		&i.ContentID,
		&i.RevisionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recycleExpiredClaims = `-- name: RecycleExpiredClaims :many
UPDATE review_tasks t
SET status = 'open', updated_at = now()
FROM review_claims c
WHERE c.task_id = t.id
  AND c.expires_at <= now()
  AND t.status = 'claimed'
RETURNING t.id
`

// Returns task ids whose claims just expired (caller deletes claims + flips
// status inside the same transaction).
func (q *Queries) RecycleExpiredClaims(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, recycleExpiredClaims)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPendingTask = `-- name: UpsertPendingTask :exec
INSERT INTO review_tasks (content_id, revision_id, status)
VALUES ($1, $2, 'open')
ON CONFLICT (content_id) DO UPDATE
SET revision_id = EXCLUDED.revision_id,
    status = 'open',
    updated_at = now()
`

type UpsertPendingTaskParams struct {
	ContentID  int64 `json:"content_id"`
	RevisionID int64 `json:"revision_id"`
}

func (q *Queries) UpsertPendingTask(ctx context.Context, arg UpsertPendingTaskParams) error {
	_, err := q.db.Exec(ctx, upsertPendingTask, arg.ContentID, arg.RevisionID)
	return err
}
