// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: phases.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const closeOpenPhase = `-- name: CloseOpenPhase :exec
UPDATE phase_records SET exited_at = now()
WHERE incident_id = $1 AND exited_at IS NULL
`

func (q *Queries) CloseOpenPhase(ctx context.Context, incidentID uuid.UUID) error {
	_, err := q.db.Exec(ctx, closeOpenPhase, incidentID)
	return err
}

const listPhases = `-- name: ListPhases :many
SELECT id, incident_id, phase, entered_at, exited_at FROM phase_records WHERE incident_id = $1 ORDER BY id
`

func (q *Queries) ListPhases(ctx context.Context, incidentID uuid.UUID) ([]PhaseRecord, error) {
	rows, err := q.db.Query(ctx, listPhases, incidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PhaseRecord
	for rows.Next() {
		var i PhaseRecord
		if err := rows.Scan(
			&i.ID,
			&i.IncidentID,
			&i.Phase,
			&i.EnteredAt,
			&i.ExitedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const openPhase = `-- name: OpenPhase :one
INSERT INTO phase_records (incident_id, phase)
VALUES ($1, $2::incident_status)
RETURNING id, incident_id, phase, entered_at, exited_at
`

type OpenPhaseParams struct {
	IncidentID uuid.UUID      `json:"incident_id"`
	Phase      IncidentStatus `json:"phase"`
}

func (q *Queries) OpenPhase(ctx context.Context, arg OpenPhaseParams) (PhaseRecord, error) {
	row := q.db.QueryRow(ctx, openPhase, arg.IncidentID, arg.Phase)
	var i PhaseRecord
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.Phase,
		&i.EnteredAt,
		&i.ExitedAt,
	)
	return i, err
}
