// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: publish.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bumpStoreVersion = `-- name: BumpStoreVersion :one
UPDATE stores SET current_version = current_version + 1
WHERE id = $1 AND current_version = $2
RETURNING current_version
`

type BumpStoreVersionParams struct {
	ID             pgtype.UUID `json:"id"`
	CurrentVersion int32       `json:"current_version"`
}

// Atomically claim the next version. Zero rows updated => expected_version
// did not match => exactly one concurrent publisher wins.
func (q *Queries) BumpStoreVersion(ctx context.Context, arg BumpStoreVersionParams) (int32, error) {
	row := q.db.QueryRow(ctx, bumpStoreVersion, arg.ID, arg.CurrentVersion)
	var current_version int32
	err := row.Scan(&current_version)
	return current_version, err
}

const copyDraftItemsToVersion = `-- name: CopyDraftItemsToVersion :exec
INSERT INTO version_items (version_id, item_key, name, price_cents, sold_out_threshold, position)
SELECT $1, item_key, name, price_cents, sold_out_threshold, position
FROM draft_items WHERE store_id = $2
`

type CopyDraftItemsToVersionParams struct {
	VersionID pgtype.UUID `json:"version_id"`
	StoreID   pgtype.UUID `json:"store_id"`
}

func (q *Queries) CopyDraftItemsToVersion(ctx context.Context, arg CopyDraftItemsToVersionParams) error {
	_, err := q.db.Exec(ctx, copyDraftItemsToVersion, arg.VersionID, arg.StoreID)
	return err
}

const copyDraftTempPricesToVersion = `-- name: CopyDraftTempPricesToVersion :exec
INSERT INTO version_temp_prices (version_id, item_key, price_cents, starts_at, ends_at)
SELECT $1, item_key, price_cents, starts_at, ends_at
FROM draft_temp_prices WHERE store_id = $2
`

type CopyDraftTempPricesToVersionParams struct {
	VersionID pgtype.UUID `json:"version_id"`
	StoreID   pgtype.UUID `json:"store_id"`
}

func (q *Queries) CopyDraftTempPricesToVersion(ctx context.Context, arg CopyDraftTempPricesToVersionParams) error {
	_, err := q.db.Exec(ctx, copyDraftTempPricesToVersion, arg.VersionID, arg.StoreID)
	return err
}

const createMenuVersion = `-- name: CreateMenuVersion :one
INSERT INTO menu_versions (store_id, version) VALUES ($1, $2) RETURNING id, store_id, version, published_at
`

type CreateMenuVersionParams struct {
	StoreID pgtype.UUID `json:"store_id"`
	Version int32       `json:"version"`
}

func (q *Queries) CreateMenuVersion(ctx context.Context, arg CreateMenuVersionParams) (MenuVersion, error) {
	row := q.db.QueryRow(ctx, createMenuVersion, arg.StoreID, arg.Version)
	var i MenuVersion
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Version,
		&i.PublishedAt,
	)
	return i, err
}
