// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	CountBillingRecords(ctx context.Context, arg CountBillingRecordsParams) (int64, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateBatch(ctx context.Context, arg CreateBatchParams) (ImportBatch, error)
	CreateBudgetVersion(ctx context.Context, arg CreateBudgetVersionParams) (Budget, error)
	CreateCostCenter(ctx context.Context, arg CreateCostCenterParams) (CostCenter, error)
	CreateOrg(ctx context.Context, arg CreateOrgParams) (Organization, error)
	CreateRebuildEvent(ctx context.Context, arg CreateRebuildEventParams) (RebuildEvent, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeactivateBudget(ctx context.Context, id int64) error
	FinishRebuildEvent(ctx context.Context, arg FinishRebuildEventParams) error
	GetAccountByExternalID(ctx context.Context, externalID string) (Account, error)
	GetActiveBudget(ctx context.Context, arg GetActiveBudgetParams) (Budget, error)
	GetCostCenterByCode(ctx context.Context, arg GetCostCenterByCodeParams) (CostCenter, error)
	GetCostCenterByID(ctx context.Context, id int64) (CostCenter, error)
	GetLatestAnomaly(ctx context.Context, arg GetLatestAnomalyParams) (AnomalyEvaluation, error)
	GetOrgByExternalID(ctx context.Context, externalID string) (Organization, error)
	GetOrgByID(ctx context.Context, id int64) (Organization, error)
	GetUserByToken(ctx context.Context, apiToken string) (User, error)
	GrantOrg(ctx context.Context, arg GrantOrgParams) error
	InsertAnomalyEvaluation(ctx context.Context, arg InsertAnomalyEvaluationParams) error
	InsertBudgetAlert(ctx context.Context, arg InsertBudgetAlertParams) (int64, error)
	ListAccounts(ctx context.Context, orgIds interface{}) ([]Account, error)
	ListAnomalies(ctx context.Context, arg ListAnomaliesParams) ([]AnomalyEvaluation, error)
	ListAnomalyVersions(ctx context.Context, arg ListAnomalyVersionsParams) ([]AnomalyEvaluation, error)
	ListBatches(ctx context.Context, arg ListBatchesParams) ([]ImportBatch, error)
	ListBillingRecords(ctx context.Context, arg ListBillingRecordsParams) ([]BillingRecord, error)
	ListBudgetAlerts(ctx context.Context, ccIds interface{}) ([]ListBudgetAlertsRow, error)
	ListBudgetVersions(ctx context.Context, ccIds interface{}) ([]Budget, error)
	ListCostCenters(ctx context.Context, orgIds interface{}) ([]CostCenter, error)
	ListDailySummaries(ctx context.Context, arg ListDailySummariesParams) ([]DailySummary, error)
	ListGrantedOrgIDs(ctx context.Context, userID int64) ([]int64, error)
	ListMonthlySummaries(ctx context.Context, arg ListMonthlySummariesParams) ([]MonthlySummary, error)
	ListOrgs(ctx context.Context) ([]Organization, error)
	ListUsers(ctx context.Context) ([]User, error)
	MarkBatch(ctx context.Context, arg MarkBatchParams) error
	NextAnomalyVersion(ctx context.Context, arg NextAnomalyVersionParams) (int32, error)
	NextBudgetVersion(ctx context.Context, arg NextBudgetVersionParams) (int32, error)
}

var _ Querier = (*Queries)(nil)
