// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: reports.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const feedPublished = `-- name: FeedPublished :many
SELECT c.id, c.category_id, c.author_id, c.title, c.status,
       c.current_revision, c.published_revision,
       c.created_at, c.updated_at,
       r.body AS body, r.revision_no AS revision_no
FROM contents c
JOIN content_revisions r ON r.id = c.published_revision
WHERE c.status = 'published' AND c.id < $1
ORDER BY c.id DESC
LIMIT $2
`

type FeedPublishedParams struct {
	ID    int64 `json:"id"`
	Limit int32 `json:"limit"`
}

type FeedPublishedRow struct {
	ID                int64              `json:"id"`
	CategoryID        int64              `json:"category_id"`
	AuthorID          int64              `json:"author_id"`
	Title             string             `json:"title"`
	Status            string             `json:"status"`
	CurrentRevision   *int64             `json:"current_revision"`
	PublishedRevision *int64             `json:"published_revision"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Body              string             `json:"body"`
	RevisionNo        int32              `json:"revision_no"`
}

// Stable cursor feed. Published content only, keyed on the monotonic
// surrogate id: rows never move within or across pages when newer rows are
// inserted or older rows are withdrawn mid-pagination. Joins only against
// the published revision, so a new (pending) revision created after
// publication is never leaked through the feed.
func (q *Queries) FeedPublished(ctx context.Context, arg FeedPublishedParams) ([]FeedPublishedRow, error) {
	rows, err := q.db.Query(ctx, feedPublished, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeedPublishedRow
	for rows.Next() {
		var i FeedPublishedRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.AuthorID,
			&i.Title,
			&i.Status,
			&i.CurrentRevision,
			&i.PublishedRevision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Body,
			&i.RevisionNo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertReport = `-- name: InsertReport :one
INSERT INTO reports (content_id, reporter_id, reason)
VALUES ($1, $2, $3)
RETURNING id, content_id, reporter_id, reason, created_at
`

type InsertReportParams struct {
	ContentID  int64  `json:"content_id"`
	ReporterID int64  `json:"reporter_id"`
	Reason     string `json:"reason"`
}

func (q *Queries) InsertReport(ctx context.Context, arg InsertReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, insertReport, arg.ContentID, arg.ReporterID, arg.Reason)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ContentID,
		&i.ReporterID,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const listAllReports = `-- name: ListAllReports :many
SELECT r.id, r.content_id, r.reporter_id, r.reason, r.created_at FROM reports r
ORDER BY r.id DESC LIMIT $1
`

func (q *Queries) ListAllReports(ctx context.Context, limit int32) ([]Report, error) {
	rows, err := q.db.Query(ctx, listAllReports, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Report
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.ContentID,
			&i.ReporterID,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportsForContent = `-- name: ListReportsForContent :many
SELECT id, content_id, reporter_id, reason, created_at FROM reports WHERE content_id = $1 ORDER BY id
`

func (q *Queries) ListReportsForContent(ctx context.Context, contentID int64) ([]Report, error) {
	rows, err := q.db.Query(ctx, listReportsForContent, contentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Report
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.ContentID,
			&i.ReporterID,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportsInCategories = `-- name: ListReportsInCategories :many
SELECT r.id, r.content_id, r.reporter_id, r.reason, r.created_at FROM reports r
JOIN contents c ON c.id = r.content_id
WHERE c.category_id = ANY($1::bigint[])
ORDER BY r.id DESC LIMIT $2
`

type ListReportsInCategoriesParams struct {
	Column1 []int64 `json:"column_1"`
	Limit   int32   `json:"limit"`
}

func (q *Queries) ListReportsInCategories(ctx context.Context, arg ListReportsInCategoriesParams) ([]Report, error) {
	rows, err := q.db.Query(ctx, listReportsInCategories, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Report
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.ContentID,
			&i.ReporterID,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
