// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: rules.sql

package db

import (
	"context"
)

const activateRule = `-- name: ActivateRule :exec
UPDATE rule_versions SET active = true, activated_at = now() WHERE id = $1
`

func (q *Queries) ActivateRule(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, activateRule, id)
	return err
}

const addSensitiveWord = `-- name: AddSensitiveWord :exec
INSERT INTO sensitive_words (rule_version_id, word)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddSensitiveWordParams struct {
	RuleVersionID int64  `json:"rule_version_id"`
	Word          string `json:"word"`
}

func (q *Queries) AddSensitiveWord(ctx context.Context, arg AddSensitiveWordParams) error {
	_, err := q.db.Exec(ctx, addSensitiveWord, arg.RuleVersionID, arg.Word)
	return err
}

const createRuleVersion = `-- name: CreateRuleVersion :one
INSERT INTO rule_versions (version, note) VALUES ($1, $2) RETURNING id, version, note, active, created_at, activated_at
`

type CreateRuleVersionParams struct {
	Version int32  `json:"version"`
	Note    string `json:"note"`
}

func (q *Queries) CreateRuleVersion(ctx context.Context, arg CreateRuleVersionParams) (RuleVersion, error) {
	row := q.db.QueryRow(ctx, createRuleVersion, arg.Version, arg.Note)
	var i RuleVersion
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Note,
		&i.Active,
		&i.CreatedAt,
		&i.ActivatedAt,
	)
	return i, err
}

const deactivateActiveRules = `-- name: DeactivateActiveRules :exec
UPDATE rule_versions SET active = false, activated_at = NULL WHERE active
`

func (q *Queries) DeactivateActiveRules(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deactivateActiveRules)
	return err
}

const getActiveRule = `-- name: GetActiveRule :one
SELECT id, version, note, active, created_at, activated_at FROM rule_versions WHERE active = true ORDER BY version DESC LIMIT 1
`

func (q *Queries) GetActiveRule(ctx context.Context) (RuleVersion, error) {
	row := q.db.QueryRow(ctx, getActiveRule)
	var i RuleVersion
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Note,
		&i.Active,
		&i.CreatedAt,
		&i.ActivatedAt,
	)
	return i, err
}

const getRuleVersion = `-- name: GetRuleVersion :one
SELECT id, version, note, active, created_at, activated_at FROM rule_versions WHERE id = $1
`

func (q *Queries) GetRuleVersion(ctx context.Context, id int64) (RuleVersion, error) {
	row := q.db.QueryRow(ctx, getRuleVersion, id)
	var i RuleVersion
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Note,
		&i.Active,
		&i.CreatedAt,
		&i.ActivatedAt,
	)
	return i, err
}

const listRuleVersions = `-- name: ListRuleVersions :many
SELECT id, version, note, active, created_at, activated_at FROM rule_versions ORDER BY version DESC
`

func (q *Queries) ListRuleVersions(ctx context.Context) ([]RuleVersion, error) {
	rows, err := q.db.Query(ctx, listRuleVersions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RuleVersion
	for rows.Next() {
		var i RuleVersion
		if err := rows.Scan(
			&i.ID,
			&i.Version,
			&i.Note,
			&i.Active,
			&i.CreatedAt,
			&i.ActivatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuleWords = `-- name: ListRuleWords :many
SELECT word FROM sensitive_words WHERE rule_version_id = $1 ORDER BY word
`

func (q *Queries) ListRuleWords(ctx context.Context, ruleVersionID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listRuleWords, ruleVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var word string
		if err := rows.Scan(&word); err != nil {
			return nil, err
		}
		items = append(items, word)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRuleAdvisory = `-- name: LockRuleAdvisory :exec
SELECT pg_advisory_xact_lock(91729329)
`

// Transaction-scoped advisory lock. Publishing and rule activation both take
// this same lock, so a publish racing a rule switch has a deterministic
// winner rule version: the one active when the lock is acquired.
func (q *Queries) LockRuleAdvisory(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockRuleAdvisory)
	return err
}

const maxRuleVersion = `-- name: MaxRuleVersion :one
SELECT COALESCE(MAX(version), 0)::INTEGER AS version FROM rule_versions
`

func (q *Queries) MaxRuleVersion(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, maxRuleVersion)
	var version int32
	err := row.Scan(&version)
	return version, err
}
