// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: screens.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createScreen = `-- name: CreateScreen :one
INSERT INTO screens (store_id, name, token_hash) VALUES ($1, $2, $3) RETURNING id, store_id, name, token_hash, created_at, last_heartbeat_at
`

type CreateScreenParams struct {
	StoreID   pgtype.UUID `json:"store_id"`
	Name      string      `json:"name"`
	TokenHash string      `json:"token_hash"`
}

func (q *Queries) CreateScreen(ctx context.Context, arg CreateScreenParams) (Screen, error) {
	row := q.db.QueryRow(ctx, createScreen, arg.StoreID, arg.Name, arg.TokenHash)
	var i Screen
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastHeartbeatAt,
	)
	return i, err
}

const getScreenByTokenHash = `-- name: GetScreenByTokenHash :one
SELECT id, store_id, name, token_hash, created_at, last_heartbeat_at FROM screens WHERE token_hash = $1
`

func (q *Queries) GetScreenByTokenHash(ctx context.Context, tokenHash string) (Screen, error) {
	row := q.db.QueryRow(ctx, getScreenByTokenHash, tokenHash)
	var i Screen
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastHeartbeatAt,
	)
	return i, err
}

const heartbeat = `-- name: Heartbeat :exec
UPDATE screens SET last_heartbeat_at = now() WHERE id = $1
`

func (q *Queries) Heartbeat(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, heartbeat, id)
	return err
}

const listScreens = `-- name: ListScreens :many
SELECT id, store_id, name, created_at, last_heartbeat_at,
       COALESCE(last_heartbeat_at > now() - interval '90 seconds', false) AS online
FROM screens WHERE store_id = $1 ORDER BY created_at
`

type ListScreensRow struct {
	ID              pgtype.UUID        `json:"id"`
	StoreID         pgtype.UUID        `json:"store_id"`
	Name            string             `json:"name"`
	CreatedAt       time.Time          `json:"created_at"`
	LastHeartbeatAt pgtype.Timestamptz `json:"last_heartbeat_at"`
	Online          interface{}        `json:"online"`
}

func (q *Queries) ListScreens(ctx context.Context, storeID pgtype.UUID) ([]ListScreensRow, error) {
	rows, err := q.db.Query(ctx, listScreens, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScreensRow{}
	for rows.Next() {
		var i ListScreensRow
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.Name,
			&i.CreatedAt,
			&i.LastHeartbeatAt,
			&i.Online,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
