// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: transactions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const applyRefund = `-- name: ApplyRefund :one
UPDATE transactions
SET status = CASE WHEN refunded_cents + $2 >= captured_cents THEN 'refunded'
                  ELSE 'partially_refunded' END,
    refunded_cents = refunded_cents + $2,
    refunded_fee_cents = refunded_fee_cents + $3
WHERE id = $1
RETURNING id, merchant_id, status, amount_cents, captured_cents, fee_cents, refunded_cents, refunded_fee_cents, settled_cents, currency, card_last4, auth_expires_at, settled_at, refund_deadline, created_at, captured_at
`

type ApplyRefundParams struct {
	ID               uuid.UUID `json:"id"`
	RefundedCents    int64     `json:"refunded_cents"`
	RefundedFeeCents int64     `json:"refunded_fee_cents"`
}

func (q *Queries) ApplyRefund(ctx context.Context, arg ApplyRefundParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, applyRefund, arg.ID, arg.RefundedCents, arg.RefundedFeeCents)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Status,
		&i.AmountCents,
		&i.CapturedCents,
		&i.FeeCents,
		&i.RefundedCents,
		&i.RefundedFeeCents,
		&i.SettledCents,
		&i.Currency,
		&i.CardLast4,
		&i.AuthExpiresAt,
		&i.SettledAt,
		&i.RefundDeadline,
		&i.CreatedAt,
		&i.CapturedAt,
	)
	return i, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO transactions (
    merchant_id, amount_cents, card_last4, auth_expires_at, created_at
) VALUES (
    $1,
    $2,
    $3,
    $4::timestamptz,
    $5::timestamptz
)
RETURNING id, merchant_id, status, amount_cents, captured_cents, fee_cents, refunded_cents, refunded_fee_cents, settled_cents, currency, card_last4, auth_expires_at, settled_at, refund_deadline, created_at, captured_at
`

type CreatePaymentParams struct {
	MerchantID    uuid.UUID          `json:"merchant_id"`
	AmountCents   int64              `json:"amount_cents"`
	CardLast4     string             `json:"card_last4"`
	AuthExpiresAt pgtype.Timestamptz `json:"auth_expires_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.MerchantID,
		arg.AmountCents,
		arg.CardLast4,
		arg.AuthExpiresAt,
		arg.CreatedAt,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Status,
		&i.AmountCents,
		&i.CapturedCents,
		&i.FeeCents,
		&i.RefundedCents,
		&i.RefundedFeeCents,
		&i.SettledCents,
		&i.Currency,
		&i.CardLast4,
		&i.AuthExpiresAt,
		&i.SettledAt,
		&i.RefundDeadline,
		&i.CreatedAt,
		&i.CapturedAt,
	)
	return i, err
}

const createRefund = `-- name: CreateRefund :one
INSERT INTO refunds (payment_id, merchant_id, amount_cents, fee_refund_cents, net_cents, reason, created_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7::timestamptz
)
RETURNING id, payment_id, merchant_id, amount_cents, fee_refund_cents, net_cents, reason, created_at
`

type CreateRefundParams struct {
	PaymentID      uuid.UUID          `json:"payment_id"`
	MerchantID     uuid.UUID          `json:"merchant_id"`
	AmountCents    int64              `json:"amount_cents"`
	FeeRefundCents int64              `json:"fee_refund_cents"`
	NetCents       int64              `json:"net_cents"`
	Reason         string             `json:"reason"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateRefund(ctx context.Context, arg CreateRefundParams) (Refund, error) {
	row := q.db.QueryRow(ctx, createRefund,
		arg.PaymentID,
		arg.MerchantID,
		arg.AmountCents,
		arg.FeeRefundCents,
		arg.NetCents,
		arg.Reason,
		arg.CreatedAt,
	)
	var i Refund
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.MerchantID,
		&i.AmountCents,
		&i.FeeRefundCents,
		&i.NetCents,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const getPayment = `-- name: GetPayment :one
SELECT id, merchant_id, status, amount_cents, captured_cents, fee_cents, refunded_cents, refunded_fee_cents, settled_cents, currency, card_last4, auth_expires_at, settled_at, refund_deadline, created_at, captured_at FROM transactions WHERE id = $1
`

func (q *Queries) GetPayment(ctx context.Context, id uuid.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getPayment, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Status,
		&i.AmountCents,
		&i.CapturedCents,
		&i.FeeCents,
		&i.RefundedCents,
		&i.RefundedFeeCents,
		&i.SettledCents,
		&i.Currency,
		&i.CardLast4,
		&i.AuthExpiresAt,
		&i.SettledAt,
		&i.RefundDeadline,
		&i.CreatedAt,
		&i.CapturedAt,
	)
	return i, err
}

const getPaymentForUpdate = `-- name: GetPaymentForUpdate :one
SELECT id, merchant_id, status, amount_cents, captured_cents, fee_cents, refunded_cents, refunded_fee_cents, settled_cents, currency, card_last4, auth_expires_at, settled_at, refund_deadline, created_at, captured_at FROM transactions WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetPaymentForUpdate(ctx context.Context, id uuid.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getPaymentForUpdate, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Status,
		&i.AmountCents,
		&i.CapturedCents,
		&i.FeeCents,
		&i.RefundedCents,
		&i.RefundedFeeCents,
		&i.SettledCents,
		&i.Currency,
		&i.CardLast4,
		&i.AuthExpiresAt,
		&i.SettledAt,
		&i.RefundDeadline,
		&i.CreatedAt,
		&i.CapturedAt,
	)
	return i, err
}

const getRefund = `-- name: GetRefund :one
SELECT id, payment_id, merchant_id, amount_cents, fee_refund_cents, net_cents, reason, created_at FROM refunds WHERE id = $1
`

func (q *Queries) GetRefund(ctx context.Context, id uuid.UUID) (Refund, error) {
	row := q.db.QueryRow(ctx, getRefund, id)
	var i Refund
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.MerchantID,
		&i.AmountCents,
		&i.FeeRefundCents,
		&i.NetCents,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const listPaymentsByMerchant = `-- name: ListPaymentsByMerchant :many
SELECT id, merchant_id, status, amount_cents, captured_cents, fee_cents, refunded_cents, refunded_fee_cents, settled_cents, currency, card_last4, auth_expires_at, settled_at, refund_deadline, created_at, captured_at FROM transactions
WHERE merchant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPaymentsByMerchantParams struct {
	MerchantID uuid.UUID `json:"merchant_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) ListPaymentsByMerchant(ctx context.Context, arg ListPaymentsByMerchantParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listPaymentsByMerchant, arg.MerchantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Status,
			&i.AmountCents,
			&i.CapturedCents,
			&i.FeeCents,
			&i.RefundedCents,
			&i.RefundedFeeCents,
			&i.SettledCents,
			&i.Currency,
			&i.CardLast4,
			&i.AuthExpiresAt,
			&i.SettledAt,
			&i.RefundDeadline,
			&i.CreatedAt,
			&i.CapturedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRefundsByMerchant = `-- name: ListRefundsByMerchant :many
SELECT id, payment_id, merchant_id, amount_cents, fee_refund_cents, net_cents, reason, created_at FROM refunds
WHERE merchant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListRefundsByMerchantParams struct {
	MerchantID uuid.UUID `json:"merchant_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) ListRefundsByMerchant(ctx context.Context, arg ListRefundsByMerchantParams) ([]Refund, error) {
	rows, err := q.db.Query(ctx, listRefundsByMerchant, arg.MerchantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Refund{}
	for rows.Next() {
		var i Refund
		if err := rows.Scan(
			&i.ID,
			&i.PaymentID,
			&i.MerchantID,
			&i.AmountCents,
			&i.FeeRefundCents,
			&i.NetCents,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCaptured = `-- name: MarkCaptured :one
UPDATE transactions
SET status = 'captured',
    captured_cents = $2,
    fee_cents = $3,
    captured_at = $4
WHERE id = $1
RETURNING id, merchant_id, status, amount_cents, captured_cents, fee_cents, refunded_cents, refunded_fee_cents, settled_cents, currency, card_last4, auth_expires_at, settled_at, refund_deadline, created_at, captured_at
`

type MarkCapturedParams struct {
	ID            uuid.UUID          `json:"id"`
	CapturedCents int64              `json:"captured_cents"`
	FeeCents      int64              `json:"fee_cents"`
	CapturedAt    pgtype.Timestamptz `json:"captured_at"`
}

func (q *Queries) MarkCaptured(ctx context.Context, arg MarkCapturedParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, markCaptured,
		arg.ID,
		arg.CapturedCents,
		arg.FeeCents,
		arg.CapturedAt,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Status,
		&i.AmountCents,
		&i.CapturedCents,
		&i.FeeCents,
		&i.RefundedCents,
		&i.RefundedFeeCents,
		&i.SettledCents,
		&i.Currency,
		&i.CardLast4,
		&i.AuthExpiresAt,
		&i.SettledAt,
		&i.RefundDeadline,
		&i.CreatedAt,
		&i.CapturedAt,
	)
	return i, err
}

const markSettled = `-- name: MarkSettled :one
UPDATE transactions
SET status = CASE WHEN refunded_cents > 0 AND refunded_cents >= captured_cents
                    THEN 'refunded'
                  ELSE 'settled' END,
    settled_cents = captured_cents - refunded_cents,
    settled_at = $2,
    refund_deadline = $2::timestamptz + INTERVAL '90 days'
WHERE id = $1
RETURNING id, merchant_id, status, amount_cents, captured_cents, fee_cents, refunded_cents, refunded_fee_cents, settled_cents, currency, card_last4, auth_expires_at, settled_at, refund_deadline, created_at, captured_at
`

type MarkSettledParams struct {
	ID        uuid.UUID          `json:"id"`
	SettledAt pgtype.Timestamptz `json:"settled_at"`
}

func (q *Queries) MarkSettled(ctx context.Context, arg MarkSettledParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, markSettled, arg.ID, arg.SettledAt)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Status,
		&i.AmountCents,
		&i.CapturedCents,
		&i.FeeCents,
		&i.RefundedCents,
		&i.RefundedFeeCents,
		&i.SettledCents,
		&i.Currency,
		&i.CardLast4,
		&i.AuthExpiresAt,
		&i.SettledAt,
		&i.RefundDeadline,
		&i.CreatedAt,
		&i.CapturedAt,
	)
	return i, err
}

const markVoided = `-- name: MarkVoided :one
UPDATE transactions
SET status = 'voided'
WHERE id = $1
RETURNING id, merchant_id, status, amount_cents, captured_cents, fee_cents, refunded_cents, refunded_fee_cents, settled_cents, currency, card_last4, auth_expires_at, settled_at, refund_deadline, created_at, captured_at
`

func (q *Queries) MarkVoided(ctx context.Context, id uuid.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, markVoided, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Status,
		&i.AmountCents,
		&i.CapturedCents,
		&i.FeeCents,
		&i.RefundedCents,
		&i.RefundedFeeCents,
		&i.SettledCents,
		&i.Currency,
		&i.CardLast4,
		&i.AuthExpiresAt,
		&i.SettledAt,
		&i.RefundDeadline,
		&i.CreatedAt,
		&i.CapturedAt,
	)
	return i, err
}
