// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, role, api_token)
VALUES ($1, $2, $3)
RETURNING id, username, role, api_token, created_at
`

type CreateUserParams struct {
	Username string `json:"username"`
	Role     string `json:"role"`
	ApiToken string `json:"api_token"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Role, arg.ApiToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Role,
		&i.ApiToken,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByToken = `-- name: GetUserByToken :one
SELECT id, username, role, api_token, created_at FROM users WHERE api_token = $1
`

func (q *Queries) GetUserByToken(ctx context.Context, apiToken string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByToken, apiToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Role,
		&i.ApiToken,
		&i.CreatedAt,
	)
	return i, err
}

const grantOrg = `-- name: GrantOrg :exec
INSERT INTO user_org_grants (user_id, org_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type GrantOrgParams struct {
	UserID int64 `json:"user_id"`
	OrgID  int64 `json:"org_id"`
}

func (q *Queries) GrantOrg(ctx context.Context, arg GrantOrgParams) error {
	_, err := q.db.Exec(ctx, grantOrg, arg.UserID, arg.OrgID)
	return err
}

const listGrantedOrgIDs = `-- name: ListGrantedOrgIDs :many
SELECT org_id FROM user_org_grants WHERE user_id = $1 ORDER BY org_id
`

func (q *Queries) ListGrantedOrgIDs(ctx context.Context, userID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listGrantedOrgIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var org_id int64
		if err := rows.Scan(&org_id); err != nil {
			return nil, err
		}
		items = append(items, org_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, role, api_token, created_at FROM users ORDER BY id
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Role,
			&i.ApiToken,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
