// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package db

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT id, username, role, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listScopes = `-- name: ListScopes :many
SELECT user_id, category FROM moderator_scopes WHERE user_id = $1
`

func (q *Queries) ListScopes(ctx context.Context, userID int64) ([]ModeratorScope, error) {
	rows, err := q.db.Query(ctx, listScopes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModeratorScope
	for rows.Next() {
		var i ModeratorScope
		if err := rows.Scan(&i.UserID, &i.Category); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
