// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DailySale struct {
	ID       int64       `json:"id"`
	StoreID  int64       `json:"store_id"`
	SalesDay pgtype.Date `json:"sales_day"`
	DishID   int64       `json:"dish_id"`
	Quantity int64       `json:"quantity"`
	SoldOut  bool        `json:"sold_out"`
}

type Dish struct {
	ID        int64              `json:"id"`
	StoreID   int64              `json:"store_id"`
	Name      string             `json:"name"`
	BasePrice int64              `json:"base_price"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type DraftItem struct {
	ID       int64  `json:"id"`
	DraftID  int64  `json:"draft_id"`
	DishID   int64  `json:"dish_id"`
	Position int32  `json:"position"`
	Price    *int64 `json:"price"`
}

type MenuDraft struct {
	ID        int64              `json:"id"`
	StoreID   int64              `json:"store_id"`
	Version   int64              `json:"version"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type MenuVersion struct {
	ID          int64              `json:"id"`
	StoreID     int64              `json:"store_id"`
	Version     int64              `json:"version"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	PublishedBy string             `json:"published_by"`
}

type MenuVersionItem struct {
	ID        int64  `json:"id"`
	VersionID int64  `json:"version_id"`
	DishID    int64  `json:"dish_id"`
	DishName  string `json:"dish_name"`
	Position  int32  `json:"position"`
	Price     int64  `json:"price"`
}

type SalesEvent struct {
	ID         int64              `json:"id"`
	StoreID    int64              `json:"store_id"`
	EventID    string             `json:"event_id"`
	DishID     int64              `json:"dish_id"`
	Quantity   int32              `json:"quantity"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	ReceivedAt pgtype.Timestamptz `json:"received_at"`
}

type Screen struct {
	ID         int64              `json:"id"`
	StoreID    int64              `json:"store_id"`
	Name       string             `json:"name"`
	TokenHash  string             `json:"token_hash"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type SelloutThreshold struct {
	StoreID   int64 `json:"store_id"`
	DishID    int64 `json:"dish_id"`
	Threshold int64 `json:"threshold"`
}

type Store struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	Timezone  string             `json:"timezone"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type TempPrice struct {
	ID        int64              `json:"id"`
	VersionID int64              `json:"version_id"`
	DishID    int64              `json:"dish_id"`
	Price     int64              `json:"price"`
	StartsAt  pgtype.Timestamptz `json:"starts_at"`
	EndsAt    pgtype.Timestamptz `json:"ends_at"`
}
