// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	ActiveTempPricesAt(ctx context.Context, arg ActiveTempPricesAtParams) ([]TempPrice, error)
	BumpDraftVersion(ctx context.Context, storeID int64) error
	ClearDraftItems(ctx context.Context, draftID int64) error
	CountSoldOutByDay(ctx context.Context, arg CountSoldOutByDayParams) (int64, error)
	CreateDish(ctx context.Context, arg CreateDishParams) (Dish, error)
	CreateScreen(ctx context.Context, arg CreateScreenParams) (Screen, error)
	CreateStore(ctx context.Context, arg CreateStoreParams) (Store, error)
	DeleteTempPricesForVersion(ctx context.Context, versionID int64) error
	GetDailySales(ctx context.Context, arg GetDailySalesParams) (DailySale, error)
	GetDish(ctx context.Context, arg GetDishParams) (Dish, error)
	GetDraft(ctx context.Context, storeID int64) (MenuDraft, error)
	GetLatestPublishedVersion(ctx context.Context, storeID int64) (MenuVersion, error)
	GetOrCreateDraft(ctx context.Context, storeID int64) (MenuDraft, error)
	GetPublishedVersionByNumber(ctx context.Context, arg GetPublishedVersionByNumberParams) (MenuVersion, error)
	GetSalesEvent(ctx context.Context, arg GetSalesEventParams) (SalesEvent, error)
	GetScreenByTokenHash(ctx context.Context, tokenHash string) (Screen, error)
	GetStore(ctx context.Context, id int64) (Store, error)
	GetThreshold(ctx context.Context, arg GetThresholdParams) (SelloutThreshold, error)
	GetVersionByID(ctx context.Context, id int64) (MenuVersion, error)
	InsertDraftItem(ctx context.Context, arg InsertDraftItemParams) (DraftItem, error)
	InsertMenuVersion(ctx context.Context, arg InsertMenuVersionParams) (MenuVersion, error)
	InsertMenuVersionItem(ctx context.Context, arg InsertMenuVersionItemParams) error
	InsertSalesEvent(ctx context.Context, arg InsertSalesEventParams) (SalesEvent, error)
	InsertTempPrice(ctx context.Context, arg InsertTempPriceParams) error
	ListDailySalesForDay(ctx context.Context, arg ListDailySalesForDayParams) ([]DailySale, error)
	ListDishes(ctx context.Context, storeID int64) ([]Dish, error)
	ListDraftItems(ctx context.Context, draftID int64) ([]ListDraftItemsRow, error)
	ListScreensByStore(ctx context.Context, storeID int64) ([]Screen, error)
	ListSoldOutForDay(ctx context.Context, arg ListSoldOutForDayParams) ([]int64, error)
	ListStores(ctx context.Context) ([]Store, error)
	ListTempPricesForVersion(ctx context.Context, versionID int64) ([]TempPrice, error)
	ListThresholds(ctx context.Context, storeID int64) ([]SelloutThreshold, error)
	ListVersionItems(ctx context.Context, versionID int64) ([]MenuVersionItem, error)
	LockStore(ctx context.Context, id int64) error
	MarkSoldOut(ctx context.Context, arg MarkSoldOutParams) error
	SetDishActive(ctx context.Context, arg SetDishActiveParams) (int64, error)
	SetDishPrice(ctx context.Context, arg SetDishPriceParams) (int64, error)
	TouchScreen(ctx context.Context, id int64) error
	UpsertDailySales(ctx context.Context, arg UpsertDailySalesParams) (DailySale, error)
	UpsertDish(ctx context.Context, arg UpsertDishParams) (Dish, error)
	UpsertThreshold(ctx context.Context, arg UpsertThresholdParams) (SelloutThreshold, error)
}

var _ Querier = (*Queries)(nil)
