// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: sales.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSoldOutByDay = `-- name: CountSoldOutByDay :one
SELECT count(*) FROM daily_sales
WHERE store_id = $1 AND sales_day = $2 AND sold_out = true
`

type CountSoldOutByDayParams struct {
	StoreID  int64       `json:"store_id"`
	SalesDay pgtype.Date `json:"sales_day"`
}

func (q *Queries) CountSoldOutByDay(ctx context.Context, arg CountSoldOutByDayParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSoldOutByDay, arg.StoreID, arg.SalesDay)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDailySales = `-- name: GetDailySales :one
SELECT id, store_id, sales_day, dish_id, quantity, sold_out
FROM daily_sales WHERE store_id = $1 AND sales_day = $2 AND dish_id = $3
`

type GetDailySalesParams struct {
	StoreID  int64       `json:"store_id"`
	SalesDay pgtype.Date `json:"sales_day"`
	DishID   int64       `json:"dish_id"`
}

func (q *Queries) GetDailySales(ctx context.Context, arg GetDailySalesParams) (DailySale, error) {
	row := q.db.QueryRow(ctx, getDailySales, arg.StoreID, arg.SalesDay, arg.DishID)
	var i DailySale
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.SalesDay,
		&i.DishID,
		&i.Quantity,
		&i.SoldOut,
	)
	return i, err
}

const getSalesEvent = `-- name: GetSalesEvent :one
SELECT id, store_id, event_id, dish_id, quantity, occurred_at, received_at
FROM sales_events WHERE store_id = $1 AND event_id = $2
`

type GetSalesEventParams struct {
	StoreID int64  `json:"store_id"`
	EventID string `json:"event_id"`
}

func (q *Queries) GetSalesEvent(ctx context.Context, arg GetSalesEventParams) (SalesEvent, error) {
	row := q.db.QueryRow(ctx, getSalesEvent, arg.StoreID, arg.EventID)
	var i SalesEvent
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.EventID,
		&i.DishID,
		&i.Quantity,
		&i.OccurredAt,
		&i.ReceivedAt,
	)
	return i, err
}

const insertSalesEvent = `-- name: InsertSalesEvent :one
INSERT INTO sales_events (store_id, event_id, dish_id, quantity, occurred_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, store_id, event_id, dish_id, quantity, occurred_at, received_at
`

type InsertSalesEventParams struct {
	StoreID    int64              `json:"store_id"`
	EventID    string             `json:"event_id"`
	DishID     int64              `json:"dish_id"`
	Quantity   int32              `json:"quantity"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) InsertSalesEvent(ctx context.Context, arg InsertSalesEventParams) (SalesEvent, error) {
	row := q.db.QueryRow(ctx, insertSalesEvent,
		arg.StoreID,
		arg.EventID,
		arg.DishID,
		arg.Quantity,
		arg.OccurredAt,
	)
	var i SalesEvent
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.EventID,
		&i.DishID,
		&i.Quantity,
		&i.OccurredAt,
		&i.ReceivedAt,
	)
	return i, err
}

const listDailySalesForDay = `-- name: ListDailySalesForDay :many
SELECT id, store_id, sales_day, dish_id, quantity, sold_out
FROM daily_sales
WHERE store_id = $1 AND sales_day = $2
ORDER BY dish_id
`

type ListDailySalesForDayParams struct {
	StoreID  int64       `json:"store_id"`
	SalesDay pgtype.Date `json:"sales_day"`
}

func (q *Queries) ListDailySalesForDay(ctx context.Context, arg ListDailySalesForDayParams) ([]DailySale, error) {
	rows, err := q.db.Query(ctx, listDailySalesForDay, arg.StoreID, arg.SalesDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailySale
	for rows.Next() {
		var i DailySale
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.SalesDay,
			&i.DishID,
			&i.Quantity,
			&i.SoldOut,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSoldOutForDay = `-- name: ListSoldOutForDay :many
SELECT dish_id FROM daily_sales
WHERE store_id = $1 AND sales_day = $2 AND sold_out = true
`

type ListSoldOutForDayParams struct {
	StoreID  int64       `json:"store_id"`
	SalesDay pgtype.Date `json:"sales_day"`
}

func (q *Queries) ListSoldOutForDay(ctx context.Context, arg ListSoldOutForDayParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listSoldOutForDay, arg.StoreID, arg.SalesDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var dish_id int64
		if err := rows.Scan(&dish_id); err != nil {
			return nil, err
		}
		items = append(items, dish_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSoldOut = `-- name: MarkSoldOut :exec
UPDATE daily_sales SET sold_out = true
WHERE store_id = $1 AND sales_day = $2 AND dish_id = $3
`

type MarkSoldOutParams struct {
	StoreID  int64       `json:"store_id"`
	SalesDay pgtype.Date `json:"sales_day"`
	DishID   int64       `json:"dish_id"`
}

func (q *Queries) MarkSoldOut(ctx context.Context, arg MarkSoldOutParams) error {
	_, err := q.db.Exec(ctx, markSoldOut, arg.StoreID, arg.SalesDay, arg.DishID)
	return err
}

const upsertDailySales = `-- name: UpsertDailySales :one
INSERT INTO daily_sales (store_id, sales_day, dish_id, quantity)
VALUES ($1, $2, $3, $4)
ON CONFLICT (store_id, sales_day, dish_id)
DO UPDATE SET quantity = daily_sales.quantity + EXCLUDED.quantity
RETURNING id, store_id, sales_day, dish_id, quantity, sold_out
`

type UpsertDailySalesParams struct {
	StoreID  int64       `json:"store_id"`
	SalesDay pgtype.Date `json:"sales_day"`
	DishID   int64       `json:"dish_id"`
	Quantity int64       `json:"quantity"`
}

func (q *Queries) UpsertDailySales(ctx context.Context, arg UpsertDailySalesParams) (DailySale, error) {
	row := q.db.QueryRow(ctx, upsertDailySales,
		arg.StoreID,
		arg.SalesDay,
		arg.DishID,
		arg.Quantity,
	)
	var i DailySale
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.SalesDay,
		&i.DishID,
		&i.Quantity,
		&i.SoldOut,
	)
	return i, err
}
