// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: screens.sql

package db

import (
	"context"
)

const createScreen = `-- name: CreateScreen :one
INSERT INTO screens (store_id, name, token_hash)
VALUES ($1, $2, $3)
RETURNING id, store_id, name, token_hash, last_seen_at, created_at
`

type CreateScreenParams struct {
	StoreID   int64  `json:"store_id"`
	Name      string `json:"name"`
	TokenHash string `json:"token_hash"`
}

func (q *Queries) CreateScreen(ctx context.Context, arg CreateScreenParams) (Screen, error) {
	row := q.db.QueryRow(ctx, createScreen, arg.StoreID, arg.Name, arg.TokenHash)
	var i Screen
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Name,
		&i.TokenHash,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const getScreenByTokenHash = `-- name: GetScreenByTokenHash :one
SELECT id, store_id, name, token_hash, last_seen_at, created_at
FROM screens WHERE token_hash = $1
`

func (q *Queries) GetScreenByTokenHash(ctx context.Context, tokenHash string) (Screen, error) {
	row := q.db.QueryRow(ctx, getScreenByTokenHash, tokenHash)
	var i Screen
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Name,
		&i.TokenHash,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const listScreensByStore = `-- name: ListScreensByStore :many
SELECT id, store_id, name, token_hash, last_seen_at, created_at
FROM screens WHERE store_id = $1 ORDER BY id
`

func (q *Queries) ListScreensByStore(ctx context.Context, storeID int64) ([]Screen, error) {
	rows, err := q.db.Query(ctx, listScreensByStore, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Screen
	for rows.Next() {
		var i Screen
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.Name,
			&i.TokenHash,
			&i.LastSeenAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchScreen = `-- name: TouchScreen :exec
UPDATE screens SET last_seen_at = now() WHERE id = $1
`

func (q *Queries) TouchScreen(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchScreen, id)
	return err
}
