# Generated by Django 4.2.16 on 2026-09-21 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='engine.course')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_label', models.CharField(blank=True, default='', max_length=200)),
                ('filename', models.CharField(max_length=255)),
                ('source_format', models.CharField(choices=[('txt', 'TXT'), ('docx', 'DOCX')], max_length=8)),
                ('raw_content', models.BinaryField()),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('char_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='engine.submissionbatch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='engine.course')),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='engine.submission')),
            ],
        ),
        migrations.CreateModel(
            name='StyleSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('student', '学生样本'), ('reference', '参考范文'), ('known_ai', '已知 AI 文本样本')], default='student', max_length=16)),
                ('name', models.CharField(max_length=200)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('text', models.TextField()),
                ('feature_version', models.CharField(blank=True, default='', max_length=40)),
                ('feature_vector', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_samples', to='engine.course')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', '待领取'), ('RUNNING', '运行中'), ('SUCCEEDED', '成功'), ('FAILED', '失败')], db_index=True, default='PENDING', max_length=12)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('stage', models.CharField(choices=[('QUEUED', '排队'), ('EXTRACT', '文本提取'), ('NLP', 'NLP 标注'), ('METRICS', '指标计算'), ('STYLE', '风格相似度'), ('PERSIST', '结果落库')], default='QUEUED', max_length=12)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('not_before', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('worker_id', models.CharField(blank=True, default='', max_length=64)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('run_token', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.TextField(blank=True, default='')),
                ('error_detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='engine.submission')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('input_hash', models.CharField(max_length=64)),
                ('algorithm_version', models.CharField(max_length=40)),
                ('metrics', models.JSONField()),
                ('methodology', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='engine.submission')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='result', to='engine.analysistask')),
            ],
        ),
        migrations.AddIndex(
            model_name='submissionbatch',
            index=models.Index(fields=['course', '-created_at'], name='engine_subm_course__c8ed03_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['course', '-created_at'], name='engine_subm_course__8a9f9e_idx'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('course', 'content_hash'), name='uniq_content_hash_per_course'),
        ),
        migrations.AddConstraint(
            model_name='stylesample',
            constraint=models.UniqueConstraint(fields=('course', 'content_hash', 'label'), name='uniq_sample_course_hash_label'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['teacher'], name='engine_cour_teacher_820d3f_idx'),
        ),
        migrations.AddIndex(
            model_name='analysistask',
            index=models.Index(fields=['status', 'not_before'], name='engine_anal_status_34020f_idx'),
        ),
        migrations.AddIndex(
            model_name='analysistask',
            index=models.Index(fields=['lease_expires_at'], name='engine_anal_lease_e_39ab8a_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisresult',
            index=models.Index(fields=['submission', '-version'], name='engine_anal_submiss_e5ad67_idx'),
        ),
        migrations.AddConstraint(
            model_name='analysisresult',
            constraint=models.UniqueConstraint(fields=('submission', 'version'), name='uniq_result_version_per_submission'),
        ),
    ]
