# Generated by Django 5.0.14 on 2026-09-21 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('min_gpus', models.PositiveIntegerField()),
                ('max_gpus', models.PositiveIntegerField()),
                ('gpu_memory_mb', models.PositiveIntegerField()),
                ('priority', models.PositiveSmallIntegerField()),
                ('state', models.CharField(choices=[('PENDING', 'Queued / waiting to be scheduled'), ('RUNNING', 'Running'), ('PREEMPTING', 'Marked for preemption, expected to release GPUs'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled by user or queue timeout'), ('FAILED', 'Failed (e.g. its node was lost)')], default='PENDING', max_length=16)),
                ('finish_reason', models.CharField(blank=True, choices=[('COMPLETED', 'Worker reported completion'), ('USER_CANCELLED', 'Cancelled via API'), ('TIMEOUT', 'Queued for longer than QUEUE_TIMEOUT_SECONDS'), ('PREEMPTED', 'Evicted by a higher-priority job'), ('NODE_LOST', 'Host node went offline unexpectedly')], default='', max_length=20)),
                ('enqueued_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=128, unique=True)),
                ('gpu_count', models.PositiveIntegerField()),
                ('gpu_memory_mb', models.PositiveIntegerField()),
                ('admin_state', models.CharField(choices=[('ONLINE', 'Online (accepts new jobs)'), ('DRAINING', 'Draining (no new jobs; existing jobs keep running)'), ('OFFLINE', 'Offline (administratively down)')], default='ONLINE', max_length=16)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('marked_offline_at', models.DateTimeField(blank=True, null=True)),
                ('allocated_gpus', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ResourcePool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('max_total_gpus', models.PositiveIntegerField()),
                ('max_concurrent_jobs', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PreemptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Victims notified, waiting for them to release GPUs'), ('RELEASED', 'All victims released; beneficiary may be placed'), ('FAILED', 'Preemption attempt failed (release timed out / node lost)')], default='PENDING', max_length=12)),
                ('fail_reason', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preemption_requests', to='scheduler.job')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_preemptions', to='scheduler.node')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PreemptionVictim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpu_count', models.PositiveIntegerField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.job')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='victim_rows', to='scheduler.preemptionrequest')),
            ],
            options={
                'unique_together': {('request', 'job')},
            },
        ),
        migrations.AddField(
            model_name='preemptionrequest',
            name='victims',
            field=models.ManyToManyField(related_name='preempted_by_requests', through='scheduler.PreemptionVictim', to='scheduler.job'),
        ),
        migrations.AddField(
            model_name='preemptionrequest',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preemptions', to='scheduler.resourcepool'),
        ),
        migrations.AddField(
            model_name='node',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='scheduler.resourcepool'),
        ),
        migrations.AddField(
            model_name='job',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='scheduler.resourcepool'),
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpu_count', models.PositiveIntegerField()),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='allocation', to='scheduler.job')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='scheduler.node')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='scheduler.resourcepool')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SchedulingDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PLACED', 'Job placed on a node'), ('NO_FIT', 'Job could not fit any node'), ('PREEMPT_REQUESTED', 'Preemption initiated'), ('PREEMPT_RELEASED', 'Preempted resources released'), ('PREEMPT_FAILED', 'Preemption attempt failed'), ('SETTLED', 'A job was settled (complete/cancel/timeout/lost/preempt)'), ('NODE_OFFLINE', 'A node was marked offline (lost heartbeat/admin)'), ('NODE_RECOVERED', "A node's heartbeat recovered")], max_length=24)),
                ('summary', models.CharField(max_length=255)),
                ('detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='scheduler.job')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='scheduler.node')),
                ('pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='scheduler.resourcepool')),
                ('preemption', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='scheduler.preemptionrequest')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='preemptionrequest',
            index=models.Index(fields=['pool', 'status'], name='scheduler_p_pool_id_c594b9_idx'),
        ),
        migrations.AddIndex(
            model_name='preemptionrequest',
            index=models.Index(fields=['status'], name='scheduler_p_status_70d9d0_idx'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['pool', 'admin_state'], name='scheduler_n_pool_id_e0aa04_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['pool', 'state'], name='scheduler_j_pool_id_808d38_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['state', 'priority'], name='scheduler_j_state_012ca8_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulingdecision',
            index=models.Index(fields=['-created_at'], name='scheduler_s_created_2f7fbe_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulingdecision',
            index=models.Index(fields=['kind'], name='scheduler_s_kind_a0d5a8_idx'),
        ),
    ]
