# Generated by Django 5.1.15 on 2026-09-20 15:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourcePool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='资源池名称')),
                ('max_gpus', models.PositiveIntegerField(default=0, verbose_name='GPU 总配额')),
                ('max_running_jobs', models.PositiveIntegerField(default=0, verbose_name='最大并发作业数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '资源池',
                'verbose_name_plural': '资源池',
                'db_table': 'scheduler_resource_pool',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='节点名称')),
                ('gpu_count', models.PositiveIntegerField(default=0, verbose_name='GPU 数量')),
                ('gpu_memory_mb', models.PositiveIntegerField(default=0, verbose_name='单卡显存 MB')),
                ('status', models.CharField(choices=[('available', '可用'), ('occupied', '占用'), ('draining', '排空'), ('offline', '离线')], default='available', max_length=16, verbose_name='节点状态')),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True, verbose_name='最近心跳')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nodes', to='scheduler.resourcepool')),
            ],
            options={
                'verbose_name': '节点',
                'verbose_name_plural': '节点',
                'db_table': 'scheduler_node',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='作业名称')),
                ('min_gpus', models.PositiveIntegerField(verbose_name='最少 GPU 数')),
                ('max_gpus', models.PositiveIntegerField(verbose_name='最多 GPU 数')),
                ('gpu_memory_mb', models.PositiveIntegerField(default=0, verbose_name='要求单卡显存 MB')),
                ('priority', models.PositiveSmallIntegerField(default=5, verbose_name='优先级')),
                ('status', models.CharField(choices=[('queued', '排队中'), ('allocated', '已分配待启动'), ('running', '运行中'), ('preempted', '被抢占'), ('succeeded', '成功'), ('failed', '失败'), ('cancelled', '已取消'), ('timed_out', '超时取消')], default='queued', max_length=16, verbose_name='作业状态')),
                ('queued_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='入队时间')),
                ('allocated_at', models.DateTimeField(blank=True, null=True, verbose_name='分配时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始运行时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('run_timeout_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('status_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='状态原因')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='scheduler.resourcepool')),
            ],
            options={
                'verbose_name': '作业',
                'verbose_name_plural': '作业',
                'db_table': 'scheduler_job',
            },
        ),
        migrations.CreateModel(
            name='SchedulingDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('schedule', '调度分配'), ('skip', '跳过（资源不足/碎片）'), ('preempt_attempt', '尝试抢占'), ('preempt_result', '抢占结果'), ('queue_timeout', '排队超时取消'), ('run_timeout', '运行超时取消'), ('settle', '作业结算'), ('node_offline', '节点失联'), ('node_recover', '节点恢复'), ('drain', '节点排空')], max_length=20)),
                ('rationale', models.JSONField(default=dict)),
                ('success', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='scheduler.job')),
                ('node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='scheduler.node')),
                ('pool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='scheduler.resourcepool')),
            ],
            options={
                'verbose_name': '调度决策',
                'verbose_name_plural': '调度决策',
                'db_table': 'scheduler_decision',
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpu_count', models.PositiveIntegerField(verbose_name='占用 GPU 数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='scheduler.job')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='scheduler.node')),
            ],
            options={
                'verbose_name': '分配关系',
                'verbose_name_plural': '分配关系',
                'db_table': 'scheduler_allocation',
                'indexes': [models.Index(fields=['node'], name='scheduler_a_node_id_5beadb_idx'), models.Index(fields=['job'], name='scheduler_a_job_id_f185b7_idx')],
                'constraints': [models.UniqueConstraint(fields=('job', 'node'), name='uq_allocation_job_node')],
            },
        ),
        migrations.CreateModel(
            name='PreemptionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=False)),
                ('detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('preemptor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preemptions_as_preemptor', to='scheduler.job')),
                ('victim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preemptions_as_victim', to='scheduler.job')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.resourcepool')),
            ],
            options={
                'verbose_name': '抢占记录',
                'verbose_name_plural': '抢占记录',
                'db_table': 'scheduler_preemption',
                'indexes': [models.Index(fields=['pool', 'success'], name='scheduler_p_pool_id_bae7da_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['pool', 'status'], name='scheduler_n_pool_id_bcf8a2_idx'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['last_heartbeat_at'], name='scheduler_n_last_he_bf9d3e_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['pool', 'status', '-priority', 'queued_at'], name='scheduler_j_pool_id_ca1b31_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status'], name='scheduler_j_status_69fd68_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['queued_at'], name='scheduler_j_queued__b2f4ed_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulingdecision',
            index=models.Index(fields=['pool', 'kind'], name='scheduler_d_pool_id_4cb309_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulingdecision',
            index=models.Index(fields=['job', 'kind'], name='scheduler_d_job_id_5ea6f5_idx'),
        ),
    ]
